### ISSUE TITLE
第88期资讯里第二条“骨髓移植的 DNA 问题”理解当有误

### ISSUE THREAD

**Issue by wyu0725** [ruanyf/weekly#1025]
“更麻烦的是，他的精子里面所有的 DNA，都来自捐助者，这意味着这些精子产生的后代从生物学意义来说，都不是他的后代。”原文的理解应该是精液里面的DNA来自捐助者，而这个患者是做了输精管切除手术，所以他的精液没有精子，只有精液——主要是白细胞。
原文同样是在New York times 上https://www.nytimes.com/2019/12/12/science/chimera-bone-marrow-dna-semen.html

**Comment by ruanyf** [comment]
不好意思，我没注意结扎这一点，已经改正了。
