### ISSUE TITLE
去理发结果花费两千多，我好像遇到了除螨骗局~

### ISSUE THREAD

**Issue by shxingzhe** [ruanyf/weekly#1029]
[去理发结果花费两千多，我好像遇到了除螨骗局~](https://mp.weixin.qq.com/s/7nJw9wJiKS_xj_aw5z-gDw)
本文介绍了作者遭遇理发除螨骗局事件的完整始末，并且整理了多年来这类骗局的特征，分析了受害者和旁观者的微妙心理，也深入地剖析了人性的复杂，呼吁大家尽举手之劳让世界多一点友爱。

**Comment by AGDholo** [comment]
原帖
https://www.v2ex.com/t/631890

**Comment by jiangen1016** [comment]
???
