### ISSUE TITLE
[建议]增加订阅服务

### ISSUE THREAD

**Issue by lnsane** [ruanyf/weekly#1032]
非常不错的内容，不知道有没有邮箱订阅模式，哎。常常因为工作太忙而忘记看了。

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/71638250-1ce97580-2c96-11ea-9305-63280d7cba8a.png)
watch就好了

**Comment by lnsane** [comment]
@CodFrm 谢谢
