### ISSUE TITLE
关于更换文章图片为连接后产生的问题

### ISSUE THREAD

**Issue by DavidWhom** [ruanyf/weekly#1047]
以前weekly的图片都是直接和仓库放一起的，现在换成了链接的形式。
- github 被墙，图片加载缓慢，很影响体验
- pull weekly后本地无法显示图片，起码typora是这样的
希望能够解决下，很影响体验。看不了图片很难受

**Comment by ruanyf** [comment]
图片一直是链接，从来没有放在仓库里面。因为那样的话，仓库就太大了。

GitHub 用自己的服务器缓存图片，可能被墙了。你直接访问下面的链接，能打开吗？https://www.wangbase.com/blogimg/asset/201912/bg2019120604.jpg

**Comment by DavidWhom** [comment]
不好意思，不严谨了。之前是图片加载得慢。所以每次都是pull到本地看。应该是我们公司网络把控更严格了。所以访问不了你的图片服务器
现在翻墙只能翻墙看。
谢谢回复，会一直关注weekly
