### ISSUE TITLE
如何搜索历史周刊文章？

### ISSUE THREAD

**Issue by GOODXIONG** [ruanyf/weekly#1084]
例如，我记得之前看过一篇关于国外自制个性名片的文章，但是想不起来是哪一期的了，如何可以实现搜索？

**Comment by ruanyf** [comment]
1. 把这个仓库克隆到本地。
1. 使用 grep 搜索。

**Comment by tangkaichuan** [comment]
推荐使用 sourcegraph

https://sourcegraph.com/github.com/ruanyf/weekly

![sourcegraph](https://user-images.githubusercontent.com/32519285/75676486-49386700-5cc4-11ea-945c-bdb686ebc4eb.png)

**Comment by ruanyf** [comment]
@tangkaichuan 已经加到了仓库首页。
