### ISSUE TITLE
【错误】：98期--资讯--3、第一种不需要氧气的生物

### ISSUE THREAD

**Issue by BruinK** [ruanyf/weekly#1127]
科学家发现一种多细胞生物（上图），不需要氧气就能生存，成为已知唯一的不需要氧气的生物。由于生物的能量来源是细胞内部的线粒体呼吸效应（通过氧气生成三磷酸腺苷获取能量），所以所有的生物都需要氧气。

---------------------------------------------------
可以明确：地球上所有多细胞动物的共同特征之一是线粒体呼吸。
所以正确的说法应该是：第一种不需要氧气的多细胞生物。
说明：在生物的分类中本身就包含需氧型生物和厌氧型生物。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
