### ISSUE TITLE
能否把图片文件也放到这里

### ISSUE THREAD

**Issue by Vigi0303** [ruanyf/weekly#1157]
如题，现在的md文档中引用的图片资源都来自域名www.wangbase.com，
能否拷贝一份放到这个repo中，并修改md文件中图片资源的引用地址到这里。
使repo和博客解耦。

**Comment by ruanyf** [comment]
大量的二进制文件不适合放在 Git 仓库。

**Comment by Vigi0303** [comment]
感谢回复。

> 大量的二进制文件不适合放在 Git 仓库。

关于这个问题，我仔细想了一下：

- 周刊的图片作为静态资源，提交后几乎不会被二次修改，每次提交都是一份新的内容。导致图片在git中的存储是铺平式的(flat)，不会产生大量冗余的历史数据（事实上，因为没有diff的情况，根本不会产生冗余数据）；

- 同时，在搜索时，给grep加上`-I`参数，会跳过对二进制文件的匹配，所以不会影响文字搜索的结果和效率。

至于把图片资源存在其他地方，如之前所说。如果www.wangbase.com出现问题，甚至放弃维护，或者修改域名，修改路径等。这里的文档由于没有配图，几乎无法观看。那么这个repo也将失去意义。

希望我提出的想法具有参考价值。

**Comment by ruanyf** [comment]
放入图片以后，仓库克隆到本地就麻烦了。另外，视频要不要放入仓库呢？

现在的图床是我在维护，所以问题还不大。
