### ISSUE TITLE
CodeCombat 代码战斗

### ISSUE THREAD

**Issue by Ynjxsjmh** [ruanyf/weekly#117]
[CodeCombat](https://codecombat.com) 是一款有趣开源的编程游戏！它使用代码来操控游戏人物.

**Comment by ruanyf** [comment]
收入第 35 期。

**Comment by Ynjxsjmh** [comment]
今天无意中在知乎专栏中发现了更多游戏 [12 款助你学编程的免费游戏](https://zhuanlan.zhihu.com/p/23936161)
