### ISSUE TITLE
【自荐】如何在非英文输入法下愉快地写 Markdown

### ISSUE THREAD

**Issue by hbhde** [ruanyf/weekly#1186]
[Markable](https://github.com/hbhde/markable) 能让我们用任何语言编写 Markdown 文档。它将非英文的与 Markdown 语法相关的字符翻译成英文，以便任何 Markdown 解析器都可以解析它们（即是，使它们变得 “markable” ）。

这样，当我们在用中文写作的时候（或者其他任何语言），不再需要为了使用 Markdown 语法，而切换到英文，然后再切回来。

让我们直接在 [实时编辑器](http://lengyue.ink/markable-markdown-editor/) 中看看 markable 是怎么工作的吧！

**Comment by Lionad-Morotar** [comment]
我喜欢等宽英文 φ(*￣0￣)

**Comment by hbhde** [comment]
> 我喜欢等宽英文 φ(*￣0￣)

喜欢呢，只是频繁切换输入法挺麻烦的 ( ´▽｀)

**Comment by hanxi** [comment]
用shift切换输入法，很快

**Comment by hbhde** [comment]
> 用shift切换输入法，很快

在macOS里，据我所知，想切换输入法至上需要按两个键，默认的是control + space。
