### ISSUE TITLE
[个人建议]怎样才能延长周刊的半衰期，使得它有更多被用到的机会？

### ISSUE THREAD

**Issue by GOODXIONG** [ruanyf/weekly#1192]
周刊目前就是一周一刊，每周五上新。
一周过去了就真的没有人看了吗？我不这么认为。

我想起了有个网站:[hellogithub](https://hellogithub.com)
该网站是一个信息聚合网站，主要还是一些编程工具和框架推荐，该网站定期推送都没有，我觉得只是准备足够多的新内容才会出新的一期。
该网站的内容每次更新完很快就没人看了吗？
然而并不是，该网站还有一个分类查询功能，我可以随时按自己想要查看的类别去浏览历史信息，非常方便，我自己经常用，毕竟很多信息很好，但不可能自己记得住。该案例值得参考。

其实我想说的是：如果一个周刊类信息流，通过加工，新增了其他需求的功能，一定能延长半衰期。

**Comment by ruanyf** [comment]
谢谢建议。后面考虑搭建一个资源分类网站，采用 serverless 的数据库服务，我还在准备。
