### ISSUE TITLE
[第 105 期] [自荐][Chrome插件-小悦记]可以导出微信读书APP里面的笔记；支持Markdown等三种格式

### ISSUE THREAD

**Issue by zxhycxq** [ruanyf/weekly#1198]
具体介绍在这里
神器安利！可以一键导出微信读书笔记|支持Markdown等三种格式  https://mp.weixin.qq.com/s/hCZWQEfHrCAxTiO0h8ukJw

Chrome 应用商店地址：（搜索小悦记即可）https://chrome.google.com/webstore/detail/%E5%B0%8F%E6%82%A6%E8%AE%B0/dcfmienoiahabnladhacocfbhngagpok

希望能够帮助到大家，O(∩_∩)O谢谢

**Comment by davix** [comment]
没放到github上吗？求firefox插件

**Comment by zxhycxq** [comment]
你好，不知道Firefox出什么问题了，检测不通过，就暂时没放。

**Comment by zxhycxq** [comment]
@davix  你可以在360浏览器应用商店安装（直接搜索即可），是可以正常使用的。
