### ISSUE TITLE
[纠错]第27期中"1.3部"应该为"1.3亿部"

### ISSUE THREAD

**Issue by Anderson-Liu** [ruanyf/weekly#12]
![image](https://user-images.githubusercontent.com/8468372/47197585-c302d580-d399-11e8-8810-4e6666487738.png)

具体位置在 https://www.yuque.com/ruanyf/share/issue-27#q2qfet 中手机最终销量应该为1.3亿部

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
