### ISSUE TITLE
[自荐] 《从零开始的 Flutter 动画》

### ISSUE THREAD

**Issue by xrr2016** [ruanyf/weekly#1207]
花了挺长时间写的一篇关于 Flutter 动画的文章 😝

[从零开始的 Flutter 动画](https://coldstone.fun/post/2020/04/26/flutter-animation-from-zero/)

**Comment by halk947** [comment]
@xrr2016  链接404

**Comment by xrr2016** [comment]
> @xrr2016 链接404

修复了 thx
