### ISSUE TITLE
[第 106 期] [工具] Markdown 工具推荐

### ISSUE THREAD

**Issue by YLongo** [ruanyf/weekly#1218]
[Vditor](https://github.com/Vanessa219/vditor)

- 一款浏览器端的 Markdown 编辑器，支持所见即所得、即时渲染（类似 Typora）和分屏预览模式

[liandi](https://github.com/88250/liandi)

- 一款桌面端的 Markdown 笔记应用，支持 Windows、Mac 和 Linux。

**Comment by XueshiQiao** [comment]
这个工具不错
