### ISSUE TITLE
[自荐]口红色号推荐小程序

### ISSUE THREAD

**Issue by rogerzhu** [ruanyf/weekly#1243]
这是我自己开发的口红色号推荐小程序，用户可以通过输入一只口红的色号，含有1300多个口红色号。

经过我自己琢磨训练出的ai模型找到相近的色号，目标是想提供不知道该送啥色号给女生的男生一点帮助，以及找到可能也适合自己的相似色号的女生。

<img width="419" alt="屏幕快照 2020-05-12 下午9 42 27" src="https://user-images.githubusercontent.com/943583/81699836-752d5100-949a-11ea-8c28-6b98db9ba967.png">
<img width="415" alt="屏幕快照 2020-05-12 下午9 42 15" src="https://user-images.githubusercontent.com/943583/81699862-7e1e2280-949a-11ea-9e0f-75446290ad68.png">
<img width="415" alt="屏幕快照 2020-05-12 下午9 41 57" src="https://user-images.githubusercontent.com/943583/81699871-82e2d680-949a-11ea-8faf-6233f7033bcb.png">

![gh_833cc648ccad_344](https://user-images.githubusercontent.com/943583/81700025-b32a7500-949a-11ea-838e-774169b63bf2.jpg)

**Comment by Rivalsa** [comment]
有没有帮助男生们认识口红色号的小程序呀？
