### ISSUE TITLE
yf大大用telegram嘛？

### ISSUE THREAD

**Issue by ichn-hu** [ruanyf/weekly#125]
如果用的话可以开一个channel，我可以帮忙管理！
如果不用的话，我可以解释下，channel类似于微信朋友圈，但是是以一种订阅的方式进行广播的，感觉非常好用的说，好处在于可以及时的广播更新，也能扩大受众和影响力。同样我也愿意帮忙打理channel，感谢yyf大大的心血整理啦！

**Comment by ruanyf** [comment]
转载和再加工，都可以，完全没有问题。

这个周刊是开源的，我希望能够搞成一个社区产品，许可跟维基百科一致。
