### ISSUE TITLE
[自荐]vscode 微信读书插件

### ISSUE THREAD

**Issue by goobyter** [ruanyf/weekly#1264]
vscode 结合puppeteer无头浏览器开发的微信读书插件，主题色和vscode完全一样，具有非常好的阅读体验，对于喜欢阅读的人非常实用。将来会支持注入自定义css,自己配置喜欢的主题。https://marketplace.visualstudio.com/items?itemName=goobyter.vscode-weixin-read
<img src="https://images.redream.cn/upic/2019/20200520001558-ohsPIa.jpg">

**Comment by elowes** [comment]
那个登录成功会弹出 hhhhh。。。

**Comment by AUGUSTRUSH8** [comment]
> 那个登录成功会弹出 hhhhh。。。

对，这个弹出的hhh，有时会影响底部菜单栏，非常影响阅读体验

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/83590366-2bf78b00-a588-11ea-808e-8eb9b0a7484f.png)
报错

**Comment by Adiwon** [comment]
> ![image](https://user-images.githubusercontent.com/30563826/83590366-2bf78b00-a588-11ea-808e-8eb9b0a7484f.png)
> 报错

遇到同样错误，是因为我没有安装谷歌官方版chrome浏览器吗？我的浏览器是chromium内核的cent

**Comment by oldthreefeng** [comment]
这个插件就很秀了.

**Comment by dyenene** [comment]
哈哈哈不错不错 今天忽然想到可不可以在vscode中看书 没想到真有

**Comment by ppoak** [comment]
目前微信读书vscode版无法登陆，扫码后闪一下就恢复未登陆的状态，烦请开发者大大修复！ @goobyter

**Comment by muchenlou** [comment]
2022年11月17日，无法登录微信读书 WeiXin Read

**Comment by muchenlou** [comment]
2022年11月17号，无法灯舞微信读书    和 上面一条原因一样

**Comment by Tastelessor** [comment]
2023-2-24依然无法登录

**Comment by dahangda** [comment]
求大神修复呀

**Comment by wtskyler** [comment]
2023-2-28依然无法登录，求大神修复🙏
