### ISSUE TITLE
猥亵/强奸儿童在中国的状况

### ISSUE THREAD

**Issue by luoxugeng** [ruanyf/weekly#1278]
2019年猥亵儿童,强奸儿童在[中国文书网](https://wenshu.court.gov.cn/)相关的判决有2455篇.我通过阅读这些判决, 处理文本和统计后, 做了这个[放过儿童](https://nemolaw.com/spare-the-child/)的项目.  在六一这一天上线,希望有更多的人看到
![spare-the-child-pic-3](https://user-images.githubusercontent.com/20366486/83614648-11d5a100-a5b8-11ea-9076-c0dfc9b98044.jpg)

**Comment by ruanyf** [comment]
请不要发与科技无关的内容。
