### ISSUE TITLE
Github Events: 输入用户名，就能看到该用户在 Github 上的所有活动历史记录

### ISSUE THREAD

**Issue by able8** [ruanyf/weekly#129]
第 32 期 介绍了[GitHub Timeline](https://githubtimeline.xyz), 我给修改了下，变成 Github Events
输入用户名，就能看到该用户在 Github 上的所有活动历史记录，除了私有项目的。
[https://able8.github.io/github-events/?username=ruanyf](https://able8.github.io/github-events/?username=ruanyf)

**Comment by ruanyf** [comment]
收入第 36 期。
