### ISSUE TITLE
【自荐】支持109种语言的提示用户停用IE浏览器的开源项目

### ISSUE THREAD

**Issue by cjh0613** [ruanyf/weekly#1319]
全球第一个支持109种语言的抵制IE开源项目。当IE浏览器（包括使用IE内核的浏览器）访问网站时，它将识别语言自动跳转到浏览器升级页面。

只需在网页源代码<head></head>间添加（尽量靠前）：
```
<script src="https://boycott-ie.github.io/boycott-ie/boycott-ie.js"></script>
```

也可clone到服务器使用。

项目地址：https://github.com/boycott-ie/boycott-ie

**Comment by MichaelPorter0** [comment]
有点东西

**Comment by wp2123** [comment]
这项目算啥方向？前端开发福利？鞭策科技进步？有点迷啊
