### ISSUE TITLE
开源博客主题推荐: theme-bmw

### ISSUE THREAD

**Issue by dongyuanxin** [ruanyf/weekly#133]
![](https://godbmw.com/images/开源项目/开源博客-theme-bmw-微声版发布/theme-bmw.jpg)

阮大您好,这个主题是我开发了1年的一款主题,经历了从 Vuejs+Node => Hexo 的过程变迁.总的来说,**是希望在保证功能齐全的情况下,提供一个更好的用户体验和更清爽的UI设计**! 

这次版本的代号是"**微声**", **寓意是希望每个人都可以记录知识 & 分享创造, 每个人也有资格为自己发声**( 这个主题做的就是让发声过程更简单!).

Github地址: [https://github.com/dongyuanxin/theme-bmw](https://github.com/dongyuanxin/theme-bmw)
~~vuejs版本地址(已经停止维护): [https://github.com/dongyuanxin/vuejs-theme-bmw](https://github.com/dongyuanxin/vuejs-theme-bmw)~~

**此致敬上**

**Comment by dongyuanxin** [comment]
再放一张专门录制的gif动图(时长 55秒):

![](https://godbmw.com/images/开源项目/开源博客-theme-bmw-微声版发布/theme-bmw.gif)

**Comment by Seven-Steven** [comment]
@dongyuanxin 
很优秀的主题, 加油!

**Comment by dongyuanxin** [comment]
> @dongyuanxin
> 很优秀的主题, 加油!

Thanks♪(･ω･)ﾉ
