### ISSUE TITLE
阮老师您好，麻烦更正第114期[24]：如何不靠运气变得富有的github地址

### ISSUE THREAD

**Issue by lg565245594** [ruanyf/weekly#1330]
老师您好，我是「胖车库」公众号作者Jessie，也是Naval「如何不靠运气变得富有」系列的译者。我是昨天知道我的文章“被”投稿（而且删减了一些内容），然后幸运地被您的周刊收录了，但是GitHub地址不是我的地址，可以麻烦您修改一下吗？我的GitHub是：https://github.com/fat-garage/how-to-get-rich-without-getting-lucky或者放我的公众号也是可以的～

感谢您的青睐，之后我会自己向您投稿我的原创内容！同时也特别开心有这么多的科技爱好者们喜欢Naval！我自己也在实践中希望和大家更多分享:)

**Comment by Bakumon** [comment]
建议自己提 PR

**Comment by ruanyf** [comment]
改好了

**Comment by lg565245594** [comment]
谢谢老师！之后找您投稿^ ^

Ruan YiFeng <notifications@github.com> 于2020年7月5日周日 下午9:56写道：
