### ISSUE TITLE
有钓鱼链接和错误引导消费！

### ISSUE THREAD

**Issue by wkingfly** [ruanyf/weekly#1395]
“最近阮一峰的这个周刊出现几个问题：
1. 有的推荐的一些工具是钓鱼工具，会窃取cookie信息
2. 一些推荐描述是完全免费的产品在到期后会自动扣除付费。
这些有可能是无意，但也有得是有意为之，大家提高警惕不可完全相信！”

**Comment by ruanyf** [comment]
哪个软件？

Walter <notifications@github.com> 于 2020年8月31日周一 下午5:54写道：

**Comment by wkingfly** [comment]
属于 songwhip.com

**Comment by ruanyf** [comment]
Hacker News 论坛上，没人反应 SongWhip 有问题，软件作者还在那里与用户交流，看上去不像恶意软件。而且，它是免费的，应该不会扣费。
https://github.com/ruanyf/weekly/issues/1395#issuecomment-683727797

能否详细描述一下你遇到的问题。

**Comment by ruanyf** [comment]
另外，“完全免费的产品在到期后会自动扣除付费”，也是 Songwhip.com 吗？

没看到它要求提交信用卡信息啊。

**Comment by wkingfly** [comment]
扣费的是 course

**Comment by wkingfly** [comment]
使用搜索后歌曲并打开链接后，Spotify账号被锁定官方原因是恶意欺诈。同时豆瓣，京东等一些常见网站的证书显示为不可信。没有细查，但回顾了一下只是在试用了
songwhip 的时候才发生了这些问题。

另外，即使没有这回事，也应该对所有提交的链接做一遍恶意URL检测再发出来做一个强制规则。

**Comment by ruanyf** [comment]
我使用 Songwhip，没有遇到这个问题。如果我没搞错，它是直接的 GET 跳转，很难有恶意行为的。

试用期结束就信用卡扣费，欧美服务往往都这样，需要自己小心。你可以跟他们的客服联系，应该可以退费。

周刊可能有错误，但是非常干净。除了每期的课程推广，跟所有内容都没有利益关系。

**Comment by wkingfly** [comment]
既然是这样,那周刊里就应该说清楚,试用就是试用不要说成是完全免费误导读者被消费.

所有的推荐链接发布之前过一遍恶意URL检测,Google等一些大厂是有这个服务的.

Ruan YiFeng <notifications@github.com> 於 2020年8月31日 週一 下午11:48寫道：

**Comment by ruanyf** [comment]
周刊都是免费内容，收费都会说清楚。

不排除有个别漏网之鱼，以后会加强检查。但是，我也认为，不应该把自己的使用不当，恶意归咎为周刊的责任。

由于这个帖子并不符合事实，稍后会被删除。

以后，发布指控时，请给出详细的证据（链接和截图），否则将被禁止在这里发言。

**Comment by wkingfly** [comment]
关于是否拿了钱故意做推广而不承认,我截了两张图,以此说明.不止我一个人这样认为. 归咎于读者的使用不当是怎么证明的? 
如果周刊里包含恶意链接,周刊不应该负责任吗?
就算这次的链接没有提交正确,那么所有链接发布之前做一遍URL恶意检测不对吗?
直接 close issue 这种做法还真是可以的.

![image](https://user-images.githubusercontent.com/3353680/91794381-794dcc00-ec4d-11ea-8e0b-1d9a2daed471.png)
![image](https://user-images.githubusercontent.com/3353680/91794465-b31ed280-ec4d-11ea-928c-9961a4c43017.png)

**Comment by ruanyf** [comment]
你的截图是推特，不是周刊。周刊已经做了修正，写明这是要收费的，你可以查看。

如果你对这里如此不信任，我建议你不要再看了。你从来没有为这里做出过贡献，稍有不满就横加指责，我认为服务你这样的读者不值得。

**Comment by wkingfly** [comment]
推特是第比较接近的一次了，容易搜索得到所以截图了推特上的。

我正是很信任这个周刊所以才会在最近出现问题就赶紧提出来。

放在 github 上做开源周刊，提出bug和问题不叫贡献而是叫做 **横加指责** 这难道是阮一峰特色开源的理念？
