### ISSUE TITLE
【推荐】：对话罗永浩：你们别把我还债这件事想得那么了不起

### ISSUE THREAD

**Issue by ShayLau** [ruanyf/weekly#1448]
文章原文：https://mp.weixin.qq.com/s/fZiL--mNFTRIwHuPVYR9Ug，

截取片段:
所以我这儿也碰到过很多年轻人来，给了一个职位，然后一开工，我有时候多问了几句他就很受伤，他说希望我能给他更多的信任。这个说法我是特别不爱听的。你在职场上，从老板那儿的信任和尊重都是你赢来的，没有一个是老板给你的。为什么有的人来了那么多年，也在一个比较高的位置上，但我从来不拿他的意见当回事，我只是没有找到替换他的人，所以他就还在那个位置，因为好过没有嘛。
 
但是有的人呢，来的时候级别也不高，上班一个月我就对他很客气，很重视他的意见，即使不高兴，我也会把他叫到小屋里两个人吵架，不会当着那些人的面去说他。原因是这块业务给他了，他就一个人把这块天空撑起来了，所以其实做老板的都是最现实。

**Comment by weipengyao** [comment]
@ShayLau 文章链接打不开，能否更新一下？

**Comment by yansheng836** [comment]
后面多了个逗号，超链接最好使用`<>`符号括起来。

**Comment by ShayLau** [comment]
[对话罗永浩：你们别把我还债这件事想得那么了不起 ](https://mp.weixin.qq.com/s/fZiL--mNFTRIwHuPVYR9Ug)

@weipengyao @yansheng836
