### ISSUE TITLE
[推荐开源项目] Vue Hooks From: 使用 Vue composition API 来构建你的表单

### ISSUE THREAD

**Issue by beizhedenglong** [ruanyf/weekly#1484]
给大家推荐一个最近做的一个新项目：[Vue Hooks From](https://github.com/beizhedenglong/vue-hooks-form)，使用 Vue 3 的新特性来构建你的表单。

## 特性
- 与 UI 解耦：可以与其他任何 UI 组建库无缝衔接。
- 简单易用：没有什么酷炫的东西，仅仅是响应式的 values/errors 。
- 支持深度嵌套的数据。
- Typescipt 支持。

Github: https://github.com/beizhedenglong/vue-hooks-form
文档：https://beizhedenglong.github.io/vue-hooks-form/

**Comment by liuxsen** [comment]
看着不好用，习惯了2里面的element ui的写法

liuxsen

**Comment by beizhedenglong** [comment]
和 element ui 的 form 组件不是一个维度的东西，因为这个是和 UI 解耦，可以帮助开发者快速构建自己的表单组件。和 https://react-hook-form.com 是一个维度的东西

**Comment by liuxsen** [comment]
恩，理解。

liuxsen

**Comment by crown-li** [comment]
和[vuelidate](https://www.vuelidate.cn/)很像

**Comment by beizhedenglong** [comment]
@crown-li 看了一下这个库，想要实现的功能类似，vuelidate 是用mixin 实现的，包含了一些样式/UI相关的API。Vue Hooks From 是 composition API 实现的，纯逻辑的库
