### ISSUE TITLE
急聘 #前端开发工程师# #高级前端开发工程师#

### ISSUE THREAD

**Issue by youfangg** [ruanyf/weekly#1506]
大家好，你好，我是编程猫产品线的产品负责人，目前正在启动一个新项目，需要一些伙伴一起参与共同推进研发。

编程猫（Codemao）是中国知名青少年编程教育品牌，本着“无趣味，不编程”的教育理念，为全球青少年研发了图形化编程平台及系列编程课。目前公司已完成 C 轮融资 6.5 亿，公司团队伙伴5000+ 人，总部总部位于深圳，分部已经遍布北京、广州、武汉、上海、长沙、贵阳等。

### 深圳 · 25~40K
您在编程猫会做这些（多个项目之一）:
1、桌面端 Web APP、Electron APP 以及其他相关前端页面的开发
2、移动端Hybrid APP及相关页面、社区的开发
3、Python 图形化工具的开发
4、通用组件与工具库的开发与维护
5、对 Web APP 的性能进行分析与优化
编程猫对您的期待：
1、统招本科及以上学历，计算机相关专业，3年以上前端开发经验，2年以上react项目经验
2、至少了解 HTML/CSS/Java"script"，并掌握至少一种可用于开发的计算机语言；
3、具备一定的算法与数据结构知识；
4、具备大型前端项目经验，并负责代码结构的设计工作；
5、熟悉单元测试，了解如何编写可测试的代码；
6、有以下经验更佳
Electron相关经验；
Windows客户端开发经验；
游戏开发相关经验；
移动端开发相关经验；
Python相关经验；

目前我所负责的项目主要招聘前端开发，欢迎直接将简历发送到我邮箱~   **haowei2@codemao.cn**
其他岗位如果需要内推，也欢迎将简历和所需要内推的岗位通过邮箱发送给我~
BOSS 直聘有更多研发岗位，欢迎投递。

**Comment by sk-xie** [comment]
感谢关注，但感觉和所找工作不是十分契合。。



在 2020-11-19 15:05:02，"youfangg" <notifications@github.com> 写道：

大家好，你好，我是编程猫产品线的产品负责人，目前正在启动一个新项目，需要一些伙伴一起参与共同推进研发。

编程猫（Codemao）是中国知名青少年编程教育品牌，本着“无趣味，不编程”的教育理念，为全球青少年研发了图形化编程平台及系列编程课。目前公司已完成 C 轮融资 6.5 亿，公司团队伙伴5000+ 人，总部总部位于深圳，分部已经遍布北京、广州、武汉、上海、长沙、贵阳等。

【前端开发工程师】
深圳 · 25~40K

您在编程猫会做这些（多个项目之一）:
1、桌面端 Web APP、Electron APP 以及其他相关前端页面的开发
2、移动端Hybrid APP及相关页面、社区的开发
3、Python 图形化工具的开发
4、通用组件与工具库的开发与维护
5、对 Web APP 的性能进行分析与优化
编程猫对您的期待：
1、统招本科及以上学历，计算机相关专业，3年以上前端开发经验，2年以上react项目经验
2、至少了解 HTML/CSS/Java"script"，并掌握至少一种可用于开发的计算机语言；
3、具备一定的算法与数据结构知识；
4、具备大型前端项目经验，并负责代码结构的设计工作；
5、熟悉单元测试，了解如何编写可测试的代码；
6、有以下经验更佳
Electron相关经验；
Windows客户端开发经验；
游戏开发相关经验；
移动端开发相关经验；
Python相关经验；

目前我所负责的项目主要招聘前端开发，欢迎直接将简历发送到我邮箱~ haowei2@codemao.cn
其他岗位如果需要内推，也欢迎将简历和所需要内推的岗位通过邮箱发送给我~
BOSS 直聘有更多研发岗位，欢迎投递。
