### ISSUE TITLE
第 135 期文章外链建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [ruanyf/weekly#1526]
[第 135 期文章章节](https://github.com/ruanyf/weekly/blob/master/docs/issue-135.md#文章) 中的第三篇文章外链可更改为不需要 App 即可查看的链接：https://www.coolapk.com/feed/22961813?shareKey=ZmFlODJiZmI1YzRhNWZjMmZhNGU

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
