### ISSUE TITLE
【文章编辑错误】 第135期-“本周话题：什么行业适合创业？”部分

### ISSUE THREAD

**Issue by seainm** [ruanyf/weekly#1528]
原文：
“上图的坐标系，竖轴是交易规模，位置越向上，表示交易金额越高；横轴是交易频率，位置越向右，表示交易次数越多。 **这里可以不用 return，因为没有用到累积变量。而且，每一轮 async 函数不管有没有 return，总是返回一个 Promise 对象。** 根据这两个坐标轴，所有行业可以分成四类。”
其中加粗部分应该是多出来的

**Comment by ruanyf** [comment]
谢谢提醒，昨天编辑的时候，不小心粘贴上去，现在已经改正了。
