### ISSUE TITLE
【上海米哈游】【内推】后端（GO、JAVA）/WEB前端/移动客户端/推荐算法/大数据/测试等大量岗位

### ISSUE THREAD

**Issue by hhqdsj** [ruanyf/weekly#1598]
【关于米哈游】上海米哈游网络科技股份有限公司(简称米哈游, milHoYo)成立于2011年,秉持“技术宅拯救世界”的信条,梦想成为世界一流的ACG内容与服务提供商。  
·《崩坏3》作为2016年重磅产品,集miHoYo多年技术积累之大成。在卡通渲染,动作表现,美术品质多方面,为表现出领先品质, iOS上线次日获AppStore推荐,迅速上升到畅销榜前10,并装安卓硬核联盟精品推荐。  
·《未定事件簿》作为米哈游在女性向领域的初次探索,于2020年7月30日正式公测,上线首日即冲入iOS国服游戏免费榜前3名。  
·《原神》--由米哈游自研的一款开放世界冒险游戏。米哈游以工匠之心倾力打造《原神》这一国产原创精品游戏力作,2020年在TGA 获得了最佳角色扮演游戏和最佳移动游戏的提名、Google Play 2020 年度最佳游戏、苹果 App Store 2020 年度最佳游戏。
  
### **面试方式：视频面试  
坐标：上海地铁九号线桂林路地铁站（上海市徐汇区宜山路700号）  
基本福利：16薪 + 全额五险一金 + 补充医疗保险 + 年度出国游 + 10天年假 + 带薪病假 + 免费晚饭+ 零食水果 + 免费体检  
薪资待遇：工资open可谈*16薪
**

**### 资深Golang后端开发**   
岗位职责：  
1、负责用户社区及通行证系统的开发及维护；  
2、负责游戏SDK和平台基础服务及组件的开发；  
3、负责游戏官网和活动相关平台的开发；  
4、负责公司内部游戏运营平台和协作效率工具开发；    
5、负责基础应用框架的维护和迭代，完善和优化服务治理系统，参与技术文档的编写。  
 
岗位要求：  
1、本科以上学历，有两年以上的服务端开发经验者优先；  
2、熟悉Go语言，有实际使用Go语言项目开发经验；  
3、对微服务架构有一定程度的研究并有开发经验，在服务治理，服务监控方面有相关经验；  
4、熟悉Web技术栈和Web应用开发，包括HTTP、安全、数据库、缓存、消息队列等；  
5、熟悉SQL和数据库设计，具备mysql数据库设计和性能优化经验；熟悉主流非关系性数据库、缓存技术，例如：Redis、MongoDB、Memcached等；  
6、掌握基本的前端知识js、ajax等，了解前后端分离架构；  
7、了解Linux/Unix系统常用命令，了解docker、kubernetes等容器技术；  
8、有高并发，海量用户经验优先。  

### **WEB前端开发**  
岗位职责：  
1、负责游戏社区产品的前端开发；  
2、负责游戏内容站（官网、攻略站、资料站、漫画站）系统的前端开发；  
3、负责H5小游戏活动的前端开发；  
4、负责运营系统和数据图表的前端开发；  
5、负责研发效率工具的前端开发。  
 
岗位要求：  
1、计算机或相关专业本科以上学历，2年及以上WEB端开发经验；  
2、熟悉ES6/CSS3/HTML5等开发调试技术，熟悉Vue或者React框架；  
3、必须要有1年以上C端项目的经验，项目类型不限；  
4、熟悉组件化开发，能就活动中常用功能的组件抽离出来，实现重用；  
5、有过研发效率工具项目经验可加分；  
6、希望应用新技术解决业务痛点，对细节有极致追求。  

### **移动客户端开发（Android、iOS）**  

岗位职责：  
负责公司面向用户的APP开发  
岗位要求：  
1、3年以上移动客户端开发经验；  
2、精通至少一个移动客户端平台（Android、iOS）的运行机制和架构体系；  
3、精通C/C++/OC/Java其中一种，具备扎实的数据结构、算法分析基础，熟悉常用设计模式、多线程、网络、界面开发；  
4、熟练掌握开发及版本控制工具，具备出色的程序优化、调试能力，良好的编程风格和文档习惯；  
5、具备高度责任感和团队合作精神，执行力强，良好的口头及书面表达能力。  

Java后端开发  
  
岗位职责：  
1、 根据产品需求和设计，独立完成内部系统的设计、开发、部署工作；  
2、 按照项目计划，按时提交高质量代码，完成开发任务；  
3、 规范文档的编写、维护，以及其他与项目相关工作。  
 
岗位要求：  
1、 大学本科以上学历，2年及以上使用JAVA开发的经验；  
2、 有扎实的Java基础，Java多线程、并发以及网络通信的经验；  
3、 精通主流开源应用框架，如Spring Boot、myBatis等开发技术；  
4、 精通设计模式、OOA/OOD，有一定Linux基础；  
5、 精通关系型数据库MySQL的性能优化、高可用；  
6、 熟悉Redis、MQ、elasticsearch等应用；  
7、 精通分布式系统的设计和应用，微服务、缓存、消息、负载均衡等机制和实现优先；  
8、 具备良好的沟通能力和团队协作精神，做事有责任心、有想法、喜欢钻研、热爱技术、有较强的自驱能力及抗压能力。  

WEB/APP测试（无需游戏测试经验）  

岗位职责：  
1、根据分配的测试任务和提供的测试文档，参加需求评审、用例编写、测试计划规划、测试项目进度跟进、bug追踪等内容；  
2、测试过程发现的缺陷在缺陷工具上提交缺陷报告、并及对修正的缺陷进行处理；  
3、完成与测试相关的任务，例如：需求分析、线上问题处理、参加培训等；  
4、具有较强的逻辑分析、协调、推进、故障排除、抗压能力；  
5、具有较好的人际沟通协调能力，有较强的责任感、进取精神和团队精神。  
  
岗位要求：  
1、3年以上工作经验；  
2、本科及以上学历；  
3、有移动端/web端、接口测试、性能测试经验；  
4、能独立完成安排的测试工作；  
5、熟练使用jmeter、postman、charles等工具；  
6、有操作linux、mysql、redis经验；  
7、项目经验有社区类app、webview活动类、管理后台优先；  
8、了解主流接口自动化框架、UI自动化框架，并且投入项目中使用者优先；  
9、了解敏捷项目相关知识。  

### **

简历投递方式：
方式一：添加微信 hhqdsj  
方式二：扫描下方二维码可以查看所有在招岗位与JD详情
![image](https://user-images.githubusercontent.com/37859524/104834440-3fb6ee00-58da-11eb-8abc-3f8192b7ea0f.png)

另有大量在招岗位：  
![image](https://user-images.githubusercontent.com/37859524/104834420-1302d680-58da-11eb-9b1a-6f21c6d632b9.png)

**

**Comment by ruanyf** [comment]
发到置顶的《谁在招人？》里面，不要单独发帖。
