### ISSUE TITLE
【147期】这个‘4、Youtube 计算机科学课程资源’，链接看不到哦，有谁知道具体内容，能再发一下具体内容嘛？谢谢谢啦

### ISSUE THREAD

**Issue by flitdu** [ruanyf/weekly#1654]

**Comment by ruanyf** [comment]
原网站不知何故下线了，只能看 Wayback Machine 了。

https://web.archive.org/web/20210210143025/https://laconicml.com/computer-science-curriculum-youtube-videos/

**Comment by flitdu** [comment]
@ruanyf 
thanks very much
