### ISSUE TITLE
请问如何通过rss订阅周刊？

### ISSUE THREAD

**Issue by BoyangMichael** [ruanyf/weekly#1679]
- 没有在`README`和issues里搜索到相关的内容。
- 试过github自带的feed，会有非issue类的commit干扰，而且看全文还要点击很多次跳转到`issue-xxx.md`。
- 试过rsshub，和github的feed一样的问题。
- 试过博主的博客，但是会有非周刊分类的内容干扰。（我用的是reeder，没有过滤内容的功能）。

请问是否有推荐的解决方案？非常感谢！

**Comment by ruanyf** [comment]
你可以选择 watch 这个仓库的 Releases。

我记得，inoreader 的收费版似乎有邮件转 RSS 功能。

**Comment by liumenghua** [comment]
> * 没有在`README`和issues里搜索到相关的内容。
> * 试过github自带的feed，会有非issue类的commit干扰，而且看全文还要点击很多次跳转到`issue-xxx.md`。
> * 试过rsshub，和github的feed一样的问题。
> * 试过博主的博客，但是会有非周刊分类的内容干扰。（我用的是reeder，没有过滤内容的功能）。
> 
> 请问是否有推荐的解决方案？非常感谢！

可以使用rsshub，https://github.com/DIYgod/RSSHub

**Comment by BoyangMichael** [comment]
> > * 没有在`README`和issues里搜索到相关的内容。
> > * 试过github自带的feed，会有非issue类的commit干扰，而且看全文还要点击很多次跳转到`issue-xxx.md`。
> > * 试过rsshub，和github的feed一样的问题。
> > * 试过博主的博客，但是会有非周刊分类的内容干扰。（我用的是reeder，没有过滤内容的功能）。
> > 
> > 请问是否有推荐的解决方案？非常感谢！
> 
> 可以使用rsshub，https://github.com/DIYgod/RSSHub

试过rsshub，和github自带rss feed一样的问题。@ruanyf 提出的订阅release也是一样的问题，链接是指向release压缩包的，想要查看文章内容还需要点击很多次。。。

目前我试过最好的方案是直接rss订阅@ruanyf 的博客，然后自己忽略非周刊的文章。

**Comment by madordie** [comment]
之前可以使用语雀外挂RSSHub然后151之后好像都抓不到了😭
