### ISSUE TITLE
【资源推荐】类似3B1B的算法与数据结构视频

### ISSUE THREAD

**Issue by jizai** [ruanyf/weekly#1685]
一个不错的数据结构与算法频道-Reducible，视频使用manim制作，也就是与3B1B一样的展示方式。该系列视频涉及动态数组，二叉树，图论，动画引擎等等，视频深入浅出，制作精良，十分推荐。
油管地址：https://www.youtube.com/channel/UCK8XIGR5kRidIw2fWqwyHRA
B站翻译：https://space.bilibili.com/50003725

**Comment by jizai** [comment]
![Snipaste_2021-03-19_10-44-44](https://user-images.githubusercontent.com/12199375/111724574-6d032680-88a0-11eb-9046-96ba4d06657d.png)
![Snipaste_2021-03-19_10-42-49](https://user-images.githubusercontent.com/12199375/111724631-83a97d80-88a0-11eb-99cc-b118ab6b3363.png)

PS：十分推荐看一下讲述FFT的那个视频，从算法角度理解FFT，很新颖~3B1B官博上也转发了这个视频。

**Comment by zstbee** [comment]
也是看了reducible对FFT的讲解后，一下子豁然开朗了

当场订阅！
