### ISSUE TITLE
【小建议】将每一期的内容添加到Release note中

### ISSUE THREAD

**Issue by chuanqisun** [ruanyf/weekly#1766]
- 读者可以使用固定的URL直接获取最新一周的内容。方便大家添加weekly为浏览器首页。具体效果参见: https://github.com/chuanqisun/weekly/releases/latest
- 读者可以连续阅读多期内容，利用GitHub自带的翻页工具，避免了逐一打开markdown文件的麻烦。具体效果参见: https://github.com/chuanqisun/weekly/releases
- 方便使用RSS阅读器的读者“足不出户”地阅览文章。利用GitHub自带的源订阅生成器，订阅地址: https://github.com/ruanyf/weekly/releases.atom (知道这个功能的人不多，博主可能需要在主页上加一些文档)

![image](https://user-images.githubusercontent.com/1895289/118376499-13a43480-b57d-11eb-8cde-59f172fcb1ac.png)

![image](https://user-images.githubusercontent.com/1895289/118376552-75649e80-b57d-11eb-8295-66352dc490b7.png)

**Comment by ruanyf** [comment]
新建 release 似乎只能网页操作。下一期我试试看，把内容放在 tag message 里面。
