### ISSUE TITLE
【自荐工具】Keptab - 功能强大并且数据能可靠保存的浏览器标签页管理工具

### ISSUE THREAD

**Issue by mywaiting** [ruanyf/weekly#1802]
## 官网

https://keptab.com  暂时没有中文版，请见谅

## 下载地址

- Chrome 浏览器： [前往 Chrome Webstore 安装](https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi)
- Microsoft Edge 浏览器：[前往 Microsoft Edge Addons 安装](https://microsoftedge.microsoft.com/addons/detail/keptab/jhajaihldpgefhccepbjdpiimikplhng)
- Firefox 浏览器，正在兼容适配，稍后将会更新到 Firefox Addons

## 产品简介

Keptab 是个轻量、功能强大、浑身黑科技、数据能可靠保存的浏览器标签页管理工具，只需一次点击，即可将您所有标签页转换成一个列表保存起来。当您需要再次访问这些标签页时，可以单独或全部恢复它们。

Keptab 的功能与 **OenTab** 类似，但是比 **OenTab** 功能更强大、反应更迅速、更不容易丢失数据

使用 Keptab 可以随时保存浏览器的标签页为列表，方便你的下次使用，你可以将 Keptab 当作是浏览器的待办/待阅读清单

- 几乎是全球唯一采用 IndexedDB 作为数据存储的底层实现的浏览器标签页管理工具
    - 几乎不会再丢失保存的列表数据
    - 在测试中保存超过 30,000 的标签页组，依然加载神速

- 很简单的 ReactDOM 的实现，页面渲染飞快飞快 
    - 肉眼可见极速的页面渲染速度

- 充满黑科技的实时搜索
    - 实时显示你的搜索结果，无论你搜索的是什么
    - 在保存了超过 30,000 的标签页组，依然能够实时显示搜索结果
    - 真实时搜索，童叟无欺

- 讨好眼睛的明亮/黑暗模式，并支持随浏览器自动更换
    - 照顾好你的眼睛是我们努力的目标

## 产品截图

![keptab-intro-chrome-webstore](https://user-images.githubusercontent.com/532871/122143498-2b285300-ce84-11eb-844f-1caee4a2b2be.png)

## 自荐留言

因为是 Chrome 浏览器的重度使用者，每天打开的无数的标签页和浏览器窗口，所以我重度依赖 OneTab 插件的一键收起并所有标签页的实现。然而 OneTab 已经好久不更新了（18年到现在），缺少我翘首以待的插件内搜索标签页的功能。在多次浏览器奔溃时丢失我保存的标签页数据后，我痛定思痛，自己折腾了一个类似 OneTab 的全新插件。

在近一年多的使用中，我使用 Keptab 插件保存超过 20,000+ 的标签页组，未发现有奔溃丢失数据的现象，这在 OneTab 中是不可想象的事情

实在地说，作为自荐工具，我确实带着推广产品的私心而来。但换个角度来说，我也确实希望我开发的这个插件，可以拯救（有点过分严重的用词）各大 OneTab 使用者于水深火热之中

趁还有用爱发电的热情，尽管做不了太大的事情，但还是希望能做点实在的小事情，让这个世界更加美好一点。共勉！

**Comment by hawk0344** [comment]
google商店下架了

**Comment by amitbha** [comment]
能否导入 onetab 数据？
如何备份？可以导出文件，还是可以使用火狐同步？

**Comment by mywaiting** [comment]
> google商店下架了

由于 Chrome Webstore 的政策调整（不能引用多余的权限）和需要 manifest v3，所以暂时被下架了

最近重写了整个 Keptab 的实现，准备重新上架

**Comment by mywaiting** [comment]
> 能否导入 onetab 数据？ 如何备份？可以导出文件，还是可以使用火狐同步？

1. 可以导入 OneTab 数据，不过需要转换一下，可以参考 [Migrate to Keptab](https://keptab.com/migrate)
2. 可以导出 JSON 文件备份
3. 目前还没有上架 Firefox Addons 最近重写完打算上架，但是应该不会使用到 Firefox Sync 原因很简单，FF Sync 同步不支持数据量过大的同步，没法用

**Comment by Gy-Hu** [comment]
你好，如何一次性删除keptab里面所有标签页？
