### ISSUE TITLE
【好玩代码】极简版 codepen

### ISSUE THREAD

**Issue by daGaiGuanYu** [ruanyf/weekly#1809]
[试一下](https://dagaiguanyu.github.io/showcode/index.html?html=%3Ch1%3Ehello%3C/h1%3E&css=/*%20%u8FD9%u91CC%u5199%20css%20%u4EE3%u7801%20*/%0Ah1%20%7B%0A%20%20color%3A%20red%3B%0A%7D&js=console.log%28%27%u8FD9%u91CC%u5199%20js%20%u4EE3%u7801%27%29&oHtml=1&oCss=1&oJs=1)

+ 轻量级，代码不到 300 行
+ 没有后端（只有 github page），但支持分享代码，思路清奇

功能当然没有 codepen 强大，但由于轻，访问速度有保证，而且可以**非常轻松地**“部署”自己的“服务”  
（不支持 ts、sass、stylus 等需要编译的语言，未提供 vue、react 等开发环境）

**Comment by 0x219** [comment]
？

**Comment by daGaiGuanYu** [comment]
> ？

怎么了铁子？

**Comment by 0x219** [comment]
> > ？
> 
> 怎么了铁子？

从哪里看到链接

**Comment by daGaiGuanYu** [comment]
> > > ？
> > 
> > 
> > 怎么了铁子？
> 
> 从哪里看到链接

好尴尬，忘记放链接了，已经更新了，谢谢提醒

**Comment by jwenjian** [comment]
url 的长度有限啊

**Comment by daGaiGuanYu** [comment]
> url 的长度有限啊

我的想法是，用来分享“不是特别长的“代码  
很长的代码，codepen 是支持的，但感觉不实用  
直接在 github 上建个仓库好一点  

另外，虽然我的想法是“较短”，但实际上 chrome 支持 8k 字符长度的 url（firefox 更长）  
我这个程序，源代码（html + css + js）总共 210 行，五千多字符，我觉得已经不算”短的代码了“  
但依然可以使用 [showcode](https://dagaiguanyu.github.io/showcode/index.html?html=%3Ch1%3Ehello%3C/h1%3E&css=/*%20%u8FD9%u91CC%u5199%20css%20%u4EE3%u7801%20*/%0Ah1%20%7B%0A%20%20color%3A%20red%3B%0A%7D&js=console.log%28%27%u8FD9%u91CC%u5199%20js%20%u4EE3%u7801%27%29&oHtml=1&oCss=1&oJs=1) 来分享

再另外，后续会考虑添加”字符串压缩“特性  
但是，它肯定需要引入依赖，会变得不那么轻  
而且也是一个“不实用”的特性  

或者，添加“引入依赖”（比如 jq、vue、react）的特性  
相较而言，这个比较实用

总之，感谢提醒

**Comment by jaywcjlove** [comment]
@daGaiGuanYu 来个新玩儿法 https://uiwjs.github.io/react-code-preview/ 

![image](https://user-images.githubusercontent.com/1680273/122880323-78b52c00-d36c-11eb-9c0d-7c7ebb5498e4.png)

使用示例：https://uiwjs.github.io/react-split/

**Comment by daGaiGuanYu** [comment]
@jaywcjlove 这个有点重……  
我给自己设了个限制，所有源代码的量，可以使用 [showcode](https://dagaiguanyu.github.io/showcode/index.html?html=%3Ch1%3Ehello%3C/h1%3E&css=/*%20%u8FD9%u91CC%u5199%20css%20%u4EE3%u7801%20*/%0Ah1%20%7B%0A%20%20color%3A%20red%3B%0A%7D&js=console.log%28%27%u8FD9%u91CC%u5199%20js%20%u4EE3%u7801%27%29&oHtml=1&oCss=1&oJs=1) 分享
