### ISSUE TITLE
【自荐】插件驱动的所见即所得的Markdown编辑器 - Milkdown

### ISSUE THREAD

**Issue by Saul-Mirone** [ruanyf/weekly#1827]
仓库: [milkdown](https://github.com/Saul-Mirone/milkdown)
文档: [milkdown doc](https://saul-mirone.github.io/milkdown/)
在线体验: [milkdown online](https://saul-mirone.github.io/milkdown/#/online-demo)

Milkdown是一个所见即所得的Markdown编辑器，基于[prosemirror](https://prosemirror.net/)和[remark](https://github.com/remarkjs/remark)构建，完全开源，可以运行在浏览器和electron中。

不同于其它Markdown编辑器，Milkdown是插件驱动的，因此用户可以根据自己的需要定制编辑器的能力，例如扩展特有的markdown语法，渲染特殊节点，定制主题。

**Comment by wangjw219** [comment]
试用了一下感觉还不错

**Comment by Saul-Mirone** [comment]
@ruanyf 请问这个不能入选的理由是什么呢？

**Comment by puzzle9** [comment]
这个 输入 / 后出现的感觉好熟悉 我记得这个有个网站专门做这个的 然后国内也有个类似的 我想问下这个叫啥 @Saul-Mirone 

不过这个文档页面和编辑器是真的好看
可是我想了想 这个适用于自己做的项目 对其他项目而言估计产品经历过不了

**Comment by Saul-Mirone** [comment]
@puzzle9 您说的可能是notion？

其实样式都是可以自定义和覆盖的，官网用的也只是一个主题，用户完全可以根据自己的需要来编写主题和样式的。

**Comment by ruanyf** [comment]
> @ruanyf 请问这个不能入选的理由是什么呢？

不要在意这个啦，不管周刊发不发，都不代表对项目的评价。

只是考虑到大多数读者不一定对这个感兴趣，Markdown 编辑器已经有很多，而这个项目的区别度又不大。插件结构的上手成本高，文档需要加强。

**Comment by Saul-Mirone** [comment]
> 
> 
> > @ruanyf 请问这个不能入选的理由是什么呢？
> 
> 不要在意这个啦，不管周刊发不发，都不代表对项目的评价。
> 
> 只是考虑到大多数读者不一定对这个感兴趣，Markdown 编辑器已经有很多，而这个项目的区别度又不大。插件结构的上手成本高，文档需要加强。

好的，谢谢您的回复，现在的文档应该比我投稿时增加了许多，也支持了中文。
