### ISSUE TITLE
【纠正】“本田电动平衡车”是概念设计，并没有推出

### ISSUE THREAD

**Issue by xuhangtong** [ruanyf/weekly#1894]
“电动平衡车 Honda Baiku”是设计师（非本田公司）nacho alfonso 设计的[概念车](https://fadmagazine.com/2021/08/09/honda-baiku-is-a-futuristic-vehicle-concept/)。

网上并没有找到 “本田推出电动平衡车” 的信息。

请核实。

**Comment by ruanyf** [comment]
谢谢指出，已经加了说明。
