### ISSUE TITLE
【工具】一个支持多语言扩展的JS版开源词法分析器

### ISSUE THREAD

**Issue by WGrape** [ruanyf/weekly#1925]
- 项目地址：https://github.com/WGrape/lexer
- 类别：JS
- 项目描述 ：一个基于DFA法的支持多语言扩展的JS版开源词法分析器
- 适用场景
  - 代码编辑器（关键字高亮、符号高亮等）
  - 为需要语法分析的场景提供Token支持
  - 代码精简、详细的源码分析文档、另附有Web演示界面，适合学习与应用

**Comment by chemsky** [comment]
good job
