### ISSUE TITLE
[自荐文章]Intl.NumberFormat数字格式化应用

### ISSUE THREAD

**Issue by 232650413** [ruanyf/weekly#1936]
Web前端开发过程中常会对后端传递过来的数值类型的对象进行格式化处理，以便用户更好的阅读。例如：数据统计里的数值、货币、百分比、角度、字节、面积、质量、温度、长度、容量及一些符合单位等数据类型进行处理转换。所以下面看看关于Intl.NumberFormat对象对这些数值如何处理。
http://www.deathghost.cn/article/javascript/92

**Comment by ruanyf** [comment]
与 #1676 重复，请不要重复提交自己的文章。

如果再次发生，将被禁止在这里发言。
