### ISSUE TITLE
勘误（手动Reopen）

### ISSUE THREAD

**Issue by lonble** [ruanyf/weekly#1994]
根据维基百科：<https://en.wikipedia.org/wiki/C17_(C_standard_revision)>

> C17 is the informal name for ISO/IEC 9899:2018, the most recent standard for the C programming language, prepared in 2017 and published in June 2018. It replaced C11 (standard ISO/IEC 9899:2011). C17 will be superseded by C2x.

C17原本准备在2017年发布，实际是在2018年才完成并发布，C17也经常写成C18.

---

根据维基百科：<https://en.wikipedia.org/wiki/Text-based_user_interface>

> ***Not to be confused with Command-line interface.***
> 
> *In computing, ****text-based user interfaces (TUI)**** (alternately ****terminal user interfaces****, to reflect a dependence upon the properties of computer terminals and not just text)*, is a retronym describing a type of user interface (UI) common as an early form of human–computer interaction, before the advent of graphical user interfaces (GUIs). Like GUIs, they may use the entire screen area and accept mouse and other inputs. They may also use color and often structure the display using special graphical characters such as ┌ and ╣, referred to in Unicode as the "box drawing" set. The modern context of use is usually a terminal emulator.

CLI和TUI虽然都是基于文本和终端，但交互方式完全不同。
像**cp**，**rm**这些都属于CLI，而**vim**，**less**则是典型的TUI。

---

关闭Issue前麻烦做一些查证，不要想当然。

**Comment by lonble** [comment]
能否简述一下所谓的“管理方式”，以及您从哪里得出“我不尊重它”的结论。再以及，我花费精力找来可以查证的资料，你看都不看就直接关Issue，就很尊重贡献者了吗。

“本杂志开源”，既然您见不得不同意见的人，那么多说无益，祝你安康。

**Comment by puzzle9** [comment]
插眼
我第一次看到标题的时候 我以为重复了
后来再看到回复 我确实没看懂
