### ISSUE TITLE
自荐项目：SimpleKernel

### ISSUE THREAD

**Issue by MRNIU** [ruanyf/weekly#204]
## 项目推荐
- 项目名称：
SimpleKernel
- 项目地址：
https://github.com/MRNIU/SimpleKernel
- 项目描述：
用于学习操作系统内核的项目。
这里有实现一个内核过程中，各个阶段的源码，你可以从自己感兴趣的地方开始。
目前已经完成了启动、gdt、idt 的初始化，系统中断（isr）以及键盘输入。

项目中需要了解的知识我会整理成文档放到一块，免去了到处找资料的麻烦，参考项目我也有列出，你可以对比不同内核的实现思路有什么不一样。

**Comment by ruanyf** [comment]
收入第 43 期。
