### ISSUE TITLE
[资源自荐] 一个专注开源题材的视频专栏

### ISSUE THREAD

**Issue by Yuyz0112** [ruanyf/weekly#2069]
专栏名称：《Koala 聊开源》
B 站链接：https://space.bilibili.com/489667127

特色：
---
这个视频专栏是在我妈妈退休之后开始合作尝试制作的，内容以开源为核心，展开社区故事、商业化分析、历史回顾等多方面的内容。

通过做视频这个活动，帮助没有编程背景的长辈发现了有趣的新世界，也丰富了她的退休生活。从视频反馈来看也有了一小批观众从中收获到了乐趣～

**Comment by erdong-fe** [comment]
真是丰富多彩的退休生活啊

**Comment by nshen** [comment]
妈妈。。。
