### ISSUE TITLE
【画图工具】plectica 一个可以共享画布的画图工具

### ISSUE THREAD

**Issue by xcuYao** [ruanyf/weekly#2086]
[plectica](https://www.plectica.com/)  可共同编辑的思维图绘制工具
> Diagram your thinking in real time, together.
For strategists, educators, technologists, designers, policy makers, and thinkers of all sorts!

下边是一些[例子](https://www.plectica.com/examples)：
<a href="https://www.plectica.com/maps/LZ9NEEUXC" target="_blank"><img src="https://plectica-thumbnails.s3.amazonaws.com/map/7JTEN2SCM/preview/CBEhluk-2gtHiQRfxeOSRFI1VnwK2PNhLi6ajqBYibo.jpg" alt="drawing" width="200"/></a>
<a href="https://www.plectica.com/maps/41T801CIV" target="_blank"><img src="https://plectica-thumbnails.s3.amazonaws.com/map/41T801CIV/preview/2jrFLaOPRgMrnG1ofuZL8mLigZt8LvNXf86C7UaeTmc.jpg" alt="drawing" width="200"/></a>
<a href="https://www.plectica.com/maps/ZOV7OZF0C" target="_blank"><img src="https://plectica-thumbnails.s3.amazonaws.com/map/ZOV7OZF0C/thumbnail/6O3RfMbGec3nb7rVlgbSRihfQ9lZxW6YCnlr9rk3YQ0.jpg" alt="drawing" width="200"/></a>
<a href="https://www.plectica.com/maps/4WHNL7DK0" target="_blank"><img src="https://plectica-thumbnails.s3.amazonaws.com/map/4WHNL7DK0/preview/tz2p7_cywzp9A68HttUph0pfIjdAH3VJlwlDAsRIn18.jpg" alt="drawing" width="200"/></a>

**Comment by longmore** [comment]
已经收到您的邮件。谢谢！

**Comment by LinQMo** [comment]
您的邮件我已经收到，我会尽快给您答复。
