### ISSUE TITLE
【自荐项目】性教育科普网站：知性 KnowSex.net

### ISSUE THREAD

**Issue by knowsex** [ruanyf/weekly#2111]
**项目名称**：知性 KnowSex
**网站首页**：[KnowSex.net](https://knowsex.net)
**仓库地址**：https://github.com/knowsex/knowsex.github.io
**简介**：知性（KnowSex）是一个性教育网站，为中学生及以上群体年龄段提供性教育知识科普。

**Comment by puzzle9** [comment]
怎么说呢 个人觉得这个需要很大的勇气去访问

**Comment by knowsex** [comment]
> 怎么说呢 个人觉得这个需要很大的勇气去访问 尤其是其中的配图

暴露的图片页面放过一层模糊，只要是现代的浏览器进行访问 ; )

**Comment by Jaya0455** [comment]
在向青少年传授性卫生知识时，男女同学要一道听，不要分开……
不要试图回避，更不要搞得神秘化。
---周恩来👍

**Comment by sunfjun** [comment]
> **项目名称**：知性 KnowSex **网站首页**：[KnowSex.net](https://knowsex.net) **仓库地址**：https://github.com/knowsex/knowsex.github.io **简介**：知性（KnowSex）是一个性教育网站，为中学生及以上群体年龄段提供性教育知识科普。

网站需要备案么？

**Comment by knowsex** [comment]
> 网站需要备案么？

备案还在筹备中~

**Comment by justhyj** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
焊仙钒慕刃
