### ISSUE TITLE
京东云-流量接入运维工程师招聘（急招）

### ISSUE THREAD

**Issue by wanglp825** [ruanyf/weekly#2115]
**### 京东云介绍：**
      https://www.jdcloud.com/cn/brand

招聘岗位：
**【流量接入运维工程师招聘（急招）】**

- 月薪酬 20K-50K * 15薪
- 职位亮点：年终奖金×五险一金×餐费补贴×岗位晋升×带薪年假×定期体检
- 学历要求：本科及以上
- 工作地点：北京 海淀区 知春路 京东科技大厦（原翠宫大厦）
- 职位描述

1. 管理就京东全集团业务域名，规划建设稳定可靠高效的全球DNS域名系统.负责DNS架构设计优化、域名系统的稳定可靠运行和持续优化。
2. 负责京东全站4、7层负载均衡系统架构设计与集群维护,包括升级更新、数据制作、日常监控等。
3. 对接入负载均衡的业务进行数据分析与优化调整。
4. 参与运维自动化建设中的流程优化、功能设计及相关开发。
5. 负责运维中的应急响应及容灾工作。
任职资格
1. 具备两年以上负载均衡建设运维经验，精通 Nginx、HAproxy、LVS、Keepalived 等开源L4+L7层架构部署，并深入理解其中各组件工作原理与参数配置。
2. 熟悉HTTP、HTTPS、HTTP/2等通讯协议，了解TLS/SSL加方式。
3. 具备DNS集群运维管理经验，了解anycast、智能DNS和HTTPDNS的工作原理。
4. 熟练掌握Linux系统管理、性能调优，c/shell/python/golang/php/perl等至少1种语言，有运维工具开发能力。
5. 优先考虑有k8s经验者。
6. 责任心强、认真细致，具有良好的协作与沟通能力。
7. 扎实的运维基本功，在监控、部署、架构规划、可用性保障方面有体系化的经验。
8. 优秀的分析问题和解决问题的能力，热衷于解决问题、追求极致。
9. 逻辑思维清晰，有良好的自驱力和上进心，有良好的团队合作精神。

感兴趣的话，可以投递简历至 wanglipeng@jd.com

**Comment by lizj3624** [comment]
👍
