### ISSUE TITLE
[工具推荐] 科学爱好者周刊 RSS 订阅推送

### ISSUE THREAD

**Issue by ronething** [ruanyf/weekly#2132]
### 工具地址

https://github.com/ronething/ifttt

### 工具描述

 科学爱好者周刊订阅推送(基于 [actionsflow](https://github.com/actionsflow/actionsflow)) ，目前支持推送到企业微信/Slack

很喜欢阮老师的科学爱好者周刊，不过貌似没有专门的 RSS 源，
发现阮老师每次周五发布都有打 tag，所以考虑结合 github 本身 rss 订阅推送，
详见 [rss.yaml](https://github.com/ronething/ifttt/blob/main/workflows/rss.yml)

- 使用

理论上 fork 并补充相关 secrets 即可 `${{ secrets.WECOM_URL }}` `${{ secrets.SLACK_URL }}`

### 效果

![image](https://user-images.githubusercontent.com/28869910/147446083-15b4eddb-7faa-40fa-a0c5-2a6b715e6923.png)

### 推荐理由

**主要是发现阮老师上周 189 期的 tag 貌似没打**，导致推送没有发送出来(逃，还望阮老师可以继续打下 tag 感恩🙇‍

![image](https://user-images.githubusercontent.com/28869910/147446446-a29e63f8-671a-400b-9a29-87153627a6ca.png)

**Comment by ruanyf** [comment]
tag 目前是手动打的，有时会忘记。

周刊的全文 Feed，可以考虑我个人网站的 Feed。

**Comment by EastLord** [comment]
@ronething 有RSS源  https://feeds.feedburner.com/ruanyifeng
