### ISSUE TITLE
【文章推荐】2022 年了，如何跟政府打交道

### ISSUE THREAD

**Issue by greensea** [ruanyf/weekly#2170]
https://www.jianda.com/p/75

介绍了行政复议、信息公开和听证会的知识。关于行政复议的介绍特别实用，很多人不知道行政复议的流程，常常被贴了罚单了也不知道怎样申诉。

**Comment by jingkaimori** [comment]
文章404了

**Comment by claviering** [comment]
> 文章404了

没有404，等一会就加载出来了，它那个系统的问题

**Comment by greensea** [comment]
如楼上所说，404 是误报，等一下文章就出来了。网站已经在修这个 404 的问题了，不过估计也要春节后才修好

**Comment by nshen** [comment]
楼主懂法还被忽悠这么多次。俺们这种法盲，行政复议肯定没戏。

**Comment by claviering** [comment]
> 楼主懂法还被忽悠这么多次。俺们这种法盲，行政复议肯定没戏。

淦

**Comment by lc-stevenzhang** [comment]
我看到门口的两个限宽柱被强拆，之后就看不动了，好长啊。
如果只是把经验写出来都这么长，那实际中行使这项权利的成本会有多大？
不过也正是作者这样一个个的人去一点一点的推（这条路），各方面才会重视并更加配合吧。
致敬，只不过从成本的程度考虑，一般人即使知道有这条路，也很难去选的。
