### ISSUE TITLE
[节目自荐]国内前端中文音频播客 Web Worker

### ISSUE THREAD

**Issue by Otto-J** [ruanyf/weekly#2228]
[《Web Worker播客》](https://www.xiaoyuzhoufm.com/podcast/613753ef23c82a9a1ccfdf35) 节目历经半年已经做到了第九期，这是一档两个前端程序员闲聊的音频播客节目。节目围绕程序员领域来瞎聊，聊资讯、聊职场、聊技术选型...... 只要是和 web 开发有关的都可以聊。因为两个主播是前端程序员，目前会以前端为视角来切入。

如果新听众同样是是程序员，尤其推荐 [《No.4 邀请到了HR做嘉宾！我要求面试涨薪》]( https://www.xiaoyuzhoufm.com/episodes/6190c0ba03abe84b7f8b8f7a)，这一期邀请到了资深 HR 一起聊了感兴趣的话题。

链接：
https://www.xiaoyuzhoufm.com/podcast/613753ef23c82a9a1ccfdf35
图片logo

![logo-1000](https://user-images.githubusercontent.com/9958583/155869846-ffb21a84-489c-4699-be99-a142ade5fd89.jpg)

**Comment by jiacai2050** [comment]
没有 RSS ？

**Comment by kang8** [comment]
> 没有 RSS ？

小宇宙没有 RSS。可以使用喜马拉雅的 RSS：https://www.ximalaya.com/album/53240139.xml

**Comment by Otto-J** [comment]
补充一下：目前可以在小宇宙 苹果播客 喜马拉雅 网易云音乐收听订阅，刚才也提供了 RSS 订阅链接

**Comment by xingorg1** [comment]
🎉

**Comment by Otto-J** [comment]
已发布，归档此 issues
