### ISSUE TITLE
【项目推荐】解放双手 ! 用语音写代码 Speech To Code

### ISSUE THREAD

**Issue by ooohmydawn** [ruanyf/weekly#2288]
它可以连接到你最喜欢的 IDE 并向其发出命令来实现使用语言编码

![网站截图01](https://user-images.githubusercontent.com/45456105/159865243-cb2586d3-b2d7-4cca-9db9-0b838f4cdea9.png)

你可以通过这个 [Demo](https://pedrooaugusto.github.io/speech-to-code/webapp) 来快速了解这个项目, 从最经典的 `Hello World` 开始, 到真正解决编码问题. 

该项目已在 Github 开源 : [speech-to-code](https://github.com/pedrooaugusto/speech-to-code)

**Comment by amitbha** [comment]
PC 上有没有语音输入法？
