### ISSUE TITLE
201期周刊图片问题

### ISSUE THREAD

**Issue by Mr54233** [ruanyf/weekly#2314]
![image](https://user-images.githubusercontent.com/46802509/161188243-ef02d9a9-fcdf-4499-aff9-e810beea8380.png)
问题图片均指向https://camo.githubusercontent.com/96d926290def0a92646b0db1ed3dc7acd9d3e27309a287f836ca2986b67d3415/68747470733a2f2f63646e2e6265656b6b612e636f6d2f626c6f67696d672f61737365742f3230323230322f6267323032323032303130362e77656270

**Comment by ruanyf** [comment]
刷新网页。
