### ISSUE TITLE
资源类:  中国科学技术大学课程资源

### ISSUE THREAD

**Issue by mbinary** [ruanyf/weekly#232]
# 项目地址: https://github.com/mbinary/USTC-CS-Courses-Resource
# 介绍
这是一个收集 中国科学技术大学课程资源的（主要是计算机学院的, 也有其他课程, 公选课, 自由选修等）的 repo, 包括课程电子版 书籍，参考书，slides(ppt), 考试试卷，学习心得，某些书的答案。

# 课程目录

**根据拼音字母排序**

*   [.](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master)
    *   [docs](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs)
        *   [工具类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E5%B7%A5%E5%85%B7%E7%B1%BB)
        *   [经管类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E7%BB%8F%E7%AE%A1%E7%B1%BB)
        *   [计算机与信息类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB)
        *   [人文社科类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E4%BA%BA%E6%96%87%E7%A4%BE%E7%A7%91%E7%B1%BB)
        *   [书籍推荐](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E4%B9%A6%E7%B1%8D%E6%8E%A8%E8%8D%90)
        *   [数学类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E6%95%B0%E5%AD%A6%E7%B1%BB)
        *   [网盘资源](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E7%BD%91%E7%9B%98%E8%B5%84%E6%BA%90)
        *   [物理类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/docs/%E7%89%A9%E7%90%86%E7%B1%BB)
    *   [工具类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E5%B7%A5%E5%85%B7%E7%B1%BB)
    *   [经管类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB)
        *   [宏观经济学](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB/%E5%AE%8F%E8%A7%82%E7%BB%8F%E6%B5%8E%E5%AD%A6)
        *   [会计学原理](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB/%E4%BC%9A%E8%AE%A1%E5%AD%A6%E5%8E%9F%E7%90%86)
        *   [生产与运作管理](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB/%E7%94%9F%E4%BA%A7%E4%B8%8E%E8%BF%90%E4%BD%9C%E7%AE%A1%E7%90%86)
        *   [市场营销](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB/%E5%B8%82%E5%9C%BA%E8%90%A5%E9%94%80)
        *   [微观经济学](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BB%8F%E7%AE%A1%E7%B1%BB/%E5%BE%AE%E8%A7%82%E7%BB%8F%E6%B5%8E%E5%AD%A6)
    *   [计算机与信息类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB)
        *   [编译原理和技术](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86%E5%92%8C%E6%8A%80%E6%9C%AF)
        *   [并行计算](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E5%B9%B6%E8%A1%8C%E8%AE%A1%E7%AE%97)
        *   [block-chain](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/block-chain)
        *   [c&c++](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/c&c++)
        *   [操作系统原理与设计](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8E%9F%E7%90%86%E4%B8%8E%E8%AE%BE%E8%AE%A1)
        *   [操作系统原理与设计 (H)](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8E%9F%E7%90%86%E4%B8%8E%E8%AE%BE%E8%AE%A1(H))
        *   [程序设计语言基础 (英)](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E8%AF%AD%E8%A8%80%E5%9F%BA%E7%A1%80(%E8%8B%B1))
        *   [common_lisp](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/common_lisp)
        *   [go](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/go)
        *   [haskell](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/haskell)
        *   [java&kotlin&scala](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/java&kotlin&scala)
        *   [计算机体系结构](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84)
        *   [计算机网络](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C)
        *   [计算机系统概论 (ICS)](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E6%A6%82%E8%AE%BA(ICS))
        *   [计算机系统详解 (csapp)](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E8%AF%A6%E8%A7%A3(csapp))
        *   [计算机组成原理](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BB%84%E6%88%90%E5%8E%9F%E7%90%86)
        *   [julia](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/julia)
        *   [密码学](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E5%AF%86%E7%A0%81%E5%AD%A6)
        *   [模拟与数字电路](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%A8%A1%E6%8B%9F%E4%B8%8E%E6%95%B0%E5%AD%97%E7%94%B5%E8%B7%AF)
        *   [python](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/python)
        *   [scheme](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/scheme)
        *   [数电实验](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%95%B0%E7%94%B5%E5%AE%9E%E9%AA%8C)
        *   [数据结构](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84)
        *   [数据科学导论](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%95%B0%E6%8D%AE%E7%A7%91%E5%AD%A6%E5%AF%BC%E8%AE%BA)
        *   [数据库系统及应用](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F%E5%8F%8A%E5%BA%94%E7%94%A8)
        *   [数理逻辑](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E6%95%B0%E7%90%86%E9%80%BB%E8%BE%91)
        *   [算法基础](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80)
        *   [图论](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E5%9B%BE%E8%AE%BA)
        *   [Type_Theory](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/Type_Theory)
        *   [网络安全基础及应用](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E7%BD%91%E7%BB%9C%E5%AE%89%E5%85%A8%E5%9F%BA%E7%A1%80%E5%8F%8A%E5%BA%94%E7%94%A8)
        *   [Web - 信息处理与应用](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/Web-%E4%BF%A1%E6%81%AF%E5%A4%84%E7%90%86%E4%B8%8E%E5%BA%94%E7%94%A8)
        *   [微机原理与系统](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E5%BE%AE%E6%9C%BA%E5%8E%9F%E7%90%86%E4%B8%8E%E7%B3%BB%E7%BB%9F)
        *   [物联网导论](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%8E%E4%BF%A1%E6%81%AF%E7%B1%BB/%E7%89%A9%E8%81%94%E7%BD%91%E5%AF%BC%E8%AE%BA)
    *   [其他](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E5%85%B6%E4%BB%96)
    *   [人文社科类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E4%BA%BA%E6%96%87%E7%A4%BE%E7%A7%91%E7%B1%BB)
        *   [交响乐赏析](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E4%BA%BA%E6%96%87%E7%A4%BE%E7%A7%91%E7%B1%BB/%E4%BA%A4%E5%93%8D%E4%B9%90%E8%B5%8F%E6%9E%90)
        *   [技术, 财富与文明变迁](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E4%BA%BA%E6%96%87%E7%A4%BE%E7%A7%91%E7%B1%BB/%E6%8A%80%E6%9C%AF,%E8%B4%A2%E5%AF%8C%E4%B8%8E%E6%96%87%E6%98%8E%E5%8F%98%E8%BF%81)
        *   [重要思想概论](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E4%BA%BA%E6%96%87%E7%A4%BE%E7%A7%91%E7%B1%BB/%E9%87%8D%E8%A6%81%E6%80%9D%E6%83%B3%E6%A6%82%E8%AE%BA)
    *   [数学类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB)
        *   [代数结构](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E4%BB%A3%E6%95%B0%E7%BB%93%E6%9E%84)
        *   [多变量微积分](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E5%A4%9A%E5%8F%98%E9%87%8F%E5%BE%AE%E7%A7%AF%E5%88%86)
        *   [概率论与数理统计 B](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E6%A6%82%E7%8E%87%E8%AE%BA%E4%B8%8E%E6%95%B0%E7%90%86%E7%BB%9F%E8%AE%A1B)
        *   [计算方法](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E8%AE%A1%E7%AE%97%E6%96%B9%E6%B3%95)
        *   [数理方程](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E6%95%B0%E7%90%86%E6%96%B9%E7%A8%8B)
        *   [随机过程](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E9%9A%8F%E6%9C%BA%E8%BF%87%E7%A8%8B)
        *   [线性代数 B1](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0B1)
        *   [运筹学基础](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E6%95%B0%E5%AD%A6%E7%B1%BB/%E8%BF%90%E7%AD%B9%E5%AD%A6%E5%9F%BA%E7%A1%80)
    *   [utils](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/utils)
    *   [网盘资源](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%BD%91%E7%9B%98%E8%B5%84%E6%BA%90)
    *   [物理类](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%89%A9%E7%90%86%E7%B1%BB)
        *   [电磁学](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%89%A9%E7%90%86%E7%B1%BB/%E7%94%B5%E7%A3%81%E5%AD%A6)
        *   [光学与原子物理](https://github.com/mbinary/USTC-CS-Courses-Resource/blob/master/%E7%89%A9%E7%90%86%E7%B1%BB/%E5%85%89%E5%AD%A6%E4%B8%8E%E5%8E%9F%E5%AD%90%E7%89%A9%E7%90%86)

**Comment by ruanyf** [comment]
收入第 44 期。
