### ISSUE TITLE
【开源项目】抗疫从容锦囊

### ISSUE THREAD

**Issue by jiezhao9** [ruanyf/weekly#2332]
收录各类抗疫过程中的攻略，让更多人更从容，直接复用最佳实践 。包括囤货指南、核酸检测方案设计、团购组织等。
https://www.yuque.com/jiezhao/congrong/readme

**Comment by ruanyf** [comment]
不要张贴跟科技无关的内容。

**Comment by jiezhao9** [comment]
> 不要张贴跟科技无关的内容。

用科技的方式 去更好地抗疫吧。比如如何设计核算检测方案，如何用科技项目推进的方式（OKR）来做团购。 

 里面已经剔除了 zz 相关的内容了。
