### ISSUE TITLE
【自荐】📲cim(cross IM) 适用于开发者的即时通讯系统

### ISSUE THREAD

**Issue by crossoverJie** [ruanyf/weekly#237]
项目名称：`cim`
项目地址：https://github.com/crossoverJie/cim

### 介绍

`CIM(CROSS-IM)` 一款面向开发者的 `IM(即时通讯)`系统；同时提供了一些组件帮助开发者构建一款属于自己可水平扩展的 `IM` 。

借助 `CIM` 你可以实现以下需求：

- `IM` 即时通讯系统。
- 适用于 `APP` 的消息推送中间件。
- `IOT` 海量连接场景中的消息透传中间件。

## 视频演示

| YouTube | Bilibili|
| :------:| :------: | 
| [群聊](https://youtu.be/_9a4lIkQ5_o) [私聊](https://youtu.be/kfEfQFPLBTQ) | [群聊](https://www.bilibili.com/video/av39405501) [私聊](https://www.bilibili.com/video/av39405821) | 
| <img src="https://ws3.sinaimg.cn/large/006tNbRwly1fys8flaofrj315e0ose81.jpg"  height="295px" />  | <img src="https://ws4.sinaimg.cn/large/006tNbRwly1fys8mpa6wij31240lghdt.jpg" height="295px" />

更详细的内容请查看项目[首页](https://github.com/crossoverJie/cim)。

**Comment by ruanyf** [comment]
收入第 44 期。
