### ISSUE TITLE
[开源自荐] 飞鸽传书 校园远程通知平台

### ISSUE THREAD

**Issue by jsun969** [ruanyf/weekly#2395]
能够方便校园内教师向教室电脑发送弹窗消息，达到远程通知的效果

使用Typescript开发
后端Nest 前端React 软件端Tauri+React+Winforms

文档：https://mpigeon.jsun969.cn/
演示视频：https://www.bilibili.com/video/BV1BL4y1c76d
开源仓库：https://github.com/MessagePigeon

**Comment by puzzle9** [comment]
可能 我最终是没想到作用是啥

**Comment by jsun969** [comment]
> 可能 我最终是没想到作用是啥

其实还挺有用的。我之前的一个版本，我们学校已经用了半个学期了，老师都觉得挺好。

**Comment by jsun969** [comment]
## 教师端
![image](https://user-images.githubusercontent.com/29330847/168934047-29a12fcb-8e52-40ed-b060-1e55c1bcc9be.png)
![image](https://user-images.githubusercontent.com/29330847/168934062-3f9a8454-dc11-4da3-aee8-36baa71034b8.png)
![image](https://user-images.githubusercontent.com/29330847/168934076-97fd2d34-30a3-4cd7-938b-85381d699bc2.png)

## 学生端
![image](https://user-images.githubusercontent.com/29330847/168934160-b5a4c404-46bd-4482-9070-7b7716e6ce45.png)
![image](https://user-images.githubusercontent.com/29330847/168934167-f279d275-bad5-4b11-ade7-531325005583.png)

## 管理员端
![image](https://user-images.githubusercontent.com/29330847/168934184-214063f2-5705-4042-bfdd-46fb3f2ed1bb.png)
![image](https://user-images.githubusercontent.com/29330847/168934264-b1d42fc7-6d5d-41da-8505-58c21105e0ef.png)
![image](https://user-images.githubusercontent.com/29330847/168934277-82d913d8-2e16-400c-9c66-f39e00b0d925.png)
