### ISSUE TITLE
到底地球的大部分海域，都将可以上网?

### ISSUE THREAD

**Issue by ljt1018168** [ruanyf/weekly#2505]
由于第一期要通过地面的卫星站中转，所以只有欧美的近海能上网（下图的浅蓝色部分）。
据说，年底可以实现卫星之间的直接通信，到底地球的大部分海域，都将可以上网。

【到时候地球的大部分海域，都将可以上网】?

**Comment by claviering** [comment]
[Starlink](https://www.starlink.com/)
