### ISSUE TITLE
推荐项目: 用Golang开发的交互式命令行(终端)组件库

### ISSUE THREAD

**Issue by fzdwx** [ruanyf/weekly#2555]
## 推荐项目

- 项目地址：https://github.com/fzdwx/infinite

- 类别：Go

- 项目标题：用Golang开发的交互式命令行组件库。

- 项目描述：
它提供了一些常用的交互式组件，比如说`progress`,`progress group`,`mulit select`,`input text`,`confirm`等.同时也提供了一些更基础的组件，方便用户进行组合使用。

- 亮点：
易于使用，定制化能力强，线程安全。

- 示例代码
这个 一个`multi select`的代码案例
```go
package main

import (
	inf "github.com/fzdwx/infinite"
	"github.com/fzdwx/infinite/color"
	"github.com/fzdwx/infinite/components"
	"github.com/fzdwx/infinite/components/selection/multiselect"
	"github.com/fzdwx/infinite/style"
)

func main() {
	input := components.NewInput()
	input.Prompt = "Filtering: "
	input.PromptStyle = style.New().Bold().Italic().Fg(color.LightBlue)

	_, _ = inf.NewMultiSelect([]string{
		"Buy carrots",
		"Buy celery",
		"Buy kohlrabi",
		"Buy computer",
		"Buy something",
		"Buy car",
		"Buy subway",
	},
		multiselect.WithHintSymbol("x"),
		multiselect.WithUnHintSymbol("√"),
		multiselect.WithFilterInput(input),
	).Display("select your items!")
}
```
- 截图：

autocomplete:
![demo](https://user-images.githubusercontent.com/65269574/183641765-e8de7441-3c4e-4008-b2a9-b2ba556ddd72.gif)

multi select
![image](https://user-images.githubusercontent.com/65269574/183274216-d2a7af91-0581-4d13-b8c2-00b9aad5ef3a.gif)

progress bar
![image](https://user-images.githubusercontent.com/65269574/183296585-b0a56827-d9d9-4258-ad32-266ada01b1ed.gif)

confirm
![image](https://user-images.githubusercontent.com/65269574/183076452-5fa73013-42de-47df-97b4-7be743d074c1.gif)

- 后续更新计划：
1. 目前项目还属于刚起步，需要做的事情很多。 
2. 提供更多的组件。
3. 提供更多的使用案例。
4. 提供组合使用的案例。
5. 增强定制化的能力...

**Comment by gitliufukui** [comment]
目前支持翻页 和 指定显示的行数吗

**Comment by fzdwx** [comment]
> 

选择的那个组件吗？ 不支持

**Comment by fzdwx** [comment]
> 目前支持翻页 和 指定显示的行数吗

翻页不支持

**Comment by gitliufukui** [comment]
NewConfirmWithSelection 多选的组件

**Comment by gitliufukui** [comment]
近期 加入这两个功能的 计划吗

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/216576640-083744b3-e8d9-4812-9301-fc395471dce0.png)
 
这个？

**Comment by gitliufukui** [comment]
> ![image](https://user-images.githubusercontent.com/65269574/216576640-083744b3-e8d9-4812-9301-fc395471dce0.png)
> 
> 这个？
> 
> 这个固定了两个选项呀， true or false

<img width="411" alt="1675420102904" src="https://user-images.githubusercontent.com/49547975/216577169-1aea29c6-17d3-4fc9-a360-b45c69c8e85d.png">
抱歉 ，是这个这个显示的行数 能指定吗

**Comment by gitliufukui** [comment]
> 

目前只显示默认的 5行

**Comment by fzdwx** [comment]
可以 

![image](https://user-images.githubusercontent.com/65269574/216578685-ae742253-2a51-4735-87c9-7232fa0e4415.png)

**Comment by gitliufukui** [comment]
> 可以
> 
> ![image](https://user-images.githubusercontent.com/65269574/216578685-ae742253-2a51-4735-87c9-7232fa0e4415.png)
好的 非常感谢
还有一个 
func NewMultiSelect(choices []string, ops ...multiselect.Option) *multiselect.Select {
	return multiselect.New(choices, ops...)
}
choices []string 有计划更改为 泛型 的吗

**Comment by fzdwx** [comment]
只能改成接口吧

**Comment by gitliufukui** [comment]
> 只能改成接口吧

是的 目前string 太单一了

**Comment by fzdwx** [comment]
> > 可以
> > ![image](https://user-images.githubusercontent.com/65269574/216578685-ae742253-2a51-4735-87c9-7232fa0e4415.png)
> > 好的 非常感谢
> > 还有一个
> > func NewMultiSelect(choices []string, ops ...multiselect.Option) *multiselect.Select {
> > return multiselect.New(choices, ops...)
> > }
> > choices []string 有计划更改为 泛型 的吗

你可以试着改下。。。 我最近在准备找工作，没什么心思搞

**Comment by gitliufukui** [comment]
> > > 可以
> > > ![image](https://user-images.githubusercontent.com/65269574/216578685-ae742253-2a51-4735-87c9-7232fa0e4415.png)
> > > 好的 非常感谢
> > > 还有一个
> > > func NewMultiSelect(choices []string, ops ...multiselect.Option) *multiselect.Select {
> > > return multiselect.New(choices, ops...)
> > > }
> > > choices []string 有计划更改为 泛型 的吗
> 
> 你可以试着改下。。。 我最近在准备找工作，没什么心思搞

好的 加油呀 感谢您的恢复

**Comment by gitliufukui** [comment]
目前咱们有  层级选择的 例子吗   选择a 显示 []string{"test","test2"}  选择b 显示其它

**Comment by fzdwx** [comment]
啥意思？

先一个:

1.咖啡
2.茶

选咖啡出现:
1.加糖
2.加奶

选茶出现:
1.大红袍
2.铁观音

的意思吗？

你可以在代码里面进行判断，然后显示不同的选择项

**Comment by gitliufukui** [comment]
是这个意思的
目前我有平台和租户两个 选项， 我选择 平台之后  同时  显示了平台 和租户
当我选择平台之后 我想只显示租户 不显示平台的信息
![image](https://user-images.githubusercontent.com/49547975/216591281-6ab60ff8-e0fc-4a1e-92b5-7565c7e2c75e.png)

**Comment by fzdwx** [comment]
你就是想第一个的信息选择后，不显示是吧？

**Comment by gitliufukui** [comment]
是的

> 你就是想第一个的信息选择后，不显示是吧？

**Comment by fzdwx** [comment]
> 是的
> 
> > 你就是想第一个的信息选择后，不显示是吧？

`WithDisableOutputResult()` 加这个

**Comment by fzdwx** [comment]
里面有一些 option ，你可以先看看在提问。

**Comment by ruanyf** [comment]
项目的具体问题，请到项目仓库讨论，不要在这里讨论。
