### ISSUE TITLE
【开源自荐】自己用java写的日志框架

### ISSUE THREAD

**Issue by jdklog** [ruanyf/weekly#2597]
https://github.com/jdkstack/jdklog

纯java，无依赖，开发还在进行中，希望朋友们给个星星，感谢软一峰老师，提供平台。

**Comment by Kingson** [comment]
“感谢软一峰老师”->"感谢阮一峰老师"
-------------------------------------------------------------
工作的层次(依靠谱程度从低到高)=有做-＞做完-＞做对-＞做好-＞帮助他人做好
