### ISSUE TITLE
【开源自荐】NESBox 多人联机玩 NES 游戏

### ISSUE THREAD

**Issue by mantou132** [ruanyf/weekly#2600]
项目地址：https://github.com/mantou132/nesbox

它使用 Rust 构建后端，使用 [Gemjs](https://gemjs.org/) 编写的前端，WASM 运行游戏，WebGL 进行联机。有好友邀请和语音的功能。

现在正在做 Flutter 移动/TV 版。

详细介绍：https://juejin.cn/post/7136883410819088397

**Comment by woshixiaoqianbi** [comment]
![image](https://user-images.githubusercontent.com/18699589/189865030-c71036b2-cbe1-4983-80cc-807b5f017641.png)
注册不了吧

**Comment by mantou132** [comment]
@woshixiaoqianbi 这应该是用户名重复了。

你浏览器版本太低了，界面烂了。如果你没有看到“用户名重复”的错误提示，那可能也是这个原因。
