### ISSUE TITLE
【网站自荐】Freehand意绘，中文化AI文生图工具

### ISSUE THREAD

**Issue by TandK8600** [ruanyf/weekly#2678]
# 介绍
### 网址
[Freehand意绘](https://freehand.yunwooo.com)

### 界面截图及生成效果
![界面](https://user-images.githubusercontent.com/64523060/194871479-5d99e248-c710-40bc-be26-449824fb38e4.png)

![太空都市,未来主义2022-10-09_03_44_01](https://user-images.githubusercontent.com/64523060/194871754-fac8df94-8319-4809-aba3-4dc991106604.png)

![image](https://user-images.githubusercontent.com/64523060/194871928-854b0119-8cb2-4fb3-a085-2865d52c8e47.png)

### 内核
内核为开源的AI模型Stable Diffusion。

### 对比内核做了些什么
做了中文化，简化了操作步骤，Stable Diffusion的Dream Studio提供了许多参数，可能更适合专业人员做成非常让人眼前一亮的图。

但是就我自己使用过程，很多参数是有操作门槛的，看说明就要耗费许多时间，这边砍掉了一些参数，只需要做三步：
1. 用一句话描述
2. 选好图片尺寸和风格
3. 点击按钮生成图片

降低使用门槛让选择困难户能更好地体验。

# 关于使用
免费，版权归创作者所有，推荐在文章插图时使用。

我自己也写作，有的时候为了一张插图能找好久，觉得合适的有版权，免费的图片又觉得和文章不太相关，本质上这个工具是为了解决这个问题而生的，文章作者需要的图片大多质量适中即可，只需要用一句话描述场景，而这个又是文章创作者较为擅长的，不需要调试，一句话调试，这个不行再生成，从我个人的写作习惯来看是比较适合写作人士的。

# 致谢
感谢阮老师提供的平台，让这个产品有机会被更多人看到，一个产品是否可行需要用户使用才能得到反馈，也感谢每一个用户的体验，这个产品还在持续迭代，有建议可以随时反馈，十分感谢~

**Comment by liumoze** [comment]
已经不行了？？

**Comment by TandK8600** [comment]
> 已经不行了？？

暂时崩掉了，最近访问有点多。。已修复

**Comment by YanBC** [comment]
我这边访问报了个502😂

**Comment by claviering** [comment]
502

**Comment by McDulll** [comment]
502
