### ISSUE TITLE
【开源自荐】为 Vue 生态打造的 Command Palette （CMD + K）类库

### ISSUE THREAD

**Issue by xiaoluoboding** [ruanyf/weekly#2683]
# Vue Command Palette

Vue 生态一直缺失一款好用的 CMDK 类库，像 React 生态有

* [cmdk](https://github.com/pacocoursey/cmdk) - Fast, unstyled command menu React component.
* [kbar](https://github.com/timc1/kbar) - fast, portable, and extensible cmd+k interface for your site.

Vue Command Palette 是一个为 Vue 而生的快速、无样式、可组合的 CMDK 组件库

## 线上 Demo

https://vue-command-palette.vercel.app/

## 仓库地址

https://github.com/xiaoluoboding/vue-command-palette

## 预览

![vue-command-palette](https://user-images.githubusercontent.com/6118824/195382235-ccee538f-a9fa-4804-9f3e-ba7a570dcf82.gif)

**Comment by penggang-home** [comment]
What is the corresponding key for Windows?

**Comment by xiaoluoboding** [comment]
@penggang-home 

It's up to you, [See doc](https://github.com/xiaoluoboding/vue-command-palette#command--k-or-)
