### ISSUE TITLE
【文章自荐】杜架的技术月刊（202210期）

### ISSUE THREAD

**Issue by TrumanDu** [ruanyf/weekly#2719]
杜架的技术月刊，主要关注计算机领域，记录本月看到的有价值的信息，主要包含：碎片化思考，阅读笔记分享，开源项目（软件）介绍。内容主题可能有极大的个人喜好偏向，努力做个输出的人，爱我所爱，想我所想，写我所写。

[杜架的技术月刊(202210期)](https://mp.weixin.qq.com/s/BIQhqa9A_ZU3d3aiYm_tLw)

**Comment by jtsang4** [comment]
请问有可以订阅的 RSS 源吗

**Comment by xiaowuleyi** [comment]
> 请问有可以订阅的 RSS 源吗

我看了一下这个作者好像只有公众号和语雀的内容，哈哈。现在RSS的太少了，不过建议TrumaDU去竹白上更新一下，支持邮件订阅。

**Comment by TrumanDu** [comment]
@jtsang4 @xiaowuleyi  周末搭建了rss,感谢关注 [TrumanDu RSS](http://blog.trumandu.top/atom.xml)

我尝试在竹白上写过几期，没有坚持下来，主要还是竹白的订阅方式其实没有想象的那么美好

如果你关注的话，地址：[TrumanDu竹白地址](https://trumandu.zhubai.love/)

再次感谢，分享让我们发现更好的世界，让我们走的更远

**Comment by jtsang4** [comment]
> 

赞，已订阅

**Comment by jtsang4** [comment]
> @jtsang4 @xiaowuleyi 周末搭建了rss,感谢关注 [TrumanDu RSS](http://blog.trumandu.top/atom.xml)
> 
> 我尝试在竹白上写过几期，没有坚持下来，主要还是竹白的订阅方式其实没有想象的那么美好
> 
> 如果你关注的话，地址：[TrumanDu竹白地址](https://trumandu.zhubai.love/)
> 
> 再次感谢，分享让我们发现更好的世界，让我们走的更远

赞，已订阅
