### ISSUE TITLE
【播客推荐】开源面对面 - 一档从嘉宾邀请、内容、节目录制、后期都在以开源模式运作的播客

### ISSUE THREAD

**Issue by LinuxSuRen** [ruanyf/weekly#2742]
[《开源面对面》](https://github.com/opensource-f2f/episode/)是一个系列的访谈节目，旨在通过采访不同行业、岗位的开源参与者的亲身经历、心得体会，让更多的从业人员看到参与开源是一种积极的趋势与良好的职业发展方向，认识到任何人都可以参与开源，并在开源的世界里体现自己的价值。

一年多的时间内，目前录制了 25 集，[小宇宙上](https://www.xiaoyuzhoufm.com/podcast/617ab62d9a75e8810fc37b99)有 1427 个订阅。

官网：https://osf2f.net/
协作仓库：https://github.com/opensource-f2f/episode/

**Comment by LinuxSuRen** [comment]
hi @ruanyf , 感谢接受投稿，这个 issue 是需要我自行关闭吗，还是会有个统一关闭的机制

**Comment by noReply-CN** [comment]
> hi @ruanyf , 感谢接受投稿，这个 issue 是需要我自行关闭吗，还是会有个统一关闭的机制

你可以自己手动关闭，阮老师不会关大伙的issue投稿的。他只会关闭他自己开的“谁在招人”的issue。:relaxed::relaxed::relaxed:

**Comment by LinuxSuRen** [comment]
@ruanyf-fans 感谢回复
