### ISSUE TITLE
【工具推荐】中科大测速网站

### ISSUE THREAD

**Issue by xcuYao** [ruanyf/weekly#2755]
https://test.ustc.edu.cn/

开源地址：https://github.com/bg6cq/speedtest  
界面干净，没有广告，配合高网速 很舒服

![image](https://user-images.githubusercontent.com/7591385/203462200-5f728507-a18c-4c77-a8ad-7956f12aeb2f.png)

**Comment by RyanCheng08** [comment]
cool

**Comment by is1900s** [comment]
> https://test.ustc.edu.cn/
> 
> 开源地址：https://github.com/bg6cq/speedtest 界面干净，没有广告，配合高网速 很舒服
> 
> ![image](https://user-images.githubusercontent.com/7591385/203462200-5f728507-a18c-4c77-a8ad-7956f12aeb2f.png)

请问使用的是什么字体，看着挺舒服。
