### ISSUE TITLE
【文章自荐】我独立开发的产品是怎样赚到第一个 2000 元的？

### ISSUE THREAD

**Issue by vikingmute** [ruanyf/weekly#2758]
我在 8 月底发布了独立开发的产品 - [简单简历](https://easycv.cn/)，11 月 7 日对于我的产品来说是具有纪念意义的一天。它的盈利达到了 2000 元，虽然不多，但是是我人生中最激动的一笔收入，所以在这里我想分享一下第一个 2000 元过程中我的收获，经验以及教训，包括盈利的组成，MRR 计算，大家比较关心的冷启动流量的来源以及不同网站的流量来源对比，以及持续曝光等等话题，希望对大家能有所启发。

[https://vikingz.me/first-2000/](https://vikingz.me/first-2000/)

一些截图：

盈利变化：
![](https://i.imgur.com/4w6TeJW.png)

MRR 变化：
![](https://i.imgur.com/RyrbzB2.png)

首页截图：
![](https://i.imgur.com/RWYeUDM.png)

**Comment by ruanyf** [comment]
与 #2696 、#2665 重复。

警告，如果再这样重复发帖，将被拉黑。

**Comment by vikingmute** [comment]
@ruanyf 收到 不会再发了 另外 这几篇文章并不重复。

**Comment by cross-hello** [comment]
Young, you must know some of productions you sell isn't time-end-line. So 
you must maintain server beyond your dead. Have you calculated this?

----------------------------------------

*From: *Viking Zhang ***@***.***>
*To: *ruanyf/weekly ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 24, 2022 01:58:30
*Subject: *[ruanyf/weekly] 【文章自荐】我独立开发的产品是怎样赚到第一个 2000 元的？ (Issue #2758)
