### ISSUE TITLE
【工具推荐】全国地铁客流量查询

### ISSUE THREAD

**Issue by xcuYao** [ruanyf/weekly#2816]
https://metrodb.org/index/shanghai.html

地铁数据很好的反映了城市的变化，这个网站 可以查询全国大部分城市的地铁客流情况，很可惜杭州的数据是缺失的。

![image](https://user-images.githubusercontent.com/7591385/209159698-c1085be9-8552-46ca-a100-33293d6669f3.png)

**Comment by Noah1991** [comment]
这个网站的数据是从哪来的？

**Comment by battleingame** [comment]
同问

**Comment by Eminlin** [comment]
左上角不是有标注来源么：MetroDB.org
