### ISSUE TITLE
---

### ISSUE THREAD

**Issue by rolitter** [ruanyf/weekly#2838]
去除

**Comment by Linnanli** [comment]
![image](https://user-images.githubusercontent.com/17219492/210920652-9332ef45-782f-46c2-af83-430264880d03.png)

**Comment by fifsky** [comment]
真是搞不懂怎么想的，VUE 版本的ant design他不香么，为什么要用这些乱七八糟的框架，设计还一点都不规范，ant 这种标准的设计规范的框架他不香么

https://antdv.com/components/overview

**Comment by rolitter** [comment]
> 
论坛都在讨论他,害怕了呗

**Comment by rolitter** [comment]
> ![image](https://user-images.githubusercontent.com/17219492/210920652-9332ef45-782f-46c2-af83-430264880d03.png) 啥情况?
论坛都在讨论他,害怕了呗

**Comment by linonetwo** [comment]
![mmexport1672982519272.png](https://user-images.githubusercontent.com/3746270/210935703-b3685b18-fa95-4378-b340-db92ab7dde35.png)

![mmexport1672982523308.png](https://user-images.githubusercontent.com/3746270/210935711-d3286338-9118-4b21-b4d6-9d26d37d14e8.png)
