### ISSUE TITLE
【工具自荐】微信公众号文章下载工具

### ISSUE THREAD

**Issue by xiaoguyu** [ruanyf/weekly#2883]
因为喜欢看的公号有些文章发布几天会404，于是想保存在本地，就有了WechatDownload

### 下载

下载页面：https://www.javaedit.com/archives/186

### 界面

![Untitled](https://img.javaedit.com/images/2023/02/07/20450813ab77bc1c8ed7528fff28185a.png)

![Untitled](https://img.javaedit.com/images/2023/02/07/400719351ac56cc0a92593ab3c86ff3a.png)

### 功能

支持单篇下载和批量下载。其它设置看界面就知道了。

- 支持选择下载范围
- 将网页抓换成HTML、Markdown
- 将网页源码保存至Mysql（下载来源是网络才有效）
- 下载图片、音频到本地
- 添加原文链接
- 跳过现有文章

下载来源（此选项只影响批量下载）：

- 网络：就是从微信接口获取文章
- 数据库：如果选择了**保存至Mysql**选项，数据库中会保存文章的网页源码，此时如果需要将源码转换成HTML、Markdown ，选择下载来源是数据库即可。（微信接口用得多会被限制）

**Comment by liangtengyu** [comment]
推荐: 一键解析Markdown 
目前支持: 微信公众号,知乎,知乎专栏,简书,知否(SegmentFault),掘金,CSDN,V2EX,博客园

项目:https://github.com/liangtengyu/to_markdown

在线体验:http://markdown.liangtengyu.com:9999
