### ISSUE TITLE
【开源自荐】沉浸式学英语,使用自己感兴趣的电影、美剧或文档，生成词库（单词本）

### ISSUE THREAD

**Issue by tangshimin** [ruanyf/weekly#2936]
### 简介
项目地址：https://github.com/tangshimin/MuJing
幕境 - 可以使用自己感兴趣的电影、美剧或文档，生成词库（单词本）。在记忆单词时，可以练习拼写并观看相关的视频片段，以便更好的理解和记忆单词。播放电影时，以弹幕的形式复习词库中的单词，使得单词记忆不再是一件乏味的事。 
### 主要功能
1.  可以使用自己感兴趣的电影、美剧，生成词库（单词本），并且保留每个单词对应的台词，让每个单词都有具体的语境。
2. 记忆单词，记忆单词的时候，会自动播放单词的读音，然后用键盘打字练习拼写。从 MKV 生成的词库(单词本)，可以抄写单词对应的字幕，播放单词对应的视频片段。

    https://user-images.githubusercontent.com/16540656/163662386-e82dc534-7a5a-4566-8449-fc71db51f960.mp4

3. 视频播放器，以弹幕的形式复习单词。学习完电影生成的陌生单词后，把视频拖放到记忆单词界面，陌生单词会以弹幕的形式出现，点击即可查看详情。
![videoPlayer](https://user-images.githubusercontent.com/16540656/220088640-2f9c3a54-500e-477b-8c63-bc31b32d2d71.jpg)
4. 字幕浏览器，可以浏览字幕，练习跟读美剧、电影、TED演讲，可以选择性的播放一条或多条字幕，还可以抄写字幕。

    https://user-images.githubusercontent.com/16540656/174944474-e5947df9-c8ed-4546-9c67-057fe52c2d51.mp4

**Comment by itmier** [comment]
看上去好牛！你用这个学的英语怎么样了？

**Comment by tangshimin** [comment]
> 看上去好牛！你用这个学的英语怎么样了？

我的英语也不好，所以就开发了这个软件。
我现在可以直接看英文技术文档和英语字幕的美剧了。
