### ISSUE TITLE
万兴科技春招（校招&社招）火热进行中！！！深圳/长沙/杭州/郑州等地HC多多~

### ISSUE THREAD

**Issue by ahahaha2333** [ruanyf/weekly#2943]
**万兴科技介绍**
创意软件A股上市公司万兴科技（300624.SZ），全球领先的新生代数字创意赋能者，致力于成为全世界范围内有特色、有影响力的百年软件老店。
产品矩阵：

公司以“让世界更有创意”为使命，面向全球海量新生代用户，提供简单高效的数字创意软件、潮流时尚的创意资源和丰富多元的生态化服务，赋能人们在数字时代与众不同地进行创意表达，帮助每一个新生代创作者将头脑中的灵感变为可见的现实。万兴科技也是中国政府认定的“国家规划布局内重点软件企业”，跻身“德勤高科技高成长亚太区500强”、“福布斯中国最具发展潜力企业”“元宇宙创作者经济领军企业”等荣誉榜。

当前，万兴科技深耕数字创意软件领域，推出万兴喵影、万兴录演、万兴优转等视频创意软件，Wondershare Filmstock、万兴喵库视频创意素材平台，万兴爱画、万兴播爆等AIGC应用；此外面向全球市场还推出亿图图示、亿图脑图、墨刀等绘图创意软件，万兴PDF、Wondershare PDFelement等文档创意软件，万兴恢复专家、万兴数据管家等实用工具软件。公司正以前瞻的视野推进全球化布局，在深圳设立研发总部，并在长沙、北京、杭州、郑州、西安、温哥华、东京等地设立运营中心，业务范围遍及全球200多个国家和地区，全球累计用户逾15亿。
拿深圳同等高薪，住长沙宜居房子，干全球软件事业！

如果你致力于让世界更有创意，希望投身改变人们生活和工作方式的美好事业，
如果你热爱探索和创新，期望在长沙寻找一个释放个体价值的成长平台，
如果你精于品牌策划，渴望在品牌公关的道路上更加精进，
我们期待你的加入！
我们能给你：一直站在科技前沿，一份体面的薪酬，和敬业进取的同事一起共事，持续成长的机会和空间！

**内推码：NTAPnAr** 

社招官网：https://job.wondershare.cn/#/ 
校招官网：https://campus.wondershare.cn/campus_apply/wanxingkeji/41591/#/ 
了解更多请关注万兴人公众号

**社招急聘**：后端开发（Golang）、Android开发、iOS开发、前端、高级测试、信息安全、Devops开发、数据分析、高级测试、大数据开发、算法、用户运营经理、产品策划……
**校招急聘**：产品、日语/韩语线上推广、社媒运营、广告投放、网站运营，中文社媒运营、用户运营……

福利待遇：
员工健康
提供年度员工体检
与办公区健身器材

动车组激励
平台+创业者模式，
提供动车组长期贡献专项奖金

带薪休假
除法定节假日外，提供带薪
年假、带薪病假等

节庆礼品
为员工准备节日礼物
与生日津贴

五险一金
根据法定政策缴纳
五险一金

员工调户
为员工开展调户服务

股权激励
有机会成为企业合伙人
利益共享，共创未来

骨干配车
为优秀骨干配置车辆

**Comment by jack9603301** [comment]
请不要把这里当成贴吧发招聘

**Comment by ahahaha2333** [comment]
邮件已收到~谢谢!
