### ISSUE TITLE
【工具推荐】nrm 镜像源切换

### ISSUE THREAD

**Issue by hqzh** [ruanyf/weekly#2964]
[镜像源管理，快速切换不同镜像地址，比如npm,cnpm,nj,taobao](https://github.com/Pana/nrm)
![image](https://user-images.githubusercontent.com/26128706/222676446-db763e36-2b68-460e-b332-b333b05188f4.png)

**Comment by wangrongding** [comment]
![image](https://user-images.githubusercontent.com/42437658/222724451-0b46aa81-5431-4fa6-85d8-7c2782f4b614.png)

https://github.com/wangrongding/prm-cli

也可以试试我的~

**Comment by kinfuy** [comment]
https://github.com/kinfuy/gacm  我也写过 集成**npm镜像源**切换与**git账户**切换 🙋
