### ISSUE TITLE
纠正一个错误

### ISSUE THREAD

**Issue by zhusaidong** [ruanyf/weekly#3]
看到`issue-9.md`中`关于桌面 PWA`的新闻
> 刚刚发布的 Chrome 67 提供了桌面 PWA 功能

我发现现在都chrome 69都没有这个功能，于是去网站上看了下，网站上是说：

chrome os 67 支持该功能，
Windows版chrome需要到chrome 70 才支持，
而mac版需要到chrome 72 才支持。

![qq 20181014160256](https://user-images.githubusercontent.com/3039961/46914045-9ed67b80-cfca-11e8-9b8c-ef5910cb25fb.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
