### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by catsled** [ruanyf/weekly#3023]
![image](https://user-images.githubusercontent.com/18079717/229076320-5cc55c40-9e38-4391-b52c-d19792577031.png)
这里应该是一个未被验证的事情，直接下结论是否不太恰当。这么说吧，人类的认知应该也是基于现有的知识，况且去年就有人发现语言生成模型可能有自己的“黑话”

**Comment by ruanyf** [comment]
如果 ChatGPT 是基于概率的模型，这是合理的推理。

你可以把它当作一家之言。
