### ISSUE TITLE
【开源自荐】Everright-formEditor 一个可视化低代码表单编辑器

### ISSUE THREAD

**Issue by Liberty-liu** [ruanyf/weekly#3049]
# 简介
Everright-formEditor是一个免费开源的javascript可视化低代码编辑器，通过gui的界面只需简单的操作即可创建出表单，拥有灵活的交互界面，pc端依赖element-plus，mobile依赖vant,内部有一套适配器，适配element和vant的组件。

# Features
- 灵活的拖放功能(通过拖拽便可决定一个字段插入行还是列，无需布局容器)
- 提供多种字段(单行文本、邮箱、身份证号、手机号、网址、多行文本、数字、单选框、多选框、时间、日期、评分、开关、滑块、Html编辑器、级联、上传文件、签名、省市区)
- 布局字段（栅格布局、表格布局、标签页、折叠面板、分割线）
- 内置了国际化（中文和英文）
- 内置两种模式：字段与布局不分离、字段与布局分离
- 编辑器、预览器和属性面板都可以单独使用，可以根据实际需求选择性单独使用属性面板，满足不同场景下的需求
# 示例
<img width="100%" src="https://user-images.githubusercontent.com/21301475/230697059-baf94040-297e-43fc-acf2-7fa90ecaf3fb.gif">

github: [https://github.com/Liberty-liu/Everright-formEditor](https://github.com/Liberty-liu/Everright-formEditor)
文档: [https://everright.site/zh-cn/module/formEditor/introduction.html](https://everright.site/zh-cn/module/formEditor/introduction.html)

编辑器预览地址:[https://www.everright.site/demo/editor.html?layoutType=1&isEdit=1&lang=en](https://www.everright.site/demo/editor.html?layoutType=1&isEdit=1&lang=en)
预览器预览地址:[https://www.everright.site/demo/preview.html?layoutType=1&lang=en](https://www.everright.site/demo/preview.html?layoutType=1&lang=en)
属性配置面板预览地址:[https://www.everright.site/demo/formEditorConfig.html?lang=en](https://www.everright.site/demo/formEditorConfig.html?lang=en)

- 后续更新计划：

1. 历史记录
2. 将tree结构界面体现出来(内部的数据有了)
3. GUI方式控制字段显示与隐藏以及逻辑校验

知乎：[https://zhuanlan.zhihu.com/p/620830979](https://zhuanlan.zhihu.com/p/620830979)

非常感谢您花时间了解我的项目

**Comment by mzky** [comment]
很棒的项目，要是支持图表就更好了
![0009C4CB](https://user-images.githubusercontent.com/13345233/231028545-05e21ccf-ac85-4bc6-8929-8ed1307d7608.jpg)

**Comment by Liberty-liu** [comment]
> 很棒的项目，要是支持图表就更好了 ![0009C4CB](https://user-images.githubusercontent.com/13345233/231028545-05e21ccf-ac85-4bc6-8929-8ed1307d7608.jpg)

感谢认可，我会持续更新的，图表也会加进来的

**Comment by Liberty-liu** [comment]
@XiaoIsGood 目前没做，我正在做一个可视化控制字段校验、显示和隐藏，就可能让用户不写代码来实现这些功能，正则我康康是不是也要加进去，非常感谢认可
