### ISSUE TITLE
举报他人【剽窃】

### ISSUE THREAD

**Issue by gunsungithub** [ruanyf/weekly#311]
好像是他自己的blog。
http://blog.icro.me/2019/02/22/Weekly-31/

简书上原作者可以举报，不知道是否认可简书以外的文章。
https://www.jianshu.com/p/0e71148bb08b

**Comment by ruanyf** [comment]
没有出处，确实不好。

这个周刊采用创意共享的署名许可，只要注明出处，都可以自由使用。
