### ISSUE TITLE
【工具自荐】一个好用的 JSON 数据预览工具

### ISSUE THREAD

**Issue by dream-unicorn** [ruanyf/weekly#3129]
在线地址：https://json.rmst.site/
GitHub仓库：https://github.com/dream-unicorn/rmst-json-preview

目前的功能：
 - 调整缩进
 - json字符串可以转成对象
 - 控制显示数组索引
 - 面对大数据量时支持虚拟滚动
 - 缩进线高亮
 - 复制对应的数据
 - 展开/收起
 - 按住 shift 键后点击 展开/收起按钮，将对直接子级进行展开收起 （行为类似于 vscode 里的代码折叠）

效果截图：

![image](https://github.com/ruanyf/weekly/assets/52687004/678aecef-2add-401d-b932-a0f9ba8d21bd)

**Comment by kiter** [comment]
very good
