### ISSUE TITLE
【开源自荐】vite-plugin-monkey，油猴脚本开发工程化，极大增强油猴脚本开发体验

### ISSUE THREAD

**Issue by lisonge** [ruanyf/weekly#3273]
# vite-plugin-monkey

<p>
  <a href="https://www.npmjs.com/package/vite-plugin-monkey"><img src="https://img.shields.io/npm/v/vite-plugin-monkey.svg" alt="npm package"></a>
  <a href="https://github.com/lisonge/vite-plugin-monkey/releases/"><img src="https://img.shields.io/node/v/vite-plugin-monkey.svg" alt="node compatibility"></a>
</p>

一个 vite 插件，用来辅助开发 [Tampermonkey](https://www.tampermonkey.net/), [Violentmonkey](https://violentmonkey.github.io/), [Greasemonkey](https://www.greasespot.net/), [ScriptCat](https://docs.scriptcat.org/) 等脚本引擎 的脚本

## feature

- 支持 Tampermonkey, Violentmonkey, Greasemonkey, ScriptCat 等脚本引擎的辅助开发
- 打包自动注入脚本配置头部注释
- 当 第一次启动 或 脚本配置注释改变时 自动在默认浏览器打开脚本安装
- 利用 `@require` 配置库的 cdn 的方案, 减少构建脚本大小
- 利用 `@resource` 配置外部资源 cdn 的方案, 额外减少构建脚本大小
- 通过 ESM 导入的方式使用 GM_api, 附带类型提示
- 智能收集使用到的 GM_api, 自动配置 `@grant` 注释
- 支持 `top level await` 和单文件下的 `dynamic import`
- 预览模式下自动打开浏览器安装构建好的脚本
- 完全的 Typescript 和 Vite 的开发体验，比如模块热替换,秒启动

## 快速开始

使用方式与 vite create 一致

```shell
pnpm create monkey
# npm create monkey
# yarn create monkey
```

然后你能从以下模板选择

| JavaScript                                                     | TypeSript                                                            |
| -------------------------------------------------------------- | -------------------------------------------------------------------- |
| [empty](/packages/create-monkey/template-empty) (only js)      | [empty-ts](/packages/create-monkey/template-empty-ts) (only ts)      |
| [vanilla](/packages/create-monkey/template-vanilla) (js + css) | [vanilla-ts](/packages/create-monkey/template-vanilla-ts) (ts + css) |
| [vue](/packages/create-monkey/template-vue)                    | [vue-ts](/packages/create-monkey/template-vue-ts)                    |
| [react](/packages/create-monkey/template-react)                | [react-ts](/packages/create-monkey/template-react-ts)                |
| [preact](/packages/create-monkey/template-preact)              | [preact-ts](/packages/create-monkey/template-preact-ts)              |
| [svelte](/packages/create-monkey/template-svelte)              | [svelte-ts](/packages/create-monkey/template-svelte-ts)              |
| [solid](/packages/create-monkey/template-solid)                | [solid-ts](/packages/create-monkey/template-solid-ts)                |

<details open>
  <summary>示例: 初始化模板</summary>

![vue-ts](https://user-images.githubusercontent.com/38517192/191197238-214abda1-f54f-4042-a046-2d7e6cf697a2.gif)

</details>

<details open>
  <summary>示例: 模块热替换</summary>

![hmr](https://user-images.githubusercontent.com/38517192/191197411-3d6f3795-e842-4cc1-a494-5d5f8425fd15.gif)

</details>

<details open>
  <summary>示例: 构建&预览</summary>

![build&preview](https://user-images.githubusercontent.com/38517192/191197542-9c763af0-de2e-4a85-88c6-75a6d5924af9.gif)

</details>

## 项目地址

<https://github.com/lisonge/vite-plugin-monkey>

**Comment by andywang425** [comment]
非常好用的插件，无论是写简单的小脚本还是非常复杂的大型油猴脚本体验都很好。我前段时间想重构一个以前写的油猴脚本，代码量挺大的，一时间无从下手。后来找到这个插件，把原来的脚本拆分成很多小模块然后逐个实现，逻辑一下子就清晰不少。插件的热替换功能也很有用，省去了很多刷新页面的麻烦。

**Comment by jwenjian** [comment]
正好有个小脚本需要写, 回头试试

**Comment by ATQQ** [comment]
第一次开发油猴脚本的时候就用的这个，非常好用 👍🏻

**Comment by jawayang** [comment]
請問一下如果需要用到 firebase 套件，請問要怎麼設定?才能在全局中調用 firebase ?

**Comment by lisonge** [comment]
> 請問一下如果需要用到 firebase 套件，請問要怎麼設定?才能在全局中調用 firebase ?

@jawayang  与正常开发 vue/react 一样调用即可

**Comment by jawayang** [comment]
@lisonge 我想請教您一個問題
我的主程式有引用到 firebase ，
```js
import firebase from "firebase/app";
import 'firebase/firestore';
```
但我想在發布的時候把引入的方式改為 @require 引入 firebase
```js
// @require    https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js
// @require    https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js
```
請問在 vite.config.js 中應該怎麼設置? 
因為如果在程式碼中載入，發布的時候也會是載入的情況.

:) 您開發的套件真的很好用,非常感謝!

**Comment by lisonge** [comment]
下次你可以去 https://github.com/lisonge/vite-plugin-monkey/issues 提出问题

---

https://unpkg.com/browse/firebase@10.7.0/ 并没有提供 UMD 或 IIFE 格式的产物，它只有 CJS 和 ESM 格式的产物

因此你无法通过 `@require` 引入

一个可行的解决方法是 你将你使用到的这个版本的 ESM 格式转为 UMD/IIFE 格式，然后发布到 NPM 上去

方法可参考 <https://github.com/lisonge/pkg-cdn>
