### ISSUE TITLE
GitHub Markdown 支持的 emoji 备忘表

### ISSUE THREAD

**Issue by yuzhenzero** [ruanyf/weekly#331]
在 markdown 写作中加入适当的 emoji 可以提升文档的可读性，这个项目由 [GitHub Emoji API](https://api.github.com/emojis) 和 [Emoji Cheat Sheet](http://www.emoji-cheat-sheet.com/)自动生成。
https://github.com/ikatyang/emoji-cheat-sheet

**Comment by ruanyf** [comment]
这个跟 https://gist.github.com/rxaviers/7360908 好像没区别。

**Comment by yuzhenzero** [comment]
> 这个跟 https://gist.github.com/rxaviers/7360908 好像没区别。

好的，之前没有看到过这个 gist。
