### ISSUE TITLE
🚀 【项目自荐】基于Canvas的开源版"创客贴"

### ISSUE THREAD

**Issue by more-strive** [ruanyf/weekly#3336]
https://github.com/more-strive/yft-design
使用 Vue3 + TypeScript + Fabric.js + Pinia + Element-Plus，支持 文字、图片、形状、线条、二维码 、条形码几种最常用的元素类型，每一种元素都拥有高度可编辑能力，缩略图显示，模板，支持导出json，svg, image文件。
体验demo: https://more-strive.github.io/design/

![image](https://github.com/ruanyf/weekly/assets/113762408/eb71b440-02c3-48f4-872e-481d185c7124)
![image](https://github.com/ruanyf/weekly/assets/113762408/cfd4c96e-259e-4387-af64-b22c2c11009e)
![image](https://github.com/ruanyf/weekly/assets/113762408/13868aa8-328c-42b4-a6eb-b2ba2009968b)

**Comment by ruanyf** [comment]
what is the difference? https://github.com/nihaojob/vue-fabric-editor

**Comment by more-strive** [comment]
1, 项目架构不一样，这里使用的Vue3 + Typescript + Element-Plus
2, 针对印刷行业，名片，单页等做了相对限制，应用性更专业
3, 项目中用到了Pinia作为状态管理机制
4, 项目中用到了indexdb作为数据管理
5, 背景图设置集合了其他开源项目 https://github.com/qrohlf/trianglify，
6, 缩略图显示
