### ISSUE TITLE
【工具自荐】一款怀旧复古的扫雷小游戏

### ISSUE THREAD

**Issue by zerosoul** [ruanyf/weekly#3491]
利用周末时间做的扫雷小游戏，做它的缘由是前段时间想玩扫雷小游戏，复古怀旧的那种，在网上找了一圈，要么太花哨，要么太简陋，还挂了一堆广告，自己用的mac，而且window98系统也不太好搞得到，决定自己撸一个。

https://ohminesweeper.online/

特性：

- 具备经典扫雷游戏的所有功能

- Win98风格界面

- 原声声效：默认关闭

- 支持快捷键操作

- 游戏记录：自动生成历史记录

- 支持PWA：无论手机还是PC，可安装，接近原生APP体验

- 游戏截图：游戏结果截图

- 多语言支持（计划中）

- 在线排名（计划中）

- 可分享同样配置的给ta人一起玩（计划中）

如果你也怀旧，可以把玩一下这款纯粹的扫雷小游戏：https://ohminesweeper.online/

![localhost_3888_a_how-to](https://github.com/ruanyf/weekly/assets/2985895/257367a4-e1e1-45e3-a36a-9bf6952d970a)

**Comment by zerosoul** [comment]
更新： 新增XP主题，快捷键操作（纯键盘就可以玩）

**Comment by mohuani** [comment]
我有一个珍藏版的
https://xzhyj93.github.io/Mine-Sweep/

**Comment by zerosoul** [comment]
> 我有一个珍藏版的 https://xzhyj93.github.io/Mine-Sweep/

这个也不错哈~
