### ISSUE TITLE
github 升级 Feed filters 后，无法得到更新提醒

### ISSUE THREAD

**Issue by listenfree** [ruanyf/weekly#3508]
如题，github 升级 Feed filters 后，无法得到更新提醒。
以前有新的，每周都能看到更新，现在我把Feed filters全部开启，都没有提醒。这样会减少很多阅读量。

**Comment by ruanyf** [comment]
你看看前几天网友的插件 #3478 ，也可以订阅 ruanyifeng.com 的 RSS 。
