### ISSUE TITLE
科技爱好者周刊（第 274 期）文章bug

### ISSUE THREAD

**Issue by q845655058** [ruanyf/weekly#3574]
科技爱好者周刊（第 274 期）：加密通信的最后一块拼图 的人造重力 文章描述的应该是离心力，为什么是向心力？

**Comment by murphysking** [comment]
来自维基百科的解释

-----
向心力是当物体沿着圆周或者曲线轨道运动时，指向圆心（[曲率](https://zh.wikipedia.org/wiki/%E6%9B%B2%E7%8E%87)中心）的合外力作用力。“向心力”一词是从这种合外力作用所产生的效果而命名的。这种效果可以由[弹力](https://zh.wikipedia.org/wiki/%E5%BC%B9%E5%8A%9B)、[重力](https://zh.wikipedia.org/wiki/%E9%87%8D%E5%8A%9B)、[摩擦力](https://zh.wikipedia.org/wiki/%E6%91%A9%E6%93%A6%E5%8A%9B)等任何一力而产生，也可以由几个力的[合力](https://zh.wikipedia.org/wiki/%E5%90%88%E5%8A%9B)或其[分力](https://zh.wikipedia.org/w/index.php?title=%E5%88%86%E5%8A%9B&action=edit&redlink=1)提供。

因为[圆周运动](https://zh.wikipedia.org/wiki/%E5%9C%93%E5%91%A8%E9%81%8B%E5%8B%95)属于[曲线运动](https://zh.wikipedia.org/wiki/%E6%9B%B2%E7%BA%BF%E8%BF%90%E5%8A%A8)，在做圆周运动中的物体也同时会受到与其速度方向不同的合外力作用。对于在做圆周运动的物体，向心力是一种拉力，其方向随着物体在圆周轨道上的运动而不停改变。此拉力沿着圆周半径指向圆周的中心，所以得名“向心力”。向心力指向圆周中心，且被向心力所控制的物体是沿着[切线](https://zh.wikipedia.org/wiki/%E5%88%87%E7%BA%BF)的方向运动，所以向心力必与受控物体的运动方向垂直，仅产生速度[法线](https://zh.wikipedia.org/wiki/%E6%B3%95%E7%BA%BF)方向上的[加速度](https://zh.wikipedia.org/wiki/%E5%8A%A0%E9%80%9F%E5%BA%A6)。因此向心力只改变所控物体的运动方向，而不改变运动的速率，即使在[非匀速圆周运动](https://zh.wikipedia.org/w/index.php?title=%E9%9D%9E%E5%8C%80%E9%80%9F%E5%9C%86%E5%91%A8%E8%BF%90%E5%8A%A8&action=edit&redlink=1)中也是如此。[非匀速圆周运动](https://zh.wikipedia.org/w/index.php?title=%E9%9D%9E%E5%8C%80%E9%80%9F%E5%9C%86%E5%91%A8%E8%BF%90%E5%8A%A8&action=edit&redlink=1)中，改变运动速率的切向加速度并非由向心力产生。

-----
离心力（英语：centrifugal force）是一种虚拟力或称[惯性力](https://zh.wikipedia.org/wiki/%E6%85%A3%E6%80%A7%E5%8A%9B)，它使旋转的物体远离它的旋转中心。在牛顿力学里，离心力曾被用于表述两个不同的概念：在一个[非惯性参考系](https://zh.wikipedia.org/wiki/%E9%9D%9E%E6%83%AF%E6%80%A7%E5%8F%82%E8%80%83%E7%B3%BB)下观测到的一个惯性力，和[向心力](https://zh.wikipedia.org/wiki/%E5%90%91%E5%BF%83%E5%8A%9B)的反作用力。在[拉格朗日力学](https://zh.wikipedia.org/wiki/%E6%8B%89%E6%A0%BC%E6%9C%97%E6%97%A5%E5%8A%9B%E5%AD%A6)下，离心力有时被用来描述在某个[广义坐标](https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E5%9D%90%E6%A0%87)下的[广义力](https://zh.wikipedia.org/wiki/%E5%BB%A3%E7%BE%A9%E5%8A%9B)。

在通常语境下，离心力并非真实的存在。它的作用只是为了在旋转参考系（非惯性参考系）下，[牛顿运动定律](https://zh.wikipedia.org/wiki/%E7%89%9B%E9%A1%BF%E8%BF%90%E5%8A%A8%E5%AE%9A%E5%BE%8B)依然能够使用。在[惯性参考系](https://zh.wikipedia.org/wiki/%E6%83%AF%E6%80%A7%E5%8F%82%E8%80%83%E7%B3%BB)下是没有惯性力的，在非惯性参考系下（如旋转参考系）才需要有惯性力，否则[牛顿运动定律](https://zh.wikipedia.org/wiki/%E7%89%9B%E9%A1%BF%E8%BF%90%E5%8A%A8%E5%AE%9A%E5%BE%8B)不能使用。
