### ISSUE TITLE
【产品自荐】筷字输入法：汉语拼音滑屏输入新方案

### ISSUE THREAD

**Issue by flytreeleft** [ruanyf/weekly#3578]
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/774187c4-e683-4e4c-bcfb-e1b24ae2bde3" height="500" title="筷字输入法预览图"/>

> - Google Play 地址: https://play.google.com/store/apps/details?id=org.crazydan.studio.app.ime.kuaizi
> - 项目地址: https://github.com/crazydan-studio/kuaizi-ime
> - 内测尝鲜版下载地址（需解压）: https://github.com/crazydan-studio/kuaizi-ime/files/13194753/Kuaizi_IME-1.1.0-alpha.zip

**筷字输入法** 是一款根据汉语拼音的组合特征而专门设计的、高效且快速的、适用于电子触屏设备的拼音输入法。

**筷字输入法** 摒弃传统的逐个点击虚拟键盘按键的录入方式，改为以滑屏方式录入拼音，并结合拼音字母的有限组合特征，精心设计按键布局，让拼音输入更加准确且便捷。

**筷字输入法** 同时提供对目标编辑器的光标移动和文本选择等编辑支持，从而彻底摆脱因移动设备屏幕太小而无法准确定位输入和文本位置的烦恼，进一步提高在小屏设备上的文本输入和编辑效率。

**筷字输入法** 的用户数据仅留存在本地，其不连接互联网，不会收集和分析用户数据和行为习惯。其也不支持和提供联想输入和模糊匹配机制，在某种程度上，该输入法是希望加强用户对汉字和拼音的识别和记忆能力，不要因为对数字工具的依赖而逐渐遗忘并最终丢弃<b>「汉字」</b>这一中华文明的瑰宝。

## 关于图标

<img src="https://raw.githubusercontent.com/crazydan-studio/kuaizi-ime/master/assets/img/logo.svg" width="128" title="筷字输入法 Logo"/>

**筷字输入法** 的图标由汉字<b>「字」</b>与中国特色餐具<b>「筷子」</b>组合而成，该组合将中华文明与其人民独有的饮食文化紧密相连，既展现了中华文明悠久的历史，也有助于向世界传播中华的传统文化，加深世界友人对中华文化的认识和了解，同时，也让中华儿女能够对其民族文化拥有更加坚定的自信。

## 功能特性

- 以连续滑屏方式录入拼音，且单次录入最多仅需滑屏两次
- 所有候选字均附带显示完整的拼音，可清晰识别各个字的准确读音
- 输入数据本地存储，不收集、不分析用户数据
- 仅支持精确的拼音输入匹配，**不支持**拼音联想输入和模糊匹配机制
- 提供光标移动、文本选择、复制、粘贴、剪切等编辑功能，同时，支持撤回已提交至目标编辑器的输入，以便于对输入进行修正
- 支持左右手模式切换，以适应不同的用户使用习惯
- 支持简单的数学四则运算，可以边输入边计算
- 支持录入标点、表情等文本符号，提供丰富的内容表达形式
- 支持直接输入括号、引号等配对的标点符号，并自动将选中内容包裹在配对符号中
- 在拉丁字符与汉字、操作数与运算符之间自动添加空格，以规范输入格式

<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/766cea91-5a1b-48d5-9ce0-d921a43fefe3" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/b21413f0-1357-426f-b536-d5bfe6b47f2f" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/eef674fb-b41c-4514-9167-37b9b88cfe8a" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/8ecd285d-aa9a-4274-b5f9-879bc20b0ab5" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/643016b6-462b-4079-93d5-50a54a97de1b" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/4e0afd48-d9e9-4b84-a17d-bd8f570bbadc" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/e13c6f18-c9e1-4141-bed2-2024ac77782f" height="300"/>
<img src="https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/04cb3b6b-343a-4174-8521-ca1b34afa175" height="300"/>

### 拼音滑屏输入

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/eb2f74f9-f64e-4d02-ad80-98e3ecb9d61b

### 算数输入

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/f461b564-0ac4-4257-82ad-11afcd3e1d6c

### 内容编辑

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/992a0a5e-7e1e-4b93-a1ac-c893d0e3ff2e

### 表情符号匹配

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/7fff6ddf-9e10-408f-b160-3b3b8e2ab215

### 配对符号输入

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/97b0f99b-92e1-4b28-a5b6-d45150c4bada

### 英文/拼音输入补全

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/c77c37e8-054c-41f7-a5ba-db407964fb60

### 拼音输入提交选项

https://github.com/crazydan-studio/kuaizi-ime/assets/1321315/274d41dd-e858-4b71-a041-31df3dd24f7d

**Comment by jwenjian** [comment]
我来试一下, 看看和现在主流输入法的滑动输入有什么区别 ;)

**Comment by jwenjian** [comment]
最好也能给个 APK 链接.

**Comment by flytreeleft** [comment]
> 最好也能给个 APK 链接.

@jwenjian 在前面正文中已添加尝鲜版下载地址，你可以试用一下，有什么问题可以点击 APP 中的**意见与建议**进行反馈。

**Comment by amitbha** [comment]
必须要完整拼音吗？我分不清 in 和 ing，en 和 eng

**Comment by amitbha** [comment]
我现在在用岁寒滑行输入，感觉不错，支持模糊音和语音输入
不过语音输入用的是免费服务，延迟较大

**Comment by flytreeleft** [comment]
> 必须要完整拼音吗？我分不清 in 和 ing，en 和 eng

@amitbha 是的，使用完整拼音就不需要复制的模糊匹配了 :)。前后鼻韵分不清也没关系，可以在选候选字时再纠正拼音，在候选字页面提供切换支持。

**Comment by flytreeleft** [comment]
> 我现在在用岁寒滑行输入，感觉不错，支持模糊音和语音输入 不过语音输入用的是免费服务，延迟较大

@amitbha 岁寒输入也不错，筷字输入法的输入撤回功能就是从岁寒的重新上屏了解到的。模糊和语音输入，筷字可能不会去做，这两块的工作量比较大，后面会加强输入流畅性和顺滑性方面的工作。
