### ISSUE TITLE
【工具推荐】280 期周刊的所有推荐工具的向量化语义搜索

### ISSUE THREAD

**Issue by ahaapple** [ruanyf/weekly#3701]
将280期周刊推荐的所有工具进行了向量化处理，提供向量化语义搜索功能。 向量化语义搜索功能是基于 faiss 索引库，Transformers 自然语言处理库，Fastapi 框架实现

网址：  https://www.apigpts.dev/tools

效果：

<img width="825" alt="tools-vector-1" src="https://github.com/ruanyf/weekly/assets/151364778/66a37d5e-6966-4d1d-b39e-30b00dc56ab0">

<img width="818" alt="tools-vector-2" src="https://github.com/ruanyf/weekly/assets/151364778/fed3697b-4912-4678-9f45-ae34f9d2f879">

**Comment by jwenjian** [comment]
不错, 也欢迎把我的周刊里的内容加进去 https://1link.fun

**Comment by rainwalkerhu** [comment]
要是有分类和推荐就好了,脑子一片空白不知道搜索关键字

**Comment by flashlab** [comment]
@ahaapple 很多图片无法显示，不知道啥原因

**Comment by gowk** [comment]
awesome!

**Comment by ahaapple** [comment]
> 要是有分类和推荐就好了,脑子一片空白不知道搜索关键字

@rainwalkerhu 感谢反馈，这个周末会加上

**Comment by ahaapple** [comment]
> @ahaapple 很多图片无法显示，不知道啥原因

@flashlab 因为周刊有些工具没有图片，这个有时间的话，再抓个图。

**Comment by ahaapple** [comment]
@flashlab 已经支持分类和推荐，也支持随机返回数据。

**Comment by ahaapple** [comment]
https://www.ahavs.com/tools

**Comment by aha-weikai** [comment]
请求接口失败，code：500

**Comment by ahaapple** [comment]
https://github.com/memfreeme/memfree  前后端代码已经开源，欢迎 star, 感谢
