### ISSUE TITLE
【网站推荐】基于282 期周刊的 Chat 服务

### ISSUE THREAD

**Issue by ahaapple** [ruanyf/weekly#3767]
将282期周刊的所有内容进行了向量化索引，然后通过向量化索引给 ChatGPT 提供准确的上下文，返回的消息中也会显示引用的周刊文档：

https://www.ahavs.com/chat-ruanyifeng

![chat-ruanyifeng](https://github.com/ruanyf/weekly/assets/151364778/5bf5b266-e3f0-473e-8e82-fa35070328de)

**Comment by web1992** [comment]
这个是怎么实现的，能一个大概的思路吗

**Comment by liuqinghang** [comment]
俺也想学习学习，大佬能说下大概的思路呢

**Comment by ahaapple** [comment]
https://github.com/memfreeme/memfree  @web1992 @liuqinghang 前后端所有代码已经开源，欢迎给个 star, 感谢

**Comment by YellowOrz** [comment]
这个网站似乎不工作了

**Comment by ahaapple** [comment]
https://www.memfree.me/ @YellowOrz 你好，可以使用的新的搜索网址。  之后会专门为这个周刊新增一个页面。
