### ISSUE TITLE
【产品自荐】支持任意 RSS 源订阅，专注优质信息源分享、整理、订阅的中文社区

### ISSUE THREAD

**Issue by jiannei** [ruanyf/weekly#3775]
![SNC](https://raw.githubusercontent.com/jiannei/snc-pro/master/images/202312210957358.png)

为了更好地收集优质资源，专门学前端做了这个网站：https://sinan.fun

### 介绍

使用vue3、unocss 、vite5、bun构建，页面已适配移动端，并支持暗黑模式。支持创建子社区，围绕问题讨论、产品展示、RSS订阅、技术文档、编程导航进行内容建设，旨在探索发现更多的优质信息源。

### 内容形式

* **帖子**：分享产品相关的想法，或是合集形式的作品展示，也可以是技术相关的问题讨论
* **RSS**：可以通过 [RssHub](https://docs.rsshub.app/zh/) 项目来发现感兴趣的信息源，添加发布后内容会定时更新，也支持手动刷新。关于 RSS 数据的解析实现已开源  [laravel-crawler](https://github.com/jiannei/laravel-crawler) ，通过该扩展还可以解锁 RSSHub 以外的信息源添加技巧
* **文档**：基于 Github 发起技术相关的文档维护，会定时同步，目的是发现并整理优质的技术文档，以开源协作的方式来促进文档的及时性
* **链接**：发布编程相关的链接，会定时校验链接的有效性

更多内容形式持续探索中...

RSS 部分可以前往体验：https://sinan.fun/rss

**Comment by jwenjian** [comment]
一个建议, 关于 RSS 的文章展示, 最好可以添加一个 RSS 源网站的链接, 可以让感兴趣的用户进到源网站浏览更多, 而且也可以给源网站分得一些流量, 互惠互利.

另外推荐下我自己的科技周刊, 有 RSS: https://1link.fun

**Comment by jiannei** [comment]
@jwenjian 不错的建议，会在下一次发布实现。

周刊订阅已添加，向持续输出的内容创作者们致敬🫡
