### ISSUE TITLE
【开源自荐】DouyinLiveRecorder：抓取直播源基于ffmpeg的多平台直播录制工具

### ISSUE THREAD

**Issue by ihmily** [ruanyf/weekly#3809]
## 💡简介

一款免费的可循环值守的简易直播录制工具，基于FFmpeg实现多平台直播源录制，支持自定义配置录制以及直播状态推送。

**特性**：可循环值守和多人录制的直播录制软件，支持抖音、Tiktok、快手、虎牙、斗鱼、B站、小红书、AfreecaTV等平台直播录制，抓取多平台直播源地址，抖音无水印解析，快手无水印解析

</div>

## 😺已支持平台

- [x] 抖音
- [x] TikTok
- [x] 快手
- [x] 虎牙
- [x] 斗鱼
- [x] YY
- [x] B站
- [x] 小红书
- [x] bigo 
- [x] blued
- [x] AfreecaTV
- [ ] 更多平台正在更新中

</div>

## 📷预览图
![image](https://github.com/ruanyf/weekly/assets/114978440/71b12ab5-87e7-4c62-946e-85795afda9c2)
![012eb2248c0e75348b792c187a06e8e](https://github.com/ruanyf/weekly/assets/114978440/5c57bf0d-148a-49d2-ae4b-84ea99d877b7)

## 🚀下载安装

项目地址：
https://github.com/ihmily/DouyinLiveRecorder

更新地址：
https://github.com/ihmily/DouyinLiveRecorder/releases

打包软件下载地址：
https://github.com/ihmily/DouyinLiveRecorder/releases/download/v2.0.7/DouyinLiveRecorder.v2.0.7.zip
&emsp;
&emsp;

**Comment by 28LO** [comment]
我要咋联系你呀大佬？纯小白看不懂这个代码
