### ISSUE TITLE
【开源自荐】将 Github Copilot 请求转换为 ChatGPT 请求，免费使用 GPT-4 模型

### ISSUE THREAD

**Issue by aaamoon** [ruanyf/weekly#3820]
## 背景
通过抓包我们可以发现 Github Copilot Chat 其实底层是调用 OpenAI 的 ChatGPT 接口，那么我们就可以将 Github Copilot Chat 的请求转换为 ChatGPT 请求。只要我们拥有 Github Copilot 账号，就能无限制使用 ChatGPT 的 GPT-4 模型。

## 实现原理

![实现原理](https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/assets/principle.png)

## 源码地址
https://github.com/aaamoon/copilot-gpt4-service

## 使用方法
1、访问 https://gpt4copilot.tech

2、在设置的接口地址填入本仓库项目部署出来的api地址 https://gpt4copilot.tech

3、在API Key中填入Github Copilot Token（可以通过[copilot-token接口](https://cocopilot.org/copilot/token)来获取，Token的格式是以ghu_开头）

![步骤1](https://raw.githubusercontent.com/aaamoon/copilot-gpt4-service/master/assets/step1.png)

4、支持各种OpenAI模型选择，目前默认使用的是GPT-4模型

5、接下来我们就可以无限制使用GPT-4模型了~

**Comment by YunTaoLin** [comment]
感謝分享
請問如果帳號本身訂閱的是copilot for business，一般在使用時所有資料都會被限制在企業內，可以避免資料外流的風險。
但使用這個方式來無限制使用GPT-4模型，是否還可以維持這樣的隱私保障呢?

**Comment by aaamoon** [comment]
@YunTaoLin 这个我就不太确定了，如果是企业版的话，不清楚会不会在调用 Open AI 接口时加上什么特定字段，我这边没有尝试过使用企业账号的场景

**Comment by Stanley-baby** [comment]
希望这个项目可以用 CF 的worker来搭建。 发件人: exia ***@***.***>日期: 星期四, 2024年2月1日 19:40收件人: ruanyf/weekly ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [ruanyf/weekly] 【开源自荐】将 Github Copilot 请求转换为 ChatGPT 请求，免费使用 GPT-4 模型 (Issue ***@***.*** 这个我就不太确定了，如果是企业版的话，不清楚会不会在调用 Open AI 接口时加上什么特定字段，我这边没有尝试过使用企业账号的场景—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by aaamoon** [comment]
> 希望这个项目可以用 CF 的worker来搭建。 发件人: exia ***@***.***>日期: 星期四, 2024年2月1日 19:40收件人: ruanyf/weekly ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [ruanyf/weekly] 【开源自荐】将 Github Copilot 请求转换为 ChatGPT 请求，免费使用 GPT-4 模型 (Issue ***@***.*** 这个我就不太确定了，如果是企业版的话，不清楚会不会在调用 Open AI 接口时加上什么特定字段，我这边没有尝试过使用企业账号的场景—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CD worker 更换 IP 地址频繁，容易被判定为异常行为，可能会对 Github 账号造成风险，不建议这种方式

**Comment by 0x3fffff** [comment]
现在失效了？

**Comment by aaamoon** [comment]
> 现在失效了？

仓库被封了，不建议再用了

**Comment by Louis-udm** [comment]
为何会被封？ 还有fork吗？
