### ISSUE TITLE
【错误提醒】第 287 期：禄丰恐龙谷记行 - 图片 - 2、透过双腿观察

### ISSUE THREAD

**Issue by BruinK** [ruanyf/weekly#3932]
周记文中是：
> 心理学家很早就发现，两根同样长度的线，一根水平，一根垂直。人们会觉得水平的那根更长一点，这被认为是一种“视觉错觉”。

![image](https://github.com/ruanyf/weekly/assets/18461030/0e0755e7-d41d-44ca-8c05-362ab0283bb3)

但是我实际看起来觉得还是红线长，而且特别明显。
所以我看了链接的原文，如下：
![image](https://github.com/ruanyf/weekly/assets/18461030/9026359e-14f5-43e1-bd0b-0dad4af00d82)

所以，是否存在翻译错误？

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
