### ISSUE TITLE
【功能建议】建议添加类似周刊关键词搜索功能

### ISSUE THREAD

**Issue by AAABingBing** [ruanyf/weekly#3945]
周刊中有好多实用工具，但是当真正要用到的时候却不容易找到

建议添加个类似周刊关键词搜索功能，可以通过关键词检索对应周刊

**Comment by HailPHP** [comment]
之前阮老师分享过关于周刊内容关键词的搜索：

https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fruanyf%2Fweekly%24+IT&patternType=standard

**Comment by AAABingBing** [comment]
> 之前阮老师分享过关于周刊内容关键词的搜索：
> 
> https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fruanyf%2Fweekly%24+IT&patternType=standard

感谢解答
