### ISSUE TITLE
第48期文章网站扩展的图说教程（英文）的翻译版本

### ISSUE THREAD

**Issue by ShayLau** [ruanyf/weekly#397]
老师你好，上一周的分享有一篇文章提到**网站的扩展图说教程引文版**

自己手工查资料翻译了一下，我把同步到了我的语雀和微信公众号上面了

**文章的链接：**

[微信公众号文章：如果从带胎服务器扩展一个可以服务百万用户的Web站点](https://mp.weixin.qq.com/s/RbepG4rrCIDGTQ6WDBcTpQ)

[语雀:如何从单台服务器扩展一个可以服务百万级用户的We（翻译）](https://www.yuque.com/sourlemon/java/dtgpwb)

**Comment by ruanyf** [comment]
这篇文章很不错，但推荐过英文原版了，中文版不再单独推荐了。
