### ISSUE TITLE
【开源自荐】HomeInfra: 可重现的可靠Homelab for DevOps，全站 HTTPS、OAuth、Git、CD/CD、定时任务、自动备份、监控 and more

### ISSUE THREAD

**Issue by NoCLin** [ruanyf/weekly#3977]
演示站点：https://homeinfra.org/ (2H2C小机器)

repo: https://github.com/homeinfra-org/infra

适用群体：Homelab for DevOps 或者 小型互联网团队

Features：

- 通过Docker + Docker-Compose定义容器
- 全站HTTPS: https://*.homeinfra.org，基于traefik 和 Cloudflare
- [gitea](https://git.homeinfra.org/) 作为 git server 和 OAuth Provider ，支持通过 Github 登录，也支持作为各种语言的Registry
- 基于 Gitea Actions (与 Github Actions 兼容）实现CI/CD。
- 基于Actions的[定时任务](https://git.homeinfra.org/root/cronjobs/actions)。
   - DDNS
   - uptime-kuma Watchdog
   - 可以接入自己的各种监控脚本
- 通过[dockge](https://dockge.homeinfra.org/)管理 Docker ，通过OAuth2-Proxy保护。
- [uptime-kuma](https://uptime.homeinfra.org/) 监控，监控各个 https 站点、DNS、docker container等，第一时间了解Downtime。
- homeassistant 管理IOT设备
- 集成OpenVSCode 在线管理代码，通过OAuth2-Proxy保护。
- 通过Restic定时备份到S3
- 集成FileBrowser等App
- grafana + OAuth

TODO:

- waf
- grafana + loki 集成
- FRP / CloudFlare Tunnel / Zerotier Demo

<img width="1037" alt="image" src="https://github.com/ruanyf/weekly/assets/31406718/9b2a3a9b-fa4c-434d-81d8-74e92ca78810">

<img width="1374" alt="image" src="https://github.com/ruanyf/weekly/assets/31406718/d574b415-8955-439e-9f3f-a00b951a9adc">

**Comment by X4tar** [comment]
LGTM

**Comment by wzl778633** [comment]
LGTM!

**Comment by NoCLin** [comment]
谢谢推荐！

**Comment by reatang** [comment]
现在家用服务器都这么高级了么
