### ISSUE TITLE
【开源推荐】在 Clash 上使用免费，无限制，高速 Warp+ 代理

### ISSUE THREAD

**Issue by CorrectRoadH** [ruanyf/weekly#3994]
> 通过订阅在 Clash 和 Surge 上一键导入无限流量，高速的 Warp+ 代理，无需任何额外的配置。适用于任何需要科学上网的情况。可以通过 Docker 自部署，通过这样使用代理不会留下与机场的交易信息，非常合适匿名、临时性的使用。

开源地址: https://github.com/vvbbnn00/WARP-Clash-API

- 可以通过 Clash、Shadowrocket、Surge 等等多种软件直接订阅使用。
- 也可以通过 Wireguard 导入配置使用 Warp+ 的节点。

社区部署实例: https://tofree.zeabur.app

![CleanShot 2024-01-30 at 23 06 17@2x](https://github.com/ruanyf/weekly/assets/29306285/e88026dd-2316-4b47-9231-2f148acc58d2)

节点信息(每次更新订阅都会获得不同的节点):

![节点信息](https://github.com/ruanyf/weekly/assets/29306285/50433f2d-57a2-49fe-9ad4-b09d110c3838)

**Comment by jakbroot** [comment]
感谢楼主分享

**Comment by linmuxi117** [comment]
OK了家银

**Comment by 1368129224** [comment]
请问下这个前端是自己改的吗？

**Comment by CorrectRoadH** [comment]
> 请问下这个前端是自己改的吗？

是的。代码在 https://github.com/CorrectRoadH/free-warp

**Comment by lunat1cccc** [comment]
请问一下如果我自己部署，ios想获得订阅的话，是不是必须部署到公网

**Comment by dyxfanfan** [comment]
新手小白 订阅了还是用不了 有没有大神可以拯救一下我呜呜呜呜

**Comment by linmuxi117** [comment]
> 新手小白 订阅了还是用不了 有没有大神可以拯救一下我呜呜呜呜

clash的话设置里面打开服务模式和Tun模式

**Comment by dyxfanfan** [comment]
> > 新手小白 订阅了还是用不了 有没有大神可以拯救一下我呜呜呜呜
> 
> clash的话设置里面打开服务模式和Tun模式

Tun模式我找到了 服务模式在哪呀 而且Tun模式开了好像没反应

**Comment by linmuxi117** [comment]
> > > 新手小白 订阅了还是用不了 有没有大神可以拯救一下我呜呜呜呜
> > 
> > 
> > clash的话设置里面打开服务模式和Tun模式
> 
> Tun模式我找到了 服务模式在哪呀 而且Tun模式开了好像没反应

Tun下面的就是服务模式，点开后下一个插件，下完后旁边有个小绿球还是绿盾来着就行了
Tun模式需要先开服务模式才有效果

**Comment by dyxfanfan** [comment]
> > > > 新手小白 订阅了还是用不了 有没有大神可以拯救一下我呜呜呜呜
> > > 
> > > 
> > > clash的话设置里面打开服务模式和Tun模式
> > 
> > 
> > Tun模式我找到了 服务模式在哪呀 而且Tun模式开了好像没反应
> 
> Tun下面的就是服务模式，点开后下一个插件，下完后旁边有个小绿球还是绿盾来着就行了 Tun模式需要先开服务模式才有效果

哥 还是不太会 你可以加我的微信给我讲一下吗 球球了（D13198193790）

**Comment by waitingyou** [comment]
非常感谢提供的实例。
实例配置里面有些地方是需要修改的，否则会出现谷歌Play商店能浏览却不能下载，解决了Play商店问题回头安卓Youtube又不能播放了。
首选我使用的硬件是JGC-Q20路由器使用OpenClash 0.45.16，安卓鸿蒙3.0使用Clash Meta，MacOS10.15使用Clash Verge。
使用订阅的配置是不能在Play商店下载任何软件的，在Fallback-Filter里面删除services.googleapis.cn和xn--ngstr-lra8j.com后，
添加
rules:
- DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
Play商店下载的问题就解决了，下载速度也非常快，但新问题就是一直都是中国商店。请问是否设置把services.googleapis.cn和xn--ngstr-lra8j.com固定为国外网站就能变成国外商店？
很奇怪使用OpenClash和Clash Verge订阅会多了
- dns:
  - 1.1.1.1
  - 1.0.0.1
而使用安卓的Clash Meta订阅就没有此项。这一项会导致安卓的YouTube是打不开的，iOS就不受影响。
我解决办法就是删除这些dns项目，路由器的OpenClash里面自定义上游dns就好了。
最后请问如何设置才能看TikTok，我暂时没有头绪。

**Comment by Stanley-baby** [comment]
请问这个可以用cf来部署吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: CorrectRoad ***@***.***>
发送时间: Thursday, March 14, 2024 5:07:14 PM
收件人: ruanyf/weekly ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ruanyf/weekly] 【开源推荐】在 Clash 上使用免费，无限制，高速 Warp+ 代理 (Issue #3994)


请问下这个前端是自己改的吗？

是的。代码在 https://github.com/CorrectRoadH/free-warp

―

**Comment by qiyuqingyun** [comment]
好像失效了

**Comment by lyc592git** [comment]
请问社区部署实例是否已经失效

**Comment by qiyuqingyun** [comment]
> 请问社区部署实例是否已经失效

是的，clash链接失效了

**Comment by clkljh** [comment]
哥，为什么导入之后梯子延迟很低，却无法访问链接，甚至不能使用play商店😭😭😭

**Comment by CorrectRoadH** [comment]
@qiyuqingyun @bijhla @clkljh 感谢反馈。我有空就看看，看看能不能修好一下。

**Comment by CorrectRoadH** [comment]
@qiyuqingyun @bijhla @clkljh 目前已经能用了。后续会加一个status page来监控节点情况，再做一些额外的处理来保证可用性。

**Comment by clkljh** [comment]
> @qiyuqingyun @bijhla @clkljh 目前已经能用了。后续会加一个status page来监控节点情况，再做一些额外的处理来保证可用性。

哥，可以告诉我是对网络和覆写有什么要求吗？我还是没办法上网😭可能是我自己的问题😭我用的是手机版clashmeta，不知道怎么设置🤡

**Comment by clkljh** [comment]
> @qiyuqingyun @bijhla @clkljh 目前已经能用了。后续会加一个status page来监控节点情况，再做一些额外的处理来保证可用性。

可能对您添麻烦了🤧很抱歉😭

**Comment by bijhla** [comment]
@clkljh 我并未使用过手机版，但你可以试试在clashmeta的github项目中发布issue

**Comment by clkljh** [comment]
> @clkljh 是节点全超时还是未超时但不能访问呢

无法访问网络😭

**Comment by huochui555** [comment]
我想问一下clash按网上改了还是会出现redir-host错误是什么原因

**Comment by rainlycoris** [comment]
现在用不了了，我自己生成的配置也不能用，请问是什么情况啊，应该不是墙的问题。

**Comment by waitingyou** [comment]
请问有没有适用于路由器OpenClash跑IPV6的实例，你的模板小改后在电脑和手机跑IPV6是通过的，但在路由器OpenClash上就行不通

**Comment by zhengyang3552** [comment]
为什么社区部署实例网站已暂时暂停

**Comment by CorrectRoadH** [comment]
> 为什么社区部署实例网站已暂时暂停

因为gfw更新了，新的CF WARP不太好用了。这个服务已经基本不太可用了

**Comment by lansedoujiao** [comment]
大佬们我不知道怎么用，能教教我吗？下了个clash不是要在订阅里面导入链接嘛，这里哪有那个链接，怎么弄？
