### ISSUE TITLE
关于前9篇命名

### ISSUE THREAD

**Issue by troy351** [ruanyf/weekly#4]
在docs文件夹中，github默认字典顺序排列，导致`issue-1.md`后面是`issue-10.md`而不是`issue-2.md`。
建议将`issue-[1-9].md`改成`issue-0[1-9].md`，这样阅读顺序就正常了。

**Comment by ruanyf** [comment]
我想过这个问题，如果是三位数的编号怎么办呢？

**Comment by troy351** [comment]
有道理。不妨以日期命名，比如issue-181015.md，这样就没有位数的问题了

**Comment by ruanyf** [comment]
这也是一个办法，有点像报纸。

目前，还是先做成期刊。毕竟，markdown 仓库只是存档，大家阅读还是提倡去网站。

**Comment by AnyListen** [comment]
感觉还是有比较规则的命名比较好，即便是作为仓库，我们也有很多场景需要按照文件夹来进行排序查找；
目前的命名，按照名称排序得到的结果其实是不大理想的，希望可以进行规范化

**Comment by ruanyf** [comment]
已经在 README 加了目录，应该没问题了。
