### ISSUE TITLE
开源图书：《C/C++面向WebAssembly编程》

### ISSUE THREAD

**Issue by chai2010** [ruanyf/weekly#40]
https://github.com/3dgen/cppwasm-book

**Comment by ruanyf** [comment]
挺好的，可惜大部分都没有写完。已经完成的部分，我也觉得有点简单。

**Comment by chai2010** [comment]
感谢大神认可和支持，目前更新速度大致在每周2-3节。
Emscripten基本介绍绕不过去，ch4之后的章节会开始交流实际项目中遇到的问题和经验。

**Comment by Hapoa** [comment]
这很不错:+1:
