### ISSUE TITLE
建议周刊筛选掉包含大量广告的内容

### ISSUE THREAD

**Issue by unclesmiley** [ruanyf/weekly#4009]
在贵刊 289 期中，[中国开发者上传盗版视频到 NPM](https://www.cnbeta.com.tw/articles/tech/1415071.htm) 超链接页面包含大量广告以及推广，以至于无法正常阅读。

建议周刊筛选掉包含大量广告的内容。@ruanyf

**Comment by kimlee2023** [comment]
加个广告屏蔽浏览器插件就能解决啊。

**Comment by unclesmiley** [comment]
> 加个广告屏蔽浏览器插件就能解决啊。

@kimlee2023 并不是所有浏览器都支持 ad block addon，而对于移动设备用户，则根本无法阅读。

**Comment by ruanyf** [comment]
@unclesmiley 你是说 cnbeta 吗？这条消息，除了他们，好像没看到其他地方发。
