### ISSUE TITLE
Sublime 团队发布的 Git 工具：Sublime Merge

### ISSUE THREAD

**Issue by wilon** [ruanyf/weekly#406]
官网：https://www.sublimemerge.com/

优点：小巧、反应快、界面漂亮

![2019-03-28 at 11 38](https://user-images.githubusercontent.com/7512755/55128297-071ab300-514e-11e9-9448-eaef4b2ea544.gif)

**Comment by ruanyf** [comment]
这个是付费的。周刊一般不介绍付费软件，因为等于做广告了。

**Comment by wilon** [comment]
OK，多谢
