### ISSUE TITLE
【免费中文字体推荐】京华老宋体

### ISSUE THREAD

**Issue by WFANG12719** [ruanyf/weekly#4078]
汉字爱好者、传播者，网名“特里王”参照1961年北京新华字模厂改刻的老筑地体61-1体的旧书，利用AI辅助，完成了“京华老宋体”字体文件的制作，收录了36000多个汉字，特别美观，实测在Windows 10/11 里Winword 2016以上文字编辑工具都可以使用，用一般的激光打印机也可以正确打印出来。
 
作者是汉字爱好者，之前也制作过两款老字体，受到好评。此款字体由于资料比较充足，而且借助AI修正、美化，大大提高了制作速度，堪称完美复刻了这一款老字体。

从作者的介绍来看，制作这一款字体历时至少两年。这里需要指出，不同于西文字体大多数只有几十个字母，加上标点符号、特殊符号，要完成一款西文字体制作只需要完成300~500个字符即可使用。汉字由于字数繁多，常用字就有6000多个，如果要覆盖最新的GB18030-2022标准里的87887个汉字，制作任何一款中文字体工作量相当大。从汉字字体文件大多几十兆，相比英文字体文件只有1-2兆就可以看出其中工作量的区别。

作者在文中还顺便普及了一些汉字的编码知识，而且分享了他所参考使用的Python库，有兴趣的读者可以仔细品尝。
文末作者分享了字体文件的下载，可以免费商用。

我们的邻国日本在计算机字体制作方面一直很发达。日本国内流行的汉字字体种类繁多，且不乏有精品。近些年来随着广大中文字体爱好者的增多和计算机AI的发展，我国国内个人和大厂制作的中文字体也逐渐增多，且很多可以自用、商用。我们为之感到欣慰。

https://zhuanlan.zhihu.com/p/637491623

PS，作者制作的“汇文明朝体”，收录的汉字较少，可以满足一般使用：https://zhuanlan.zhihu.com/p/344103391

**Comment by WFANG12719** [comment]
作者更新到2.002版本了，小米手机商城也有得卖，其它渠道都是免费的。 https://zhuanlan.zhihu.com/p/677725322

**Comment by alexis-michaud** [comment]
请问免费具体什么意思呢？这个字体，具体的license（许可）哪里可以查到呢？
