### ISSUE TITLE
【文章推荐】自然语言进行视频搜索

### ISSUE THREAD

**Issue by TimZhang2090** [ruanyf/weekly#4147]
使用自然语言搜索视频的技术，在视频监控行业应用前景巨大。
https://www.ycombinator.com/launches/Kft-edgetrace-real-world-video-understanding

**Comment by samswift86400** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
