### ISSUE TITLE
一个介绍量子计算，量子通讯的网站

### ISSUE THREAD

**Issue by xwu64** [ruanyf/weekly#432]
本网站由 《Quantum Computation and Quantum Information》的作者制作，期中包含了基础的量子计算知识。同时，网站中包含了上百道简单的练习题，可以帮助初学者检验自己的知识掌握程度。

目前只完成了量子计算相关的知识，未来还将介绍 "Quantum Search Algorithm" 与 "Quantum Teleportation" 相关的知识。

https://quantum.country/qcvc/

**Comment by ruanyf** [comment]
跟 #400 重复了。
