### ISSUE TITLE
中国移动拔尖计划招聘 - 北京移动公司

### ISSUE THREAD

**Issue by wangshouyi323** [ruanyf/weekly#4365]
### 岗位1：
**SRE运维架构师**
### 岗位职责：
入职信息系统部SRE团队。
1、参与业务支撑系统技术架构规划、设计，助力数字化转型。
2、负责微服务体系治理及优化、打造规范化、标准化、高扩展性、高稳定性、高安全性的微服务系统架构；
3、负责稳定性技术标准的制定，项目建设技术方案的评审；
4、负责系统架构的稳定性评估，识别风险，制定改进方案并解决；
5、负责应用系统容量规划及运营，端到端服务调用链路性能瓶颈分析及优化；
6、负责运维自动化的规划及研发，促进生产效率提升；
7、负责运维系统全生命周期运维能力的提炼，持续迭代能力的研发、建设及推广；
8、负责运维领域新技术、新产品的探索研究，端到端可观测体系，智能运维能力等的研发；
9、负责挖掘业务领域的痛点，引导业务优化，在业务全生命周期和交付模式上建立长期的运营制度；
10、负责挖掘各业务条线中的相关风险线索并及时跟进，输出风控专业判断与优化建议，兼顾预防和管理策略的制定和落地；
### 岗位要求
（1）硕士研究生及以上学历（如特别优秀，可放宽到本科），计算机、通信等相关专业优先；
（2）3年以上头部互联网公司SRE工作经验，具备大型系统项目设计和开发经验，精通分布式、高并发系统的设计与开发
（3）掌握SpringCloud体系架构，精通主流的微服务框架构建；
（4）深刻理解Redis、Kafka等主流开源软件技术,具备社区开发经验优先；
（5）精通业务/产品架构规划与实施，业务架构设计相关方法论以及模型设计和领域规划；
（6）清晰的逻辑思维能力，较强的沟通能力，跨部门协同的推动能力，以及复杂沟通环境下的应变能力；
（7）具备SRE体系建设、运维平台架构设计、用户体验优化、业务风险应对、数据稽核治理等工作经验者优先；

-----------------------------------------------------------------------------------------------------------------------------
### 岗位2：
**DevOps技术专家**
### 岗位职责：
入职信息系统部云原生交付开发管理团队。
1. 负责公司业务支撑系统持续交付、统一运维管控等平台的基础架构规划、设计与研发工作，实现平台持续集成持续交付能力和应用管控提升，打造业界领先的运维基础设施平台。包括但不限于计算、存储、数据库、大数据等产品的统一运维管控。
2. 建立并完善Devops工具体系，提高开发效率，降低运维成本，提升整体交付效率。包括不限于代码扫描、SQL审计、安全扫描等工具链能力的构建和持续维护。
3. 制定和执行系统自动化部署计划，保证软件版本控制和各环境的一致性。
4. 负责服务容量规划和性能优化，确保系统高可用和灵活扩展。结合服务治理和故障自愈，落地自动扩缩容机制。
5. 构建端到端的资源需求交付及监控管理能力。
6. 参与制定和执行公司技术战略和计划，协助领导进行技术决策和团队管理。
### 岗位要求
（1）硕士研究生及以上学历（如特别优秀，可放宽到本科），计算机、通信等相关专业优先；
（2）5年以上Devops经验，熟悉PaaS平台的建设和运维，熟悉云原生技术，包括Docker、Kubernetes等主流技术。
（3）对分布式技术、低代码、微服务架构、容器技术、消息队列、多技术栈、存储等相关技术领域有一定了解，对容器、K8s的架构体系以及微服务的本质有较深了解，有实施过企业容器环境开发经验者优先。
（4）熟悉端到端开发流程，具备全链路开发经验。对面向对象编程思想、DDD领域驱动设计、设计模式、设计原则有深入的理解和应用；熟悉主流数据库，如MySQL、Oracle、SQL Server、MongoDB等；熟悉Java语言，熟悉Java应用的编译流程。
（5）具备出色的安全意识，熟悉常见的安全漏洞和攻击手段。
（6）具备优秀的团队协作能力，能够与开发、测试、运维等团队紧密合作。
（7）具备优秀的分析问题和解决问题的能力，能够快速响应并解决系统故障和问题。
（8）具备较强的沟通能力和团队协作能力。
（9）熟悉敏捷开发Scrum流程，拥有项目管理及协作、代码托管、Cl/CD、DevOps、大数据处理等工具开发经验者优先。

------------------------------------------------------------------------------------------------------------------------------
联系方式：
coffee-killer（wx）
wangshouyi@bj.chinamobile.com (email)

**Comment by ruanyf** [comment]
请贴到《谁在招人》那个帖子 https://github.com/ruanyf/weekly/issues/4204
