### ISSUE TITLE
【网站自荐】微寻 - 为个人网站提供微信扫码登录能力

### ISSUE THREAD

**Issue by lvxianchao** [ruanyf/weekly#4399]
[微寻](https://weixunlogin.com) 以极简的方式为个人网站提供微信扫码登录的能力，没有各种复杂的认证审核机制，只需轻松对接两个接口便可为个人网站接入微信扫码登录能力，熟练的开发者可以在 2 个小时（甚至更快）以内接入并发布上线。

<img width="1920" alt="image" src="https://github.com/ruanyf/weekly/assets/22412818/657e199d-4e9b-4c2f-8dc2-7e7fdafad4a0">

<img width="1920" alt="image" src="https://github.com/ruanyf/weekly/assets/22412818/88c03655-12e5-47d7-8c96-523357959e78">

**Comment by Jackiexiao** [comment]
无法访问了

**Comment by lvxianchao** [comment]
> 无法访问了

@Jackiexiao 微信不允许这种方式，已经下架。
