### ISSUE TITLE
工具推荐：LaTeX 公式转换工具

### ISSUE THREAD

**Issue by erdong** [ruanyf/weekly#458]
Mathpix 出品的 Snip 是一个免费的的工具，可用把各种公式转换成 LaTeX。除了印刷的公式，手写公式也能识别转换，但是要求字迹工整。除了公式，化学方程式和矩阵也能识别，支持 Mac、Windows、Ubuntu。

官网地址：https://mathpix.com

**Comment by ruanyf** [comment]
与 #433 重复。

**Comment by erdong** [comment]
不好意思，没有看仔细。

那我关闭这个 Issue 了。
