### ISSUE TITLE
[第 59 期] 软件 Fika - Reader Mode

### ISSUE THREAD

**Issue by yueyericardo** [ruanyf/weekly#473]
chrome 插件 阅读模式
![](https://yyrcd-1256568788.cos.na-siliconvalley.myqcloud.com/yyrcd/2019-04-19-153134.png)

链接：https://chrome.google.com/webstore/detail/fika-reader-mode/fbcdnjeoghampomjjaahjgjghdjdbbcj

**Comment by lenkenlau** [comment]
感谢你的推荐！这是我用到的第一个代码块能高亮的阅读工具
