### ISSUE TITLE
[第 56 期] 命令行的艺术

### ISSUE THREAD

**Issue by sdir** [ruanyf/weekly#478]
大部分是关于Linux命令下的，一些基本又实用的命令。
个人感觉很实用，有多种语言的介绍包括中文。
地址：https://github.com/jlevy/the-art-of-command-line

其中有一个用golang写的快速查找工具，感觉很实用。
项目地址：https://github.com/junegunn/fzf
youtube视频：https://www.youtube.com/watch?v=qgG5Jhi_Els

**Comment by emilytimer** [comment]
阮老师，第一个链接无效，要把最后的句号去掉。

**Comment by sdir** [comment]
@emilytimer 好了
