### ISSUE TITLE
【工具自荐】通过 RSS 订阅外语信源，AI 翻译、摘要后，推送信息简报给你

### ISSUE THREAD

**Issue by jaredliu233** [ruanyf/weekly#4846]
[Tidyread](https://tidyread.ai) 是一款可灵活定制的资讯简报工具，借力 AI，让你以更少的时间阅读更多内容，为你建立起资讯阅读的秩序感。

**高效模式：**
<img width="1470" alt="高效模式" src="https://github.com/user-attachments/assets/8bd5aea4-88f8-48a8-93e6-fd8cd4cbd47b">

**普通模式：**
<img width="1470" alt="普通模式" src="https://github.com/user-attachments/assets/e97a34de-0eb3-4dde-9095-7d7231c2e373">

我们内置了一些高质量信源，供您一键订阅，包括阮老师的周报：
![信源订阅](https://github.com/user-attachments/assets/8cb468ea-6b45-44f9-a2e9-58f7da3e6ccd)

此外您还可以定制自己的 prompt，提供更有价值的摘要：
![recipe-pic](https://github.com/user-attachments/assets/793f4215-a279-42e6-af01-7f43b543426f)

---
### 用户评价
- Zeno:
目前用下来，感觉比 rss 好用，比我当时设想的 mvp 要完善太多太多

- Ken: 
You are making a great tool/product in my opinion. Being able to have feeds of interest summarized so nicely will save people so much time to try to get more information about the topics they are interested in using far less time. This will accelerate growth of knowledge and allow people to learn more even more quickly.

- Saumil:
Beyond its core functionality, Tidyread.ai offers a clean and user-friendly interface. This user-friendly design makes it a perfect tool for anyone who wants to streamline their information consumption process.
If you're looking to overcome information overload and boost your reading productivity, I highly recommend Tidyread.ai. It's a powerful tool that has become an essential part of my daily workflow.

**Comment by ruanyf** [comment]
@jaredliu233 请不要再发 Tidyread 了，我搜了一下，已经发了8次，都成骚扰了。

如果再发，我只能把发布账号拉黑了。

**Comment by jaredliu233** [comment]
> @jaredliu233 请不要再发 Tidyread 了，我搜了一下，已经发了8次，都成骚扰了。
> 
> 如果再发，我只能把发布账号拉黑了。

好的阮老师 @ruanyf ，尊重您的选择，后面不会再发 Tidyread。

不过能否问一下，Tidyread 是什么方面没法被您选上呢？

前三次我推 Tidyread，那时是做了一个纯免费且开源的 Raycast 插件，用自己的 API Key 接入即可。

后面才开始推付费版（但不用 AI 仍然可以免费使用），而且非订阅制，而是用量付费制，我内测阶段是按 3.5 turbo 价格收费的，基本上是等于成本价了。而且我们做了很多功能帮助用户节省 Token，比如动态 Prompt（只提供一部分原文内容供摘要）、智能标题翻译默认选项（比如选择您的周报作为订阅源，如果我是中文用户，则默认不需要用 AI 翻译标题）。我感觉在商业方面我做得算是很良心了。
