### ISSUE TITLE
【工具自荐】Annotree：一款可视化生成目录注释树的工具，大大方便技术文档的编写! (非常好用！欢迎大家来试试！🎉🎉🎉)

### ISSUE THREAD

**Issue by itchaox** [ruanyf/weekly#4880]
项目名称：Annotree
项目简介：一款生成带注释的目录树工具
使用场景：编写技术文档的目录注释树，帮助你高效地编写技术文档。

GitHub 地址：https://github.com/itchaox/annotree
官方文档：https://www.annotree.com/
Annotree 详细功能视频介绍：https://www.bilibili.com/video/BV1fS421R7UM
Annotree 最新功能视频介绍：https://www.bilibili.com/video/BV1Tz421B7AY

> 这是我的第一个正式开源项目，如果对你有帮助，[感谢 Star ⭐️](https://github.com/itchaox/annotree) 和分享给你的朋友们，这对我很重要，[谢谢 💖](https://github.com/itchaox/annotree)！

### 效果演示：
![20240726133750_rec_](https://github.com/user-attachments/assets/a2696842-a85d-4c32-ae44-3c9fa58c08bc)

### 功能概览
1. 扫描目录
2. 导出后自动打开文件
3. 忽略文件夹
4. 忽略以 "." 开头的文件夹
5. 只扫描文件夹忽略以 "." 开头的文件
6. 忽略文件类型
7. 扫描深度
8. 导出文本的默认名称配置
9. 注释格式化
10. 桥梁最短字符数
11. 桥梁填充字符
12. 始终显示桥梁
13. 文件夹和文件的图标显示配置
14. 支持一键复制目录注释树
15. tab 聚焦下一个输入框；shift + tab 聚焦上一个输入框；
16. 编辑区和预览区的同步滚动配置
17. 实时预览效果
18. 删除节点功能
19. 展开和折叠节点功能
20. 扫描前键入需要忽略的文件夹。
21. 扫描前键入需要忽略的文件类型。

**Comment by yxw007** [comment]
你这是每周都发帖给他推啊... star 涨了不少，看来这样搞有效果啊 😄

**Comment by ruanyf** [comment]
请勿重复发布，再发拉黑。

**Comment by itchaox** [comment]
> 请勿重复发布，再发拉黑。

了解了，不好意思哈 🙏🏻

**Comment by itchaox** [comment]
> 你这是每周都发帖给他推啊... star 涨了不少，看来这样搞有效果啊 😄

涨 star，应该主要是我发的 B 站视频
