### ISSUE TITLE
【开源推荐】多个大模型同时对话、生图，支持 Web、浏览器插件

### ISSUE THREAD

**Issue by KwokKwok** [ruanyf/weekly#5077]
阮老师你好，这个项目是一个纯前端的多个大模型同时对话的应用（直接使用用户配置的密钥请求对应的服务端），配置了 GitHub Action 支持自动打包成浏览器插件并提交审核。个人感觉页面做的也比较用心。

主要基于 SiliconCloud API 提供 20 多个国内外大模型。速度极快。

也可以通过自定义模型，引入更多的大模型。针对以下做了内置支持
- OpenAI API 兼容的。这一点可以支持大部分的大模型，基本就是配置一下 请求域名、密钥、要用到的模型就可以了。（还提供一些图标、详情页之类的可选填）
- Google Gemini。 API 与 OpenAI 不兼容，现在已经做了支持，配一下密钥就可以了。（不过实测速度要比其他的低一些。）
- deepseek。虽然 API 与 OpenAI 兼容，但是这个预设比 OpenAI 兼容的预设做的早，所以保留。并且设置会更简单一些，也是配置一下 密钥就可以了。

[Silo - GitHub](https://github.com/KwokKwok/Silo)

[在线体验，可以直接点弹框的”先不注册，用用你的“](https://chat.kwok.ink)

<img width="960" alt="image" src="https://github.com/user-attachments/assets/6a3818af-c288-4b34-947d-8df6a05587a9">

### 作用

1. 日常使用。同时向各个大模型提问。
2. 对比。可以对比测试各个大模型的输出质量、输出速度等，比如之前 0.8 和 0.11 谁大的问题。
3. 项目相关的一些东西，比如富文本输出之类的。
4. 学习浏览器插件开发。有一个[提交](https://github.com/KwokKwok/Silo/commit/552c8950b893f903d02194e9bcaa78332b365ebd)可以看到怎么把当前的项目做成一个浏览器扩展。也可以查看 GitHub Action 看怎么配置自动发布提交审核。（浏览器插件开发使用的 wxt 框架）

### 特性说明

🌐 提供浏览器插件和 Web 端的访问方式
🚀 基于 SiliconCloud API，模型丰富，响应快
🔑 配置简单，只需配置一次密钥
💰 支持 SiliconCloud 余额自动刷新
🧩 可以通过自定义模型的功能来接入更多模型
🔄 支持调整模型顺序
🌙 夜间模式
📱 手机端支持（受限于屏幕尺寸，提供较简单的版本）
📦 纯前端实现（方便迁移、CDN 部署等，不依赖服务器中转）
🔧 模型参数调整
💬 优化的输入体验

### 放一些截图

<img width="1917" alt="image" src="https://github.com/user-attachments/assets/bd25d3d6-2dd8-4497-b62f-e462eb13a155">

<img width="1917" alt="image" src="https://github.com/user-attachments/assets/ed31972a-c0cd-4be0-8d56-dd8f666f024b">

**Comment by lixianmin** [comment]
非常不错的一个项目，去年的时候，我自己也做过一款有些相似的chrome插件，那是基于各大网站的，就是想通过一次性提交message给各大网站，然后通过对比能稍微减少一些幻觉，可惜各大网站不断的在改自己的web页，后来便没有维护了。

顺便推荐一个我现有使用的跟大模型聊天的网址吧： https://chat.notdiamond.ai 免费用gpt 4o与claude 3.5 sonnet这些模型

**Comment by KwokKwok** [comment]
> 阮老师你好，这个项目是一个纯前端的多个大模型同时对话的应用（直接使用用户配置的密钥请求对应的服务端），配置了 GitHub Action 支持自动打包成浏览器插件并提交审核。个人感觉页面做的也比较用心。
> 
> 主要基于 SiliconCloud API 提供 20 多个国内外大模型。速度极快。
> 
> 也可以通过自定义模型，引入更多的大模型。针对以下做了内置支持
> 
> * OpenAI API 兼容的。这一点可以支持大部分的大模型，基本就是配置一下 请求域名、密钥、要用到的模型就可以了。（还提供一些图标、详情页之类的可选填）
> * Google Gemini。 API 与 OpenAI 不兼容，现在已经做了支持，配一下密钥就可以了。（不过实测速度要比其他的低一些。）
> * deepseek。虽然 API 与 OpenAI 兼容，但是这个预设比 OpenAI 兼容的预设做的早，所以保留。并且设置会更简单一些，也是配置一下 密钥就可以了。
> 
> [Silo - GitHub](https://github.com/KwokKwok/Silo)
> 
> [在线体验，可以直接点弹框的”先不注册，用用你的“](https://chat.kwok.ink)
> 
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/22879367/362513041-6a3818af-c288-4b34-947d-8df6a05587a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzI2OTEsIm5iZiI6MTcyNTIzMjM5MSwicGF0aCI6Ii8yMjg3OTM2Ny8zNjI1MTMwNDEtNmEzODE4YWYtYzI4OC00YjM0LTk0N2QtOGRmNmEwNTU4N2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIzMTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTY4ODc0NzI5YzA3M2E3Mzg5OTMzNTU2NTZlZGY2Mzg4NjkyY2IyNjVjY2QzOTE3YjQ3N2E3Y2QyMzY3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vke3-QOraYJsoLa28_TqfSWRDX3wpO9rlpWEi6G8Zdw">
> ### 作用
> 1. 日常使用。同时向各个大模型提问。
> 2. 对比。可以对比测试各个大模型的输出质量、输出速度等，比如之前 0.8 和 0.11 谁大的问题。
> 3. 项目相关的一些东西，比如富文本输出之类的。
> 4. 学习浏览器插件开发。有一个[提交](https://github.com/KwokKwok/Silo/commit/552c8950b893f903d02194e9bcaa78332b365ebd)可以看到怎么把当前的项目做成一个浏览器扩展。也可以查看 GitHub Action 看怎么配置自动发布提交审核。（浏览器插件开发使用的 wxt 框架）
> 
> ### 特性说明
> 🌐 提供浏览器插件和 Web 端的访问方式 🚀 基于 SiliconCloud API，模型丰富，响应快 🔑 配置简单，只需配置一次密钥 💰 支持 SiliconCloud 余额自动刷新 🧩 可以通过自定义模型的功能来接入更多模型 🔄 支持调整模型顺序 🌙 夜间模式 📱 手机端支持（受限于屏幕尺寸，提供较简单的版本） 📦 纯前端实现（方便迁移、CDN 部署等，不依赖服务器中转） 🔧 模型参数调整 💬 优化的输入体验
> 
> ### 放一些截图
> <img alt="image" width="1917" src="https://private-user-images.githubusercontent.com/22879367/362512705-bd25d3d6-2dd8-4497-b62f-e462eb13a155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzI2OTEsIm5iZiI6MTcyNTIzMjM5MSwicGF0aCI6Ii8yMjg3OTM2Ny8zNjI1MTI3MDUtYmQyNWQzZDYtMmRkOC00NDk3LWI2MmYtZTQ2MmViMTNhMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIzMTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZGIwMTA3NWY5ODMzZjU3MTgxMDMyNzc5NjQzNzE5MWEyNWFlYTY1YjY2OGNlZmU0YTE0YjNlZDc1MzFlZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wqyZfi-9tIoHMocDQrGozN6nnd49q_3EfF2PWmEnPzQ"> <img alt="image" width="1917" src="https://private-user-images.githubusercontent.com/22879367/362512869-ed31972a-c0cd-4be0-8d56-dd8f666f024b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzI2OTEsIm5iZiI6MTcyNTIzMjM5MSwicGF0aCI6Ii8yMjg3OTM2Ny8zNjI1MTI4NjktZWQzMTk3MmEtYzBjZC00YmUwLThkNTYtZGQ4ZjY2NmYwMjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIzMTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOThhYWE4NjMwNzhjZGI4MmYxZTg4NzNlYmU1YTdlMTQyOTUwY2M5Mzg0MzNlYjA1ZWMxZGY0NDc5MzFkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PkTX84PMz43dLGid1KElMklje_bH5sPYoJE2uwCdF1A">

生图也支持了

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/ade07b5f-6bfa-40cb-a062-478b0412b46d">

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/f1199adf-6926-4d30-a721-3ee5a258b115">

<img width="1247" alt="image" src="https://github.com/user-attachments/assets/87f6c053-65d5-4566-9ef9-de06eec63bc4">
