### ISSUE TITLE
微软正在推出一款名为Windows Terminal的新命令行应用程序。

### ISSUE THREAD

**Issue by wangweiX** [ruanyf/weekly#511]
https://www.theverge.com/2019/5/6/18527870/microsoft-windows-terminal-command-line-tool

**Comment by erdong** [comment]
我今天也看到这个工具了，准备发在 issue 里。
仓库地址如下：https://github.com/microsoft/Terminal 

Windows Terminal是微软推出的新的命令行应用程序，提供多标签、分割窗口、快捷键、完整的Unicode字符支持等功能。

**Comment by wangweiX** [comment]
http://www.ruanyifeng.com/blog/2019/05/weekly-issue-55.html

**Comment by erdong** [comment]
昨天在文章中看到了。谢谢。
