### ISSUE TITLE
[第 56 期] 个人项目推荐——kindle电子书分享网

### ISSUE THREAD

**Issue by sun1752709589** [ruanyf/weekly#527]
网址：https://kindle.51nazhun.pub/

自荐理由：

个人业余时间搞得一个小网站，以解决自己找电子书的烦恼。后端基于rails，用的技术栈之前写了博文：https://ruby-china.org/topics/38483

建站初衷：解决找电子书的烦恼！不要下载豆，不要积分，无需注册，更无需回复后查看！

**Comment by ChenZhongPu** [comment]
so，侵犯版权这么理直气壮？

**Comment by Lionad-Morotar** [comment]
(⊙﹏⊙) 所以我

**Comment by sun1752709589** [comment]
关于对版权的回应：
https://github.com/sun1752709589/blog/blob/master/2019/05/17/reply_about_copyright.md

**Comment by Lionad-Morotar** [comment]
对zhe'z这种d'g

> 关于对版权的回应：
> https://github.com/sun1752709589/blog/blob/master/2019/05/17/reply_about_copyright.md

一方面我赞成<黑客与画家>一书中曾提及的"黑客对自由的向往"精神(无论是人身自由或是信息自由), 另一方面, 在严制版权的大环境下, 不论楼主的目的, 这是高风险行为. 
所以对这种东西我很难说支持或否, 我们都享受过盗版的便利, 但同时我们也都向往一个更好的社会.

**Comment by sun1752709589** [comment]
> 对zhe'z这种d'g
> 
> > 关于对版权的回应：
> > https://github.com/sun1752709589/blog/blob/master/2019/05/17/reply_about_copyright.md
> 
> 一方面我赞成<黑客与画家>一书中曾提及的"黑客对自由的向往"精神(无论是人身自由或是信息自由), 另一方面, 在严制版权的大环境下, 不论楼主的目的, 这是高风险行为.
> 所以对这种东西我很难说支持或否, 我们都享受过盗版的便利, 但同时我们也都向往一个更好的社会.

谢谢你的提醒，我会适时将它停掉，不会存在太长时间，还是自己用吧。

**Comment by xiongruixu** [comment]
没想到版权的问题引起了这么多争议。这说明了中文圈的版权意识在增强，至少也算是个好事。
在某些环境与场景下，版权问题并没有那么非黑即白。楼主既然已经对潜在的风险有清楚的认识，仍然愿意这么做，我觉得作为受益的一方，除了点赞、感谢并为之祈祷之外，也没有太多能做的。
