### ISSUE TITLE
【工具自荐】用于浏览内容平台时，模糊媒体资源。专注于信息获取，减少视觉干扰，避免公共场合出现尴尬的场景，在泛滥的互联网噪音中夺取注意力阵地。

### ISSUE THREAD

**Issue by Dnevend** [ruanyf/weekly#5443]
- 插件名称：X-Comfort-Browser

- 插件介绍：用于浏览内容平台时，模糊媒体资源。专注于信息获取，减少视觉干扰，避免公共场合出现尴尬的场景，在泛滥的互联网噪音中夺取注意力阵地。

- 官网地址：[X-Comfort-Browser](https://x-comfort-browser.dnevend.site/)

- 开源地址：[Github](https://github.com/dnevend/x-comfort-browser/)

![cover](https://github.com/user-attachments/assets/45e4ab89-ab19-496e-80a3-58a90139930c)

## 详细介绍

信息成瘾和注意力的夺取，在互联网上，平台和用户之间互相形成了彼此同构的势力：
平台通过设计产品的细节给用户以信息反馈（如小红点，精准的内容推荐）使用户养成对这种反馈机制的习惯，来保持用户的活跃度；
从用户角度，为了更多的流量的媒体和帐号，在发布的内容中精心的挑选和设计，穿插一些可能无关联甚至吸引性的图片。
图片的滥用和视频的干扰，形成了一种噪音，使得纯文字的阅读能力和信息的表达深度在这视觉的转移运动中逐渐削弱。

如何获取更多的注意力主动权，保护自己的时间和行为价值，就像做眼保健操一样，是在“课前”需要逐渐的养成良好习惯。

另外推特这样的内容开放的平台，在公共场合浏览时，有可能跳出一两条不合时宜的图片，让自己老脸一红或措手不及。

因为这样的出发点，顺手也想尝试下浏览器插件的开发，便产生了 [X-Comfort-Browser](https://github.com/dnevend/x-comfort-browse/) 这个小工具。

<p align="center">
  <img src="https://raw.githubusercontent.com/Dnevend/x-comfort-browse/refs/heads/main/assets/blur-50.png" alt="X-Comfort-Browser" width="300" />
  <img src="https://raw.githubusercontent.com/Dnevend/x-comfort-browse/refs/heads/main/assets/blur-none.png" alt="X-Comfort-Browser" width="300" />
</p>

## 主要适用
1、减少媒体资源内容造成的注意力分散。
2、避免公共场合突然出现的不适图片造成尴尬。

## 目前支持
- 推特
- 知乎（谷歌商店审核中）

**Comment by 1765659645** [comment]
一看就是经历过

**Comment by QYG2297248353** [comment]
一看就是上班摸鱼的产物
