### ISSUE TITLE
【工具自荐】TempMail 最美临时邮箱 支持iOS 网页端干净清爽没广告

### ISSUE THREAD

**Issue by houzhongjian** [ruanyf/weekly#5455]
我个人觉得我这个项目 是同类型产品中 页面最好看的一个

没有广告，页面清爽，支持多域名，支持iOS

访问链接 [TempMail ( https://tempmail100.com)](https://tempmail100.com/)

![TempMail](https://i.imgur.com/8ijFucc.png)

**Comment by houzhongjian** [comment]
@Stanley-baby 目前没有开源

**Comment by Minhasokz2** [comment]
我个人觉得我这个项目 是同类型产品中 页面最好看的一个

没有广告，页面清爽，支持多域名，支持iOS

访问链接 [TempMail ( https://tempmail.pk)](https://tempmail.pk)

**Comment by Minhasokz2** [comment]
我个人觉得我这个项目 是同类型产品中 页面最好看的一个

[Buy Cosmetics in Pakistan](http://beautyoutlet.pk/)
