### ISSUE TITLE
[第 63 期] 开源项目自荐：中国大陆 31 个省份 1978 年至 2019 年一千多万工商企业注册信息，包含企业名称、注册地址、统一社会信用代码、地区、注册日期、经营范围、法人代表、注册资金、企业类型。

### ISSUE THREAD

**Issue by imhuster** [ruanyf/weekly#607]
项目地址：[imhuster/Enterprise-Registration-Data-of-Chinese-Mainland](https://github.com/imhuster/Enterprise-Registration-Data-of-Chinese-Mainland)
中国大陆 31 个省份 1978 年至 2019 年一千多万工商企业注册信息，包含企业名称、注册地址、统一社会信用代码、地区、注册日期、经营范围、法人代表、注册资金、企业类型。

**Comment by ruanyf** [comment]
数据只到1999？

**Comment by imhuster** [comment]
> 
> 
> 数据只到1999？

后面的数据本周内会上传，因为2000年后数据较多，需要清洗。

**Comment by 990988969** [comment]
3ks  a lot~ 您做出了巨大的贡献！大赞！

**Comment by bensentray** [comment]
imhuster/Enterprise-Registration-Data-of-Chinese-Mainland 这个地址没有数据。

**Comment by imhuster** [comment]
原仓库已删除，麻烦峰哥删除此 issue

**Comment by zuzhiyang** [comment]
为啥删除了呢，刚刚做好了一个检索的服务？

**Comment by zuzhiyang** [comment]
> 3ks a lot~ 您做出了巨大的贡献！大赞！

您下载的能共享下么

**Comment by dad110** [comment]
咋删除了呢 老铁
