### ISSUE TITLE
Listary --- Windows 下的快捷启动与效率搜索工具

### ISSUE THREAD

**Issue by Seven-Steven** [ruanyf/weekly#65]
1. [官网](https://www.listary.com/)
2. [我自己写的使用教程](https://blog.diqigan.cn/20180117/Listary.html)
3. [知乎话题](https://www.zhihu.com/topic/19847885/hot)

**Comment by ruanyf** [comment]
这个软件是针对普通用户的，周刊更多是为程序员服务。而且，有些功能要收费，周刊一般只推荐开源作品。

**Comment by Seven-Steven** [comment]
了解了, 谢谢
