### ISSUE TITLE
AI又出偏门，用算法“脱掉”女性衣服

### ISSUE THREAD

**Issue by ketra21** [ruanyf/weekly#652]
据美国科技媒体Motherboard报道，一名程序员最近开发出一款名叫DeepNude的应用，只要给DeepNude一张女性照片，借助神经网络技术，App可以自动“脱掉”女性身上的衣服，显示出裸体。目前DeepNude只能处理女性照片，如果原图裸露的皮肤越多，处理效果越好；而上传男性照片，最后得出的照片还是替换成女性下体。DeepNude官网已上线，可下载的Windows和Linux应用也在6月23日推出，使用者无需专业知识。这款应用有免费版和50美元付费版。

![](https://wx3.sinaimg.cn/mw690/6283e751gy1g4gwoiqsulj20hi0bogn9.jpg)
Motherboard还联系了DeepNude的创建者，此人化名为“阿尔贝托”（Alberto）。他表示，该软件基于加州大学伯克利分校研究者开发的开源算法pix2pix创建，并使用1万张女性裸图加以训练。这一算法与之前的人工智能换脸技术deepfake算法相似，也和无人车技术所使用的算法相似。“阿尔贝托”表示，该软件目前之所以只能用于女性照片，是因为女性裸体图像更容易在网上找到，但他希望能创建一个男性版本的软件。他还表示，他继续这一实验是出于“有意思”和好奇心。“我不是偷窥狂。我是技术的爱好者，”他说，“继续提升这个算法，最近也是吸取了之前的教训（来自其它创业公司）和经济上的问题，我问我自己是否可以在这个算法上获得经济回报。这就是我创建DeepNude的原因。”

![](https://wx2.sinaimg.cn/mw690/6283e751gy1g4gwnogolpj20hs09hwfp.jpg)

**Comment by shijian123** [comment]
这个技术已经下架了吧？也不怎么道德😂

**Comment by Lionad-Morotar** [comment]
crazy 😂

**Comment by ketra21** [comment]
好吧，那我删掉，确实不太好~~
