### ISSUE TITLE
建议：往期发布过的是否还需要再次发布

### ISSUE THREAD

**Issue by zxhycxq** [ruanyf/weekly#655]
这两天把第一期到最新一期的都看了，发现有个别内容重复出现。

HelloGitHub 应该至少出现了两次，还有个机器人狗的新闻大概也至少出现 了两次。

**Comment by ruanyf** [comment]
谢谢建议，我也希望避免重复内容。

你提到的两个例子，其实不能算重复。Hello GitHub 他们是每月一期，然后还有一个网站；机器狗是产品宣布的时候，发了一个新闻，正式上市前再发一次。

**Comment by xiaohuoni** [comment]
这么认真的嘛
