### ISSUE TITLE
开源项目推荐： 《前端面试宝典 - 图解前端》

### ISSUE THREAD

**Issue by azl397985856** [ruanyf/weekly#682]
这是一份自己总结的关于准备前端面试的一个复习汇总项目，项目不定时更新。

这不仅仅是一份用于求职面试的攻略，也是一份前端er用来检视自己，实现突破的宝典。 希望通过这个指南，大家可以打通自己的任督二脉，在前端的路上更进一步。

本仓库大量采用图的形式来传达知识，所谓一图胜千言，希望通过这种图文并茂的表达方式 让你更容易记住一些抽象，难以理解的概念，《图解前端》是我给它的副标题。

所有的内容按照主题进行分类，大家可以根据自己需要随意传送

![SmartSelect_20190713-142324](https://user-images.githubusercontent.com/12479470/61168631-958f3500-a583-11e9-9e3c-9125336f0060.jpg)
![SmartSelect_20190713-142350](https://user-images.githubusercontent.com/12479470/61168632-9627cb80-a583-11e9-84e7-9304420b54a4.jpg)
![SmartSelect_20190713-142258](https://user-images.githubusercontent.com/12479470/61168630-94f69e80-a583-11e9-96ec-1c9588bea588.jpg)

![SmartSelect_20190713-142136](https://user-images.githubusercontent.com/12479470/61168626-93c57180-a583-11e9-9288-7ccc2ea642dd.jpg)
![SmartSelect_20190713-142204](https://user-images.githubusercontent.com/12479470/61168627-93c57180-a583-11e9-94b3-8c4f8feac9c0.jpg)
![SmartSelect_20190713-142225](https://user-images.githubusercontent.com/12479470/61168628-945e0800-a583-11e9-9be1-2137042bdef5.jpg)

我的目标是做宇宙最强的前端面试指南。 

项目地址：https://github.com/azl397985856/fe-interview
在线阅读： https://lucifer.ren/fe-interview/#/

**Comment by azl397985856** [comment]
请问是被pass掉了么

**Comment by ruanyf** [comment]
看了几条，写得不好。
