### ISSUE TITLE
[第 70 期] [自荐] RutHub: 分享列表型内容的网站，与周刊理念相当契合

### ISSUE THREAD

**Issue by danloh** [ruanyf/weekly#699]
RutHub 网址： https://ruthub.com
希望能成为一个小众的，安静分享知识清单的小站。

可以分享书单，比如关于某个知识点或主题相关的书籍、课程、视频、网页等；
或每周、每月的读书所得、网络所见所闻，就如阮大的周刊一样；
或任何其他列表类型的内容。

主要的意义在于：可以像阮大的周刊一样分享出来，让大家共同受益；
而分享过程也是一个温故、整理和个人沉淀的过程。

不是共享电子书的，是分享如何获取知识的。

现在就可用，还在完善中，欢迎意见和建议，代码是开源的。
目前是前后端分离，正在做spa+ssr混合，
后端使用Rust（Actix），前端使用Angular，也做过Vue版。

网站不收集任何个人信息，注册无需邮箱、手机号，
主机暂时在境外，暂为SPA , 首次打开速度可能有点慢。

**Comment by zjy2931** [comment]
这是中文的吗？

**Comment by feizhaojun** [comment]
有rss吗？

**Comment by danloh** [comment]
暂没有

**Comment by danloh** [comment]
谢谢阮大
