### ISSUE TITLE
[科技趋势新闻推荐]高德推车载AR导航 将陆续应用于后视镜、中控和风挡玻璃

### ISSUE THREAD

**Issue by Anderson-Liu** [ruanyf/weekly#7]
新闻链接： https://www.cnbeta.com/articles/tech/778259.htm

感觉这个未来会很有前景。

![image](https://user-images.githubusercontent.com/8468372/47080190-ea429100-d239-11e8-8622-a4b577fc4356.png)

![image](https://user-images.githubusercontent.com/8468372/47080199-f2023580-d239-11e8-8a46-ac11372f0425.png)

![image](https://user-images.githubusercontent.com/8468372/47080205-f62e5300-d239-11e8-885d-2291fcd2636b.png)

![image](https://user-images.githubusercontent.com/8468372/47080212-faf30700-d239-11e8-9e3a-57aef509d469.png)

![image](https://user-images.githubusercontent.com/8468372/47080216-ffb7bb00-d239-11e8-9057-1be95db4e924.png)

**Comment by Anderson-Liu** [comment]
未来自动驾驶汽车上的挡风玻璃和窗户也许就是类似这样的AR场景，人坐在车里通过AR看到汽车智能计算监测的过程。
当然在现有的需要司机驾驶的汽车上使用也会是一个趋势。

**Comment by ruanyf** [comment]
这个不错，收入本周的周刊。

**Comment by lumm** [comment]
鸡肋，喜欢技术的人可能会觉得新鲜。

**Comment by tjsymbol** [comment]
会不会AR影像误导司机，导致车祸发生
