### ISSUE TITLE
[第 70 期] 自荐：Lite 编程语言

### ISSUE THREAD

**Issue by kulics** [ruanyf/weekly#701]
## 项目推荐
- 项目地址：
https://github.com/kulics/lite

- 类别：编程语言

- 项目后续更新计划：
语法设计已经稳定（1.0-alpha），后续主要精力将放在编译器实现改进迭代，扩展到更多场景。

- 项目描述：
    Lite 是一个专注于工程化的开源通用编程语言。

    这门语言的设计目标是简单性、可读性、可理解性。

    通过去除关键字，减少语法特性，统一表达规范，这门语言可以有效降低读写负担，让使用者能够把真正的注意力放在解决问题上。

    目前支持输出到 C#/Go/TypeScript，借助它们的资源，已经可以在非常广泛的场景下使用这门语言。

- 推荐理由：精心设计的语法，易于编写和阅读。可能是目前世界上语法最精简的静态编程语言。

- 示例代码：
```
main(->) {
    print("Hello, world!")
    greetings = get_greetings("love lite!")
    index:value @ greetings {
        index ?  0 {
            print(value)
        } 1 {
            print(value + ", 世界!")
        } _ {
            print(value + ", world!")
        }
    }
}

get_greetings(first str -> result []str) {
    <- first + {"你好", "Hola", "Bonjour",
                "Ciao", "こんにちは", "안녕하세요",
                "Cześć", "Olá", "Здравствуйте",
                "Chào bạn"}
}
```

**Comment by ruanyf** [comment]
好像是 Eric S. Raymond 说的，一种编程语言想要成功，它必须是一个已经成功的软件的脚本。

建议添加一些实用场景，作为应用实例。
