### ISSUE TITLE
BaiduPCS-Go --- 跨平台的百度网盘客户端

### ISSUE THREAD

**Issue by Seven-Steven** [ruanyf/weekly#71]
[Github地址](https://github.com/iikira/BaiduPCS-Go)

多平台支持, 支持 Windows, macOS, linux, 移动设备等.
百度帐号多用户支持;
通配符匹配网盘路径和 Tab 自动补齐命令和路径, 通配符_百度百科;
下载网盘内文件, 支持多个文件或目录下载, 支持断点续传和单文件并行下载;
上传本地文件, 支持上传大文件(>2GB), 支持多个文件或目录上传;
离线下载, 支持http/https/ftp/电驴/磁力链协议.

**Comment by Seven-Steven** [comment]
最炫酷的事情莫过于这个工具的 CLI 了, 支持 ls, mv等命令, 操作网盘文件如本地般顺滑

**Comment by ruanyf** [comment]
收入第 35 期。
