### ISSUE TITLE
6 款热门 macOS 开源应用

### ISSUE THREAD

**Issue by Alice-sos** [ruanyf/weekly#735]
六款应用都是开源（使用 Swift 和 Objective C 编写），不仅可以免费获得，还有源代码可供观摩借鉴。

[《6 款热门 macOS 开源应用》](https://nextfe.com/macos-201904/)

**Comment by ruanyf** [comment]
警告，请不要一再发文，推广你的网站。

再发的话，你的帐号发被封。
