### ISSUE TITLE
[第 73 期] 自荐： Research  好用的搜索工具，整合百度、微博、知乎、微信、语雀、京东等搜索结果

### ISSUE THREAD

**Issue by ifrontend-xyz** [ruanyf/weekly#747]
[**Research**](http://www.suiyuanka.com/?q=%E9%98%AE%E4%B8%80%E5%B3%B0)
Github: https://github.com/ifrontend-xyz/research
平时搜索搜索时，有时在单一的搜索引擎找不到想要的内容。复制关键字到其他搜索引擎再次搜索时感觉比较麻烦，浪费时间。所以做了一个同步关键字到其他搜索引擎的元搜索工具。 [Research]
可以整合百度、微博、知乎、微信、语雀、京东等搜索结果。
(http://www.suiyuanka.com/?q=%E9%98%AE%E4%B8%80%E5%B3%B0),快速搜索相关内容.
 <img alt="Research" src="https://raw.githubusercontent.com/ifrontend-xyz/research/master/public/screenshot.png" width="100%" />

**Comment by jingkaimori** [comment]
服务地址发生改变，博客中的地址不再可用，能否将博客中的这部分链接改为现在的地址[http://search.kunhai.xyz/](http://search.kunhai.xyz/)

**Comment by ifrontend-xyz** [comment]
> 服务地址发生改变，博客中的地址不再可用，能否将博客中的这部分链接改为现在的地址http://search.kunhai.xyz/
