### ISSUE TITLE
跨平台文件夹同步工具：坚果云

### ISSUE THREAD

**Issue by potterhere** [ruanyf/weekly#75]
跨平台的文件夹同步工具，可以用于文件共享、关键文件夹备份等。同步方式与Git的版本控制相似，也可以找回历史文件版本。因只同步改变的部分，每次消耗流量很少，也很快。
免费版可基本满足日常需求。

官网链接：https://www.jianguoyun.com/

**Comment by ruanyf** [comment]
主要是一个商业工具，周刊一般不推荐收费的商业服务。

**Comment by potterhere** [comment]
嗯嗯，好的，晓得了。 :)
