### ISSUE TITLE
[第 66 期] 关于京阿尼的一个问题

### ISSUE THREAD

**Issue by Anopia** [ruanyf/weekly#751]
阮大大，在第六十六期中写的“日本网友贴出京都动画工作室的内部照片。该工作室被一个神经病放火，已经有30多个动画师遇难。**有人为了抢救画稿，而来不及逃离。**”。
加粗部分是不实信息，虽然听上去很感人，但实际上大家都意识到了生命的重要性，都是及时去逃生的。画稿存于一楼，一楼仅死亡2人，主要死亡人数分布在逃生通道。
希望阮大大可以修改一下。

**Comment by ruanyf** [comment]
谢谢指出，已经删掉了这句话。
