### ISSUE TITLE
vimium --- Chrome 效率插件

### ISSUE THREAD

**Issue by Seven-Steven** [ruanyf/weekly#78]
1. [插件地址](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb)
2. [相对来说比较贴切的介绍文章](https://sspai.com/post/27723)

个人评价:
    像操作 vim 一样操作 chrome 网页, 一定程度上脱离鼠标, 极大地提高了网页操作效率, 堪称神器!

**Comment by Syzq** [comment]
哇，感谢推荐

**Comment by Seven-Steven** [comment]
> 哇，感谢推荐

好东西值得一起分享, 嘻嘻!

**Comment by ruanyf** [comment]
收入第 36 期。

**Comment by RainyH2O** [comment]
[surfingkeys](https://github.com/brookhong/Surfingkeys)功能更强大一些

**Comment by Seven-Steven** [comment]
@RainyH2O 
@guerbai 
试了一下, 很赞!
感谢分享!
