### ISSUE TITLE
[第 83 期]【自荐】在一个自制的操作系统上制作一款游戏

### ISSUE THREAD

**Issue by CasterWx** [ruanyf/weekly#912]
一天吃饭心血来潮，想到能不能把游戏做成游戏操作系统，打包成镜像，装到U盘来启动，这样就可以随时随地带着游戏，找一台电脑直接插入启动即可，而不用烦恼于游戏运行库，或者其他电脑有没有安装游戏。

在之前做的一个操作系统的基础上直接进行开发。

https://github.com/CasterWx/AntzGameOS

(99级大魔王Linus)

![img](https://github.com/CasterWx/AntzGameOS/raw/master/screen/linus.png)

真机运行效果：

![gif](https://github.com/CasterWx/AntzGameOS/raw/master/screen/VID_20191019_173937.gif)

(提issue时刚做完地图模块和初始人物)

**Comment by iamdt** [comment]
大佬
