### ISSUE TITLE
[第 85 期] [自荐] 优秀个人独立博客收录网站，通过分析博客进行评分排序

### ISSUE THREAD

**Issue by wensonsmith** [ruanyf/weekly#946]
网址： https://seekbetter.me

通过分析网站的建站天数，订阅数，浏览量以及上次更新时间进行评分，随着用户参与，优秀博客将会获得更高曝光量。

![image](https://user-images.githubusercontent.com/2544185/68262159-609c7600-007d-11ea-85bb-560eb0e0fe8b.png)

**Comment by platoer** [comment]
网址：[https://rizi.me/](https://rizi.me/)
主题：书和读书
系统：Tiddlywiki
<img width="1130" alt="Snipaste_2019-11-07_16-56-13" src="https://user-images.githubusercontent.com/27715615/68374286-9033a700-017f-11ea-9022-63630da4d45d.png">

**Comment by hapiman** [comment]
感觉还不错

**Comment by richshaw2015** [comment]
跟这个 [https://ohmyrss.com/](https://ohmyrss.com/) 很类似啊

**Comment by HowieHz** [comment]
> 网址： https://seekbetter.me
> 
> 通过分析网站的建站天数，订阅数，浏览量以及上次更新时间进行评分，随着用户参与，优秀博客将会获得更高曝光量。
> 
> ![image](https://user-images.githubusercontent.com/2544185/68262159-609c7600-007d-11ea-85bb-560eb0e0fe8b.png)

已经无法访问了

**Comment by wensonsmith** [comment]
@HowieHz  因为有个博主写了一些你懂的文章，我恰好收录了，然后就被网安局给 BAN  了 😅

**Comment by HowieHz** [comment]
> @HowieHz 因为有个博主写了一些你懂的文章，我恰好收录了，然后就被网安局给 BAN 了 😅

收到。
这有点惨了，搞这些还是别双备吧，顶多备个 icp。
